#!/bin/tcsh

# Set our current directory, which should be the top
# level source for ElmerFoamFSI
set topSourceDir = `pwd`
set installDir = "$topSourceDir/support_install"

# Patch Openfoam build files
cd foam/foam-extend-3.2/ThirdParty/rpmBuild/SPECS/
cp $topSourceDir/Third_Party_Modules/OpenFoamFSI/trunk/SPECSPatch .
patch < SPECSPatch
cd $topSourceDir
cd foam/foam-extend-3.2/etc
cp $topSourceDir/Third_Party_Modules/OpenFoamFSI/trunk/cshrcPatch .
patch < csrchPatch
cd $topSourceDir

# Build OpenFoam
cd foam/foam-extend-3.2
./Allwmake.firstInstall

# Source the SourceScript to ensure the proper build environment
source SourceScript

# Build IMPACT, which will also build IRAD 
cd IMPACT
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$installDir
make
make install
cd $topSourceDir

# Copy the appropriate source files into elmer
cd elmerfem/fem/src/
cp -r $topSourceDir/Third_Party_Modules/ElmerFSI/trunk/native/ ElmerModule
# Patch the elmer source
patch < ElmerModule/ElmerPatch
cd $topSourceDir

# Build elmer and the elmer module
cd elmerfem
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$installDir
make
make install
cd $topSourceDir
# we don't like where elmer installs its libraries
# so we'll link to wehre we want them
ln -s $installDir/share/elmersolver/lib/* $installDir/lib/.

# Build openfoam module
cd Third_Party_Modules/OpenFoamFSI/trunk/native
wmake libso .
cd $topSourceDir

# Build the ElmerFoamFSI driver
mkdir build
cd build
cmake .. -DCMAKE_PREFIX_PATH=$installDir
make
make test
