ElmerFoamFSI: Facet_ID::lid
char lid () const inline
Local edge ID of the halfedge within its element.
Definition at line 37 of file Simple_manifold_2.h.
References _code, and BndID.
Referenced by Simple_manifold_2::get_destination(), Simple_manifold_2::get_edge_index(), Simple_manifold_2::get_next_edge_interior(), Simple_manifold_2::get_next_ghost_edge_interior(), Simple_manifold_2::get_next_real_edge_interior(), Simple_manifold_2::get_prev_edge_interior(), Simple_manifold_2::get_prev_ghost_edge_interior(), Simple_manifold_2::get_prev_real_edge_interior(), is_border(), and operator<().
 { return _code&BndID; }