ElmerFoamFSI: SolverUtils::GeoPrim::C3Line::has_point
bool has_point (const C3Point & p2) const inline
Definition at line 1481 of file GeoPrimitives.H.
References C3Vector::Normalize(), SolverUtils::GeoPrim::TOL, C3Vector::Unit(), and C3Line::v.
Referenced by C3LineSegment::has_point().
     {
       C3Vector v2(p2,p);
       v2.Normalize();
       double r = v2 * v.Unit();
       return( (fabs(r - 1.0) < TOL) ||
               (fabs(r + 1.0) < TOL) );
     };