ElmerFoamFSI: fsicoupling::Run
virtual int Run () inline virtual
Reimplemented from couplingbase.
Definition at line 556 of file FsiCoupling.H.
References agentbase::FinalizeTimeStep(), fluidsAgent, agentbase::InitializeTimeStep(), openfoamagent::Run(), elmeragent::Run(), runMode, simulationFinalTime, simulationTime, simulationTimeStep, structuresAgent, TransferDisplacementsToFluid(), and TransferLoadsToStructures().
Referenced by SerialDriverProgram::DriverRun().
                    {
     FunctionEntry("Run");
     // Enter timestepping
     int innerCount = 0;
     int maxSubSteps = 1000;
     int dumpinterval = 1;
     int systemStep = 0;
     std::stringstream outString;
     outString << std::endl << std::endl
               << "***************************************** " << std::endl;
     outString << "       Starting Stepping in Time          " << std::endl;
     outString << "***************************************** " << std::endl << std::endl;
     outString << "ElmerFoamDriver:Run: Summary of the simulation " << std::endl;
     outString << "     Simulation Type       = ElmerFoamFSI" << std::endl;
     outString << "     Simulation final time = " << simulationFinalTime << std::endl;
     outString << "     Simulation time step  = " << simulationTimeStep << std::endl;
     outString << std::endl;
     StdOut(outString.str(),0,true);
     outString.clear();
     outString.str("");
     while(simulationTime < simulationFinalTime){
       // if(!(time%screenInterval) && (innerCount == 0)){
       // Write some stuff to screen
       outString << "ElmerFoamDriver:Run: System timestep " << ++systemStep
                 << " @ Time = " << simulationTime << std::endl;
       StdOut(outString.str(),1,true);
       outString.clear();
       outString.str("");
       // }
       if(!runMode){
         // Transfer displacements @ Tn to fluids
         outString << "ElmerFoamDriver:Run: Transferring displacements from structures to fluids @ time("
                   << simulationTime << ")" << std::endl;
         StdOut(outString.str(),1,true);
         outString.clear();
         outString.str("");
         TransferDisplacementsToFluid(structuresAgent,fluidsAgent);
       }
       if(runMode < 2){
         fluidsAgent->InitializeTimeStep(simulationTime);
         // Step fluids to get loads @ T(n+1)
         outString << "ElmerFoamDriver:Run: Stepping fluids to time("
                   << simulationTime+simulationTimeStep << ")" << std::endl;
         StdOut(outString.str(),1,true);
         outString.clear();
         outString.str("");
         fluidsAgent->Run(simulationTime+simulationTimeStep);
       }
       if(!runMode){
         // Transfer loads @ T(n+1) to structures
         //std::cout << "FSICoupling: Transferring loads from fluids to structures @ time("
         //          << simulationTime+simulationTimeStep << ")" << std::endl;
         TransferLoadsToStructures(fluidsAgent,structuresAgent);
         // Transfer pressures @ T(n+1) to structures
         //std::cout << "FSICoupling: Transferring pressures from fluids to structures @ time("
         //          << simulationTime+simulationTimeStep << ")" << std::endl;
         //TransferPressuresToStructures(fluidsAgent,structuresAgent);
         //std::cout << "FSICoupling: Transferring pressures from fluids to structures with "
         //          << "TransferLoad function" << std::endl;
         //int err = transferAgent->TransferLoad("pressure","Loads",true);
         //if(err == -1){
         //  std::cout << "FSICoupling: Error: Unable to transfer pressures from fluids agent"
         //            << "to loads at structures agent." << std::endl;
         //  exit(1);
         //}
       }
       if(!(runMode==1)){
         structuresAgent->InitializeTimeStep(simulationTime);
         // Step structures to get displacements @ T(n+1)
         /* WK
         outString << "ElmerFoamDriver:Run: Stepping structures to time("
                   << simulationTime+simulationTimeStep << ")" << std::endl; */
         outString << "ElmerFoamDriver:Run: Stepping structures to time("
                   << simulationTime+simulationTimeStep << ")" << std::endl;
         StdOut(outString.str(),1,true);
         outString.clear();
         outString.str("");
         structuresAgent->Run(simulationTime+simulationTimeStep);
       }
       // Finalize timestep and advance time T(n) --> T(n+1)
       bool converged = true;
       if(converged){
         simulationTime += simulationTimeStep;
         outString << "ElmerFoamDriver:Run: Converged at time("
                   << simulationTime << ")" << std::endl;
         outString << "ElmerFoamDriver:Run: Converged at time("
                   << simulationTime << ")" << std::endl;
         StdOut(outString.str(),1,true);
         outString.clear();
         outString.str("");
         if(runMode < 2)
           fluidsAgent->FinalizeTimeStep(simulationTime+simulationTimeStep);
         if(!(runMode == 1))
           structuresAgent->FinalizeTimeStep(simulationTime+simulationTimeStep);
         innerCount = 0;
       } else {
         innerCount++;
         if(innerCount > maxSubSteps){
           outString << "ElmerFoamDriver:Run: Failed to converge after "
                     << maxSubSteps << ", giving up." << std::endl;
           StdOut(outString.str(),0,true);
           outString.clear();
           outString.str("");
           return(1);
         }
       }
      StdOut(outString.str(),0,true);
      outString.clear();
      outString.str("");
       if(!(systemStep%dumpinterval)){
         //DumpSolution();
       }
     }
     FunctionExit("Run");
     return(0);
   };