ElmerFoamFSI: IRAD::Global::GlobalObj::FunctionEntry
virtual void FunctionEntry (const StackType & stackentry) inline virtual
FunctionEntry updates the Stack as well as the Profiler.
Definition at line 254 of file Global.H.
Referenced by fsicouplingpar::Initialize(), fsicoupling::Initialize(), fsicouplingpar::Run(), and fsicoupling::Run().
{
         _Stack.push_front(FName()+stackentry);
         if(_profiling_enabled && _Profiler)
           _Profiler->FunctionEntry(FName()+stackentry);
         if(_debug_level > 1 && _DebugStream)
           *_DebugStream << "GlobalDebugging:FunctionEntry(" << FName() + stackentry << ")" << std::endl;
       };