ElmerFoamFSI: ElmerModuleDriver::TestingObject::Test__ExampleFunction
virtual void Test__ExampleFunction (ResultsType & result) inline virtual
Test for ElmerModuleDriver::ExampleFunction.
Parameters
result ElmerModuleDriver::TestResults object to store test results.
This function implements a simple test of the function ElmerModuleDriver::ExampleFunction - which is designed to simply return a copy of the input string.
List of Serial tests
Definition at line 154 of file ElmerModuleDriverTest.H.
References ElmerModuleDriver::ExampleFunction(), and TestingObject< ResultsType >::ExampleTestFixture.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       // This is an actual test of the function called
       // ExampleFunction.   The name Test__XXXXX will
       // eventually help automated utilities with
       // running tests by name.
       std::string ExampleResult(ExampleFunction(ExampleTestFixture));
       result.UpdateResult("ExampleFunction:Works",
                           ExampleResult == ExampleTestFixture);
       result.UpdateResult("ExampleFunction:Fails",
                           ExampleResult != ExampleTestFixture);
     }