ElmerFoamFSI: Simple_manifold_2::get_prev_ghost_edge_interior
Edge_ID get_prev_ghost_edge_interior (const Edge_ID & eID) const inline private
Definition at line 772 of file Simple_manifold_2.h.
References _is_str, _maxsize_real_elmts, _nspe, _oeIDs_ghost, _oeIDs_real_or_str, COM_assertion, Facet_ID::eid(), get_edge_index(), is_ghost_element(), and Facet_ID::lid().
Referenced by get_next_ghost_edge(), and get_prev_ghost_edge().
{
     COM_assertion( is_ghost_element( eID.eid()));
     // If not a border edge, then track it within an element.
     int i=(eID.lid()?eID.lid()-1:_nspe-1);
     if ( _is_str) {
       int eindex = get_edge_index( Edge_ID(eID.eid(), i));
       while ( _oeIDs_real_or_str[eindex--]==Edge_ID()) { --i; assert(i); }
     }
     else {
       int eindex = get_edge_index( Edge_ID(eID.eid(), i), _maxsize_real_elmts);
       while ( _oeIDs_ghost[eindex--]==Edge_ID()) { --i; assert(i); }
     }
     return Edge_ID( eID.eid(), i);
   }