ElmerFoamFSI: fsicoupling::TransferLoadsToStructures
int TransferLoadsToStructures (fluidagent * fluidAgent, solidagent * solidAgent) inline
Definition at line 176 of file FsiCoupling.H.
References COM_get_array(), fluidsInterfaceName, GlobalObj< StackType, ErrorType, ProfilerType >::StdOut(), structuresInterfaceName, TransferObject::Transfer(), transferAgent, and verblevel.
Referenced by Run(), TestingObject< ResultsType >::Test__SolidAgentRun(), and TestingObject< ResultsType >::Test__TransferLoadsToStructures().
   {
     std::stringstream outString;
     int stride = 0;
     int cap = 0;
     double *tractions = NULL;
     COM_get_array((fluidsInterfaceName+".traction").c_str(),101,&tractions,&stride,&cap);
     int isize = cap*stride;
     outString << "Transfering loads to the structures solver." << std::endl;
     StdOut(outString.str(),2,true);
     outString.clear();
     outString.str("");
     if (verblevel >= 3){
       outString << "Tractions (driver): " << std::endl;
       for(int i = 0;i < isize/3;i++)
         outString << tractions[3*i + 0] << " "
                   << tractions[3*i + 1] << " "
                   << tractions[3*i + 2] << std::endl;
       StdOut(outString.str(),3,true);
       outString.clear();
       outString.str("");
     }
     transferAgent->Transfer("traction","Loads",true);
     //Get loads array from solid solver to check
     if (verblevel >= 3){
       int solidLoadStride = 0, solidLoadCap = 0;
       double  *solidLoads = NULL;
       COM_get_array((structuresInterfaceName+".Loads").c_str(),11,&solidLoads,
                      &solidLoadStride,&solidLoadCap);
       int solidLoadsize = solidLoadCap*solidLoadStride;
       outString << "Loads transfered to the solid : " << std::endl;
       for(int i = 0;i < solidLoadsize;i++){
         outString << std::setprecision(15) << "solidLoads(" << i << ") = " << solidLoads[i] << std::endl;
       StdOut(outString.str(),3,true);
       outString.clear();
       outString.str("");
       }
     }
     return(0);
   };