ElmerFoamFSI: SolverUtils::GeoPrim::CLine::has_point
bool has_point (const CPoint & p2) const inline
Definition at line 1351 of file GeoPrimitives.H.
References CVector::normalize(), SolverUtils::GeoPrim::TOL, CVector::unit(), and CLine::v.
Referenced by CLineSegment::has_point().
     {
       CVector v2(p2,p);
       v2.normalize();
       double r = v2 * v.unit();
       return( (fabs(r - 1.0) < TOL) ||
               (fabs(r + 1.0) < TOL) );
     };