ElmerFoamFSI: SolverUtils::GeoPrim::C3Box::intersect
C3Box intersect (const C3Box & b) const inline
Definition at line 1981 of file GeoPrimitives.H.
References C3Box::collide(), C3Box::p1, C3Box::p2, C3Point::x(), C3Point::y(), and C3Point::z().
     {
       C3Box retval;
       if(collide(b)){
         retval.p1.x(b.p1.x() > p1.x() ? b.p1.x() : p1.x());
         retval.p1.y(b.p1.y() > p1.y() ? b.p1.y() : p1.y());
         retval.p1.z(b.p1.z() > p1.z() ? b.p1.z() : p1.z());
         retval.p2.x(b.p2.x() < p2.x() ? b.p2.x() : p2.x());
         retval.p2.y(b.p2.y() < p2.y() ? b.p2.y() : p2.y());
         retval.p2.z(b.p2.z() < p2.z() ? b.p2.z() : p2.z());
       }
       return(retval);
     };