ElmerFoamFSI: Element_node_vectors_k_const::set
void set (const DataItem * a, Element_node_enumerator & ene) inline
initialize the accessor from an attribute assiciated with a pane.
Definition at line 228 of file Element_accessors.hpp.
References Element_node_vectors_k_const< Value >::_attr, Element_node_vectors_k_const< Value >::_offsets, Element_node_vectors_k_const< Value >::_vs, COM_assertion, COM_get_sizeof(), DataItem::data_type(), Pane::id(), DataItem::is_nodal(), DataItem::pane(), DataItem::pointer(), DataItem::size_of_components(), Element_node_enumerator::size_of_nodes(), and DataItem::stride().
{
     COM_assertion( a->is_nodal() && a->pane()->id());
     COM_assertion( sizeof(Value)==COM_get_sizeof( a->data_type(),1));
     int ncomp = a->size_of_components();
     int strd = a->stride();
     int nn = ene.size_of_nodes();
     if ( ncomp<=strd) {
       const Value *p = reinterpret_cast<const Value*>(a->pointer());
       _attr = NULL;
       for ( int i=0; i<nn; ++i) _vs[i] = &p[(ene[i]-1)*strd];
     }
     else {
       _attr = a;
       for ( int i=0; i<nn; ++i) _offsets[i] = ene[i]-1;
     }
   }