ElmerFoamFSI: ElmerFoamFSI::SerialDriverProgram::VerbLevel
int VerbLevel () const inline
Returns verbosity level.
Definition at line 276 of file Driver.H.
References SerialDriverProgram::verblevel.
Referenced by ElmerFoamFSI::ExampleProgram::Driver(), ElmerModuleDriver::ExampleProgram::Driver(), and ElmerFoamFSI::Driver().
 { return verblevel;};