ElmerFoamFSI: ElmerFoamFSI::SerialDriverProgram::~SerialDriverProgram
virtual ~SerialDriverProgram () inline virtual
Destructor.
Definition at line 280 of file Driver.H.
References COM_finalize(), COM_initialized(), SerialDriverProgram::Ouf, GlobalObj< StackType, int, ProfilerType >::Report(), and GlobalObj< StackType, int, ProfilerType >::SetOutStream().
{
       if(COM_initialized())
         COM_finalize();
       Report(Ouf);
       if(Ouf){
         Ouf.close();
         SetOutStream(std::cout);
       }
     };