ElmerFoamFSI: OpenFoamModuleDriver::TestingObject::Test__ModuleMeshRegistration
virtual void Test__ModuleMeshRegistration (ResultsType & result) inline virtual
Definition at line 663 of file OpenFoamModuleDriverTest.H.
References TestingObject< ResultsType >::GetInputData(), and TestingObject< ResultsType >::SourceDirPath.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       std::cout << "Running Test__ModuleMeshRegistration" << std::endl;
       //load OpenFoam module
       COM_LOAD_MODULE_STATIC_DYNAMIC(OpenFoamFSI, "OFModule");
       // Test Initalize function exists
       int initHandle = COM_get_function_handle("OFModule.InitFoam");
       //Call GetInputData to copy input test data to temp directory for running tests.
       std::string suffix = "/share/Testing/test_data/HronTurekFsi";
       std::string dirName = SourceDirPath + suffix;
       std::string testDir = IRAD::Sys::CWD() + "/UnitTestDataMeshTest";
       int IntDir = GetInputData(dirName, testDir);
       std::string fluidDir = testDir + "/fluid";
       std::string OrgDir = IRAD::Sys::CWD();
       IntDir = IRAD::Sys::ChDir(fluidDir);
       // call init to setup the mesh
       int dummy1=1;
       char *dummy2[2];
       dummy2[0] = const_cast<char *>(std::string("meshReg").c_str());
       dummy2[1] = NULL;
       int verb=3;
       COM_call_function(initHandle, &dummy1, &dummy2, &verb);
       // get information about what was registered in this window
       int numDataItems=0;
       std::string output;
       COM_get_dataitems("OFModule", &numDataItems, output);
       std::istringstream Istr(output);
       std::vector<std::string> dataItemNames;
       for (int i=0; i<numDataItems; ++i) {
         std::string name;
         Istr >> name;
         dataItemNames.push_back(name);
         std::cout << "DataItem # " << i << ": " << name << std::endl;
       }
       // list of panes in this window
       int numPanes;
       int* paneList;
       COM_get_panes("OFModule", &numPanes, &paneList);
       std::cout << "Number of Panes " << numPanes << std::endl;
       for (int i=0; i<numPanes; ++i)
         std::cout << "Pane ID # " << i+1 << "=" << paneList[i] << std::endl;
       // only one pane for serial runs
       int pane = paneList[0];
       // Check coordinate values
       bool coordCorrect = false;
       double* Coord;
       COM_get_array("OFModule.nc", pane, &Coord);
       if (Coord == NULL) {
         std::cout << "In Test__ModuleMeshRegistration:  No mesh coordinates registered."
                   << std::endl;
         return;
       } else {
         result.UpdateResult("CoordinateData:Registered", true);
       }
       // check for expected number of nodes
       int numNodes = 0;
       int numNodesExpected = 338;
       COM_get_size("OFModule.nc", pane, &numNodes);
       if (numNodes != numNodesExpected) {
         std::cout << "Wrong number of nodes registered for this mesh." << std::endl;
         std::cout << "Got " << numNodes << " Expected: " << numNodesExpected << std::endl;
       } else {
         coordCorrect = true;
       }
       // Arrays eith old data for check
       // move to auxilary function to clean up...
       //std::vector< std::vector<double> > CoordCheck;
       double CoordCheck[338][3] =
       //CoordCheck.push_back(std::vector<double> tmp(
         { {0.299528, 0.21, -0.025334},
         {0.299528, 0.21, 0.025334},
         {0.295179, 0.21, 0.025334},
         {0.295179, 0.21, -0.025334},
         {0.291124, 0.21, 0.025334},
         {0.291124, 0.21, -0.025334},
         {0.287343, 0.21, 0.025334},
         {0.287343, 0.21, -0.025334},
         {0.283818, 0.21, 0.025334},
         {0.283818, 0.21, -0.025334},
         {0.280531, 0.21, 0.025334},
         {0.280531, 0.21, -0.025334},
         {0.277466, 0.21, 0.025334},
         {0.277466, 0.21, -0.025334},
         {0.274609, 0.21, 0.025334},
         {0.274609, 0.21, -0.025334},
         {0.271945, 0.21, 0.025334},
         {0.271945, 0.21, -0.025334},
         {0.26946, 0.21, 0.025334},
         {0.26946, 0.21, -0.025334},
         {0.267144, 0.21, 0.025334},
         {0.267144, 0.21, -0.025334},
         {0.264984, 0.21, 0.025334},
         {0.264984, 0.21, -0.025334},
         {0.262971, 0.21, 0.025334},
         {0.262971, 0.21, -0.025334},
         {0.261093, 0.21, 0.025334},
         {0.261093, 0.21, -0.025334},
         {0.259343, 0.21, 0.025334},
         {0.259343, 0.21, -0.025334},
         {0.25771, 0.21, 0.025334},
         {0.25771, 0.21, -0.025334},
         {0.256188, 0.21, 0.025334},
         {0.256188, 0.21, -0.025334},
         {0.254769, 0.21, 0.025334},
         {0.254769, 0.21, -0.025334},
         {0.253446, 0.21, 0.025334},
         {0.253446, 0.21, -0.025334},
         {0.252213, 0.21, 0.025334},
         {0.252213, 0.21, -0.025334},
         {0.251062, 0.21, 0.025334},
         {0.251062, 0.21, -0.025334},
         {0.24999, 0.21, 0.025334},
         {0.24999, 0.21, -0.025334},
         {0.24899, 0.21, 0.025334},
         {0.24899, 0.21, -0.025334},
         {0.295179, 0.19, 0.025334},
         {0.299528, 0.19, 0.025334},
         {0.299528, 0.19, -0.025334},
         {0.295179, 0.19, -0.025334},
         {0.291124, 0.19, 0.025334},
         {0.291124, 0.19, -0.025334},
         {0.287343, 0.19, 0.025334},
         {0.287343, 0.19, -0.025334},
         {0.283818, 0.19, 0.025334},
         {0.283818, 0.19, -0.025334},
         {0.280531, 0.19, 0.025334},
         {0.280531, 0.19, -0.025334},
         {0.277466, 0.19, 0.025334},
         {0.277466, 0.19, -0.025334},
         {0.274609, 0.19, 0.025334},
         {0.274609, 0.19, -0.025334},
         {0.271945, 0.19, 0.025334},
         {0.271945, 0.19, -0.025334},
         {0.26946, 0.19, 0.025334},
         {0.26946, 0.19, -0.025334},
         {0.267144, 0.19, 0.025334},
         {0.267144, 0.19, -0.025334},
         {0.264984, 0.19, 0.025334},
         {0.264984, 0.19, -0.025334},
         {0.262971, 0.19, 0.025334},
         {0.262971, 0.19, -0.025334},
         {0.261093, 0.19, 0.025334},
         {0.261093, 0.19, -0.025334},
         {0.259343, 0.19, 0.025334},
         {0.259343, 0.19, -0.025334},
         {0.25771, 0.19, 0.025334},
         {0.25771, 0.19, -0.025334},
         {0.256188, 0.19, 0.025334},
         {0.256188, 0.19, -0.025334},
         {0.254769, 0.19, 0.025334},
         {0.254769, 0.19, -0.025334},
         {0.253446, 0.19, 0.025334},
         {0.253446, 0.19, -0.025334},
         {0.252213, 0.19, 0.025334},
         {0.252213, 0.19, -0.025334},
         {0.251062, 0.19, 0.025334},
         {0.251062, 0.19, -0.025334},
         {0.24999, 0.19, 0.025334},
         {0.24999, 0.19, -0.025334},
         {0.24899, 0.19, -0.025334},
         {0.24899, 0.19, 0.025334},
         {0.6, 0.19, -0.025334},
         {0.6, 0.19, 0.025334},
         {0.6, 0.195, 0.025334},
         {0.6, 0.195, -0.025334},
         {0.6, 0.2, 0.025334},
         {0.6, 0.2, -0.025334},
         {0.6, 0.205, 0.025334},
         {0.6, 0.205, -0.025334},
         {0.6, 0.21, 0.025334},
         {0.6, 0.21, -0.025334},
         {0.594992, 0.21, 0.025334},
         {0.594992, 0.21, -0.025334},
         {0.589984, 0.21, 0.025334},
         {0.589984, 0.21, -0.025334},
         {0.584976, 0.21, 0.025334},
         {0.584976, 0.21, -0.025334},
         {0.579969, 0.21, 0.025334},
         {0.579969, 0.21, -0.025334},
         {0.574961, 0.21, 0.025334},
         {0.574961, 0.21, -0.025334},
         {0.569953, 0.21, 0.025334},
         {0.569953, 0.21, -0.025334},
         {0.564945, 0.21, 0.025334},
         {0.564945, 0.21, -0.025334},
         {0.559937, 0.21, 0.025334},
         {0.559937, 0.21, -0.025334},
         {0.554929, 0.21, 0.025334},
         {0.554929, 0.21, -0.025334},
         {0.549921, 0.21, 0.025334},
         {0.549921, 0.21, -0.025334},
         {0.544913, 0.21, 0.025334},
         {0.544913, 0.21, -0.025334},
         {0.539906, 0.21, 0.025334},
         {0.539906, 0.21, -0.025334},
         {0.534898, 0.21, 0.025334},
         {0.534898, 0.21, -0.025334},
         {0.52989, 0.21, 0.025334},
         {0.52989, 0.21, -0.025334},
         {0.524882, 0.21, 0.025334},
         {0.524882, 0.21, -0.025334},
         {0.519874, 0.21, 0.025334},
         {0.519874, 0.21, -0.025334},
         {0.514866, 0.21, 0.025334},
         {0.514866, 0.21, -0.025334},
         {0.509858, 0.21, 0.025334},
         {0.509858, 0.21, -0.025334},
         {0.50485, 0.21, 0.025334},
         {0.50485, 0.21, -0.025334},
         {0.499843, 0.21, 0.025334},
         {0.499843, 0.21, -0.025334},
         {0.494835, 0.21, 0.025334},
         {0.494835, 0.21, -0.025334},
         {0.489827, 0.21, 0.025334},
         {0.489827, 0.21, -0.025334},
         {0.484819, 0.21, 0.025334},
         {0.484819, 0.21, -0.025334},
         {0.479811, 0.21, 0.025334},
         {0.479811, 0.21, -0.025334},
         {0.474803, 0.21, 0.025334},
         {0.474803, 0.21, -0.025334},
         {0.469795, 0.21, 0.025334},
         {0.469795, 0.21, -0.025334},
         {0.464787, 0.21, 0.025334},
         {0.464787, 0.21, -0.025334},
         {0.45978, 0.21, 0.025334},
         {0.45978, 0.21, -0.025334},
         {0.454772, 0.21, 0.025334},
         {0.454772, 0.21, -0.025334},
         {0.449764, 0.21, 0.025334},
         {0.449764, 0.21, -0.025334},
         {0.444756, 0.21, 0.025334},
         {0.444756, 0.21, -0.025334},
         {0.439748, 0.21, 0.025334},
         {0.439748, 0.21, -0.025334},
         {0.43474, 0.21, 0.025334},
         {0.43474, 0.21, -0.025334},
         {0.429732, 0.21, 0.025334},
         {0.429732, 0.21, -0.025334},
         {0.424724, 0.21, 0.025334},
         {0.424724, 0.21, -0.025334},
         {0.419717, 0.21, 0.025334},
         {0.419717, 0.21, -0.025334},
         {0.414709, 0.21, 0.025334},
         {0.414709, 0.21, -0.025334},
         {0.409701, 0.21, 0.025334},
         {0.409701, 0.21, -0.025334},
         {0.404693, 0.21, 0.025334},
         {0.404693, 0.21, -0.025334},
         {0.399685, 0.21, 0.025334},
         {0.399685, 0.21, -0.025334},
         {0.394677, 0.21, 0.025334},
         {0.394677, 0.21, -0.025334},
         {0.389669, 0.21, 0.025334},
         {0.389669, 0.21, -0.025334},
         {0.384661, 0.21, 0.025334},
         {0.384661, 0.21, -0.025334},
         {0.379654, 0.21, 0.025334},
         {0.379654, 0.21, -0.025334},
         {0.374646, 0.21, 0.025334},
         {0.374646, 0.21, -0.025334},
         {0.369638, 0.21, 0.025334},
         {0.369638, 0.21, -0.025334},
         {0.36463, 0.21, 0.025334},
         {0.36463, 0.21, -0.025334},
         {0.359622, 0.21, 0.025334},
         {0.359622, 0.21, -0.025334},
         {0.354614, 0.21, 0.025334},
         {0.354614, 0.21, -0.025334},
         {0.349606, 0.21, 0.025334},
         {0.349606, 0.21, -0.025334},
         {0.344599, 0.21, 0.025334},
         {0.344599, 0.21, -0.025334},
         {0.339591, 0.21, 0.025334},
         {0.339591, 0.21, -0.025334},
         {0.334583, 0.21, 0.025334},
         {0.334583, 0.21, -0.025334},
         {0.329575, 0.21, 0.025334},
         {0.329575, 0.21, -0.025334},
         {0.324567, 0.21, 0.025334},
         {0.324567, 0.21, -0.025334},
         {0.319559, 0.21, 0.025334},
         {0.319559, 0.21, -0.025334},
         {0.314551, 0.21, 0.025334},
         {0.314551, 0.21, -0.025334},
         {0.309543, 0.21, 0.025334},
         {0.309543, 0.21, -0.025334},
         {0.304536, 0.21, 0.025334},
         {0.304536, 0.21, -0.025334},
         {0.304536, 0.19, 0.025334},
         {0.304536, 0.19, -0.025334},
         {0.309543, 0.19, 0.025334},
         {0.309543, 0.19, -0.025334},
         {0.314551, 0.19, 0.025334},
         {0.314551, 0.19, -0.025334},
         {0.319559, 0.19, 0.025334},
         {0.319559, 0.19, -0.025334},
         {0.324567, 0.19, 0.025334},
         {0.324567, 0.19, -0.025334},
         {0.329575, 0.19, 0.025334},
         {0.329575, 0.19, -0.025334},
         {0.334583, 0.19, 0.025334},
         {0.334583, 0.19, -0.025334},
         {0.339591, 0.19, 0.025334},
         {0.339591, 0.19, -0.025334},
         {0.344599, 0.19, 0.025334},
         {0.344599, 0.19, -0.025334},
         {0.349606, 0.19, 0.025334},
         {0.349606, 0.19, -0.025334},
         {0.354614, 0.19, 0.025334},
         {0.354614, 0.19, -0.025334},
         {0.359622, 0.19, 0.025334},
         {0.359622, 0.19, -0.025334},
         {0.36463, 0.19, 0.025334},
         {0.36463, 0.19, -0.025334},
         {0.369638, 0.19, 0.025334},
         {0.369638, 0.19, -0.025334},
         {0.374646, 0.19, 0.025334},
         {0.374646, 0.19, -0.025334},
         {0.379654, 0.19, 0.025334},
         {0.379654, 0.19, -0.025334},
         {0.384661, 0.19, 0.025334},
         {0.384661, 0.19, -0.025334},
         {0.389669, 0.19, 0.025334},
         {0.389669, 0.19, -0.025334},
         {0.394677, 0.19, 0.025334},
         {0.394677, 0.19, -0.025334},
         {0.399685, 0.19, 0.025334},
         {0.399685, 0.19, -0.025334},
         {0.404693, 0.19, 0.025334},
         {0.404693, 0.19, -0.025334},
         {0.409701, 0.19, 0.025334},
         {0.409701, 0.19, -0.025334},
         {0.414709, 0.19, 0.025334},
         {0.414709, 0.19, -0.025334},
         {0.419717, 0.19, 0.025334},
         {0.419717, 0.19, -0.025334},
         {0.424724, 0.19, 0.025334},
         {0.424724, 0.19, -0.025334},
         {0.429732, 0.19, 0.025334},
         {0.429732, 0.19, -0.025334},
         {0.43474, 0.19, 0.025334},
         {0.43474, 0.19, -0.025334},
         {0.439748, 0.19, 0.025334},
         {0.439748, 0.19, -0.025334},
         {0.444756, 0.19, 0.025334},
         {0.444756, 0.19, -0.025334},
         {0.449764, 0.19, 0.025334},
         {0.449764, 0.19, -0.025334},
         {0.454772, 0.19, 0.025334},
         {0.454772, 0.19, -0.025334},
         {0.45978, 0.19, 0.025334},
         {0.45978, 0.19, -0.025334},
         {0.464787, 0.19, 0.025334},
         {0.464787, 0.19, -0.025334},
         {0.469795, 0.19, 0.025334},
         {0.469795, 0.19, -0.025334},
         {0.474803, 0.19, 0.025334},
         {0.474803, 0.19, -0.025334},
         {0.479811, 0.19, 0.025334},
         {0.479811, 0.19, -0.025334},
         {0.484819, 0.19, 0.025334},
         {0.484819, 0.19, -0.025334},
         {0.489827, 0.19, 0.025334},
         {0.489827, 0.19, -0.025334},
         {0.494835, 0.19, 0.025334},
         {0.494835, 0.19, -0.025334},
         {0.499843, 0.19, 0.025334},
         {0.499843, 0.19, -0.025334},
         {0.50485, 0.19, 0.025334},
         {0.50485, 0.19, -0.025334},
         {0.509858, 0.19, 0.025334},
         {0.509858, 0.19, -0.025334},
         {0.514866, 0.19, 0.025334},
         {0.514866, 0.19, -0.025334},
         {0.519874, 0.19, 0.025334},
         {0.519874, 0.19, -0.025334},
         {0.524882, 0.19, 0.025334},
         {0.524882, 0.19, -0.025334},
         {0.52989, 0.19, 0.025334},
         {0.52989, 0.19, -0.025334},
         {0.534898, 0.19, 0.025334},
         {0.534898, 0.19, -0.025334},
         {0.539906, 0.19, 0.025334},
         {0.539906, 0.19, -0.025334},
         {0.544913, 0.19, 0.025334},
         {0.544913, 0.19, -0.025334},
         {0.549921, 0.19, 0.025334},
         {0.549921, 0.19, -0.025334},
         {0.554929, 0.19, 0.025334},
         {0.554929, 0.19, -0.025334},
         {0.559937, 0.19, 0.025334},
         {0.559937, 0.19, -0.025334},
         {0.564945, 0.19, 0.025334},
         {0.564945, 0.19, -0.025334},
         {0.569953, 0.19, 0.025334},
         {0.569953, 0.19, -0.025334},
         {0.574961, 0.19, 0.025334},
         {0.574961, 0.19, -0.025334},
         {0.579969, 0.19, 0.025334},
         {0.579969, 0.19, -0.025334},
         {0.584976, 0.19, 0.025334},
         {0.584976, 0.19, -0.025334},
         {0.589984, 0.19, 0.025334},
         {0.589984, 0.19, -0.025334},
         {0.594992, 0.19, 0.025334},
         {0.594992, 0.19, -0.025334} };
       // check the node positions
       for(int i=0; i < numNodes; i++) {
         for(int j=0; j < 3; j++){
           if(fabs(CoordCheck[i][j] - Coord[i*3+j]) > 1.0e-6){
             coordCorrect = false;
             std::cout << "Incorrect coordinate value for node=" << i
                       << " index " << j << " Expected " << CoordCheck[i][j]
                       << " Got " << Coord[i*3+j] << std::endl;
           }
         }
       }
       result.UpdateResult("CoordinateData:Correct", coordCorrect);
       // Check connectivity values
       bool connCorrect = true;
       // get connectivity tables for panes
       int numConn;
       std::string stringNames;
       COM_get_connectivities("OFModule", pane, &numConn, stringNames);
       std::istringstream ConnISS(stringNames);
       std::vector<std::string> connNames;
       for (int i=0; i<numConn; ++i) {
         std::string name;
         ConnISS >> name;
         connNames.push_back(name);
         std::cout << "Connectivity Table # " << i+1 << ": " << name << std::endl;
       }
       // number of nodes per element
       char getDataItemLoc;
       COM_Type getDataItemType;
       int numElementNodes;
       std::string getDataItemUnits;
       std::string fullConnName("OFModule."+connNames[0]);
       COM_get_dataitem(fullConnName, &getDataItemLoc, &getDataItemType,
                        &numElementNodes, &getDataItemUnits);
       std::cout << "getDataItemLoc " << getDataItemLoc << std::endl;
       std::cout << "getDataItemType " << getDataItemType << std::endl;
       std::cout << "numElementNodes " << numElementNodes << std::endl;
       std::cout << "getDataItemUnits " << getDataItemUnits << std::endl;
       int* Conn;
       COM_get_array(fullConnName.c_str(), pane, &Conn);
       if (Conn == NULL) {
         std::cout << "In Test__ModuleMeshRegistration:  No mesh connectivity registered."
                   << std::endl;
         return;
       } else {
         result.UpdateResult("ConnectivityData:Registered", true);
       }
       // assumes a single connectivity for this pane
       int numElem = 0;
       int numElemExpected = 168;
       COM_get_size(fullConnName, pane, &numElem);
       if (numElem != numElemExpected) {
         std::cout << "Wrong number of elements registered for this mesh." << std::endl;
         std::cout << "Got " << numElem << " Expected: " << numElemExpected << std::endl;
       } else {
         connCorrect = true;
       }
       int ConnCheck[168][4] =
         { {1, 2, 3, 4},
         {3, 5, 6, 4},
         {5, 7, 8, 6},
         {7, 9, 10, 8},
         {9, 11, 12, 10},
         {11, 13, 14, 12},
         {13, 15, 16, 14},
         {15, 17, 18, 16},
         {17, 19, 20, 18},
         {19, 21, 22, 20},
         {21, 23, 24, 22},
         {23, 25, 26, 24},
         {25, 27, 28, 26},
         {27, 29, 30, 28},
         {29, 31, 32, 30},
         {31, 33, 34, 32},
         {33, 35, 36, 34},
         {35, 37, 38, 36},
         {37, 39, 40, 38},
         {39, 41, 42, 40},
         {41, 43, 44, 42},
         {43, 45, 46, 44},
         {47, 48, 49, 50},
         {51, 47, 50, 52},
         {53, 51, 52, 54},
         {55, 53, 54, 56},
         {57, 55, 56, 58},
         {59, 57, 58, 60},
         {61, 59, 60, 62},
         {63, 61, 62, 64},
         {65, 63, 64, 66},
         {67, 65, 66, 68},
         {69, 67, 68, 70},
         {71, 69, 70, 72},
         {73, 71, 72, 74},
         {75, 73, 74, 76},
         {77, 75, 76, 78},
         {79, 77, 78, 80},
         {81, 79, 80, 82},
         {83, 81, 82, 84},
         {85, 83, 84, 86},
         {87, 85, 86, 88},
         {89, 87, 88, 90},
         {91, 92, 89, 90},
         {93, 94, 95, 96},
         {96, 95, 97, 98},
         {98, 97, 99, 100},
         {100, 99, 101, 102},
         {101, 103, 104, 102},
         {103, 105, 106, 104},
         {105, 107, 108, 106},
         {107, 109, 110, 108},
         {109, 111, 112, 110},
         {111, 113, 114, 112},
         {113, 115, 116, 114},
         {115, 117, 118, 116},
         {117, 119, 120, 118},
         {119, 121, 122, 120},
         {121, 123, 124, 122},
         {123, 125, 126, 124},
         {125, 127, 128, 126},
         {127, 129, 130, 128},
         {129, 131, 132, 130},
         {131, 133, 134, 132},
         {133, 135, 136, 134},
         {135, 137, 138, 136},
         {137, 139, 140, 138},
         {139, 141, 142, 140},
         {141, 143, 144, 142},
         {143, 145, 146, 144},
         {145, 147, 148, 146},
         {147, 149, 150, 148},
         {149, 151, 152, 150},
         {151, 153, 154, 152},
         {153, 155, 156, 154},
         {155, 157, 158, 156},
         {157, 159, 160, 158},
         {159, 161, 162, 160},
         {161, 163, 164, 162},
         {163, 165, 166, 164},
         {165, 167, 168, 166},
         {167, 169, 170, 168},
         {169, 171, 172, 170},
         {171, 173, 174, 172},
         {173, 175, 176, 174},
         {175, 177, 178, 176},
         {177, 179, 180, 178},
         {179, 181, 182, 180},
         {181, 183, 184, 182},
         {183, 185, 186, 184},
         {185, 187, 188, 186},
         {187, 189, 190, 188},
         {189, 191, 192, 190},
         {191, 193, 194, 192},
         {193, 195, 196, 194},
         {195, 197, 198, 196},
         {197, 199, 200, 198},
         {199, 201, 202, 200},
         {201, 203, 204, 202},
         {203, 205, 206, 204},
         {205, 207, 208, 206},
         {207, 209, 210, 208},
         {209, 211, 212, 210},
         {211, 213, 214, 212},
         {213, 215, 216, 214},
         {215, 217, 218, 216},
         {217, 219, 220, 218},
         {219, 2, 1, 220},
         {48, 221, 222, 49},
         {221, 223, 224, 222},
         {223, 225, 226, 224},
         {225, 227, 228, 226},
         {227, 229, 230, 228},
         {229, 231, 232, 230},
         {231, 233, 234, 232},
         {233, 235, 236, 234},
         {235, 237, 238, 236},
         {237, 239, 240, 238},
         {239, 241, 242, 240},
         {241, 243, 244, 242},
         {243, 245, 246, 244},
         {245, 247, 248, 246},
         {247, 249, 250, 248},
         {249, 251, 252, 250},
         {251, 253, 254, 252},
         {253, 255, 256, 254},
         {255, 257, 258, 256},
         {257, 259, 260, 258},
         {259, 261, 262, 260},
         {261, 263, 264, 262},
         {263, 265, 266, 264},
         {265, 267, 268, 266},
         {267, 269, 270, 268},
         {269, 271, 272, 270},
         {271, 273, 274, 272},
         {273, 275, 276, 274},
         {275, 277, 278, 276},
         {277, 279, 280, 278},
         {279, 281, 282, 280},
         {281, 283, 284, 282},
         {283, 285, 286, 284},
         {285, 287, 288, 286},
         {287, 289, 290, 288},
         {289, 291, 292, 290},
         {291, 293, 294, 292},
         {293, 295, 296, 294},
         {295, 297, 298, 296},
         {297, 299, 300, 298},
         {299, 301, 302, 300},
         {301, 303, 304, 302},
         {303, 305, 306, 304},
         {305, 307, 308, 306},
         {307, 309, 310, 308},
         {309, 311, 312, 310},
         {311, 313, 314, 312},
         {313, 315, 316, 314},
         {315, 317, 318, 316},
         {317, 319, 320, 318},
         {319, 321, 322, 320},
         {321, 323, 324, 322},
         {323, 325, 326, 324},
         {325, 327, 328, 326},
         {327, 329, 330, 328},
         {329, 331, 332, 330},
         {331, 333, 334, 332},
         {333, 335, 336, 334},
         {335, 337, 338, 336},
         {337, 94, 93, 338} };
       for(int i=0; i < numElem; i++){
         for(int j=0; j < numElementNodes; j++){
           if(fabs(ConnCheck[i][j] - Conn[i*numElementNodes+j]) > 1.0e-6){
             connCorrect = false;
             std::cout << "Incorrect connectivity value at element " << i
                       << " index " << j << " Expected " << ConnCheck[i][j]
                       << " Got " << Conn[i*numElementNodes+j] << std::endl;
           }
         }
       }
       result.UpdateResult("ConnectivityData:Correct", connCorrect);
       // cleanup
       IntDir = IRAD::Sys::ChDir(OrgDir);
       COM_free_buffer(&paneList);
       COM_UNLOAD_MODULE_STATIC_DYNAMIC(OpenFoamFSI, "OFModule");
       return;
     }