ElmerFoamFSI: Connectivity::index_offset
Size index_offset () const inline
Get the index of the first element.
Definition at line 166 of file Connectivity.hpp.
References _offset, and root().
Referenced by Element_node_enumerator::id(), and Element_node_enumerator_uns::next().
 { return root()->_offset; }