ElmerFoamFSI: Simple_manifold_2::get_opposite_edge
Edge_ID get_opposite_edge (const Edge_ID & eID) const inline
Get the ID of the opposite edge of a given interior or border edge.
If its opposite is a border edge, it returns a border edge ID.
Definition at line 241 of file Simple_manifold_2.h.
References get_opposite_edge_border(), get_opposite_edge_interior(), and Facet_ID::is_border().
{
     if ( eID.is_border())
       return get_opposite_edge_border(eID);
     else
       return get_opposite_edge_interior(eID);
   }