ElmerFoamFSI: SolverUtils::GeoPrim::C3Plane::C3Plane
C3Plane (const C3Point & p1, const C3Point & p2, const C3Point & p3) inline
Definition at line 2076 of file GeoPrimitives.H.
References C3Plane::A(), C3Plane::B(), C3Plane::C(), C3Plane::n, C3Vector::Normalize(), C3Point::x(), C3Vector::x(), C3Point::y(), and C3Point::z().
       : p(p1)
     {
       double A = p1.y()*(p2.z() - p3.z()) + p2.y()*(p3.z() - p1.z()) +
         p3.y()*(p1.z() - p2.z());
       double B = p1.z()*(p2.x() - p3.x()) + p2.z()*(p3.x() - p1.x()) +
         p3.z()*(p1.x() - p2.x());
       double C = p1.x()*(p2.y() - p3.y()) + p2.x()*(p3.y() - p1.y()) +
         p3.x()*(p1.y() - p2.y());
       //      double D = -1.0 * ( p1.x()*(p2.y()*p3.z() - p3.y()*p2.z()) +
       //                          p2.x()*(p3.y()*p1.z() - p1.y()*p3.z()) +
       //                          p3.x()*(p1.y()*p2.z() - p2.y()*p1.z()) );
       n.x(A).y(B).z(C);
       n.Normalize();
     };