ElmerFoamFSI: ElmerFoamFSI::TestingObject::Test__SolidAgentRun
virtual void Test__SolidAgentRun (ResultsType & result) inline virtual
Test for solidAgent->Run() function.
Definition at line 1404 of file ElmerFoamFSITest.H.
References TestingObject< ResultsType >::__helper(), TestingObject< ResultsType >::componentInterfaceNames, TestingObject< ResultsType >::DisplacementCheck(), TestingObject< ResultsType >::fsiCoupler, fsicoupling::getFluidAgent(), fsicoupling::getFluidIntName(), fsicoupling::getRunMode(), fsicoupling::getSimulationFinalTime(), fsicoupling::getSimulationTime(), fsicoupling::getSolidIntName(), fsicoupling::getStructureAgent(), TestingObject< ResultsType >::global, fsicoupling::Initialize(), agentbase::InitializeTimeStep(), openfoamagent::Run(), elmeragent::Run(), fsicoupling::SetRunMode(), fsicoupling::SetVerbLevel(), fsicoupling::TransferDisplacementsToFluid(), fsicoupling::TransferLoadsToStructures(), and TestingObject< ResultsType >::verblevel.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       double time_final = 0.05;
       double timestep = 2.0e-3;
       int verblevel = 3;
       bool works = true;
       int IntDir;
       // Copying the SimpleStatic data using getinputdata() helper function.
       bool work =__helper();
       std::string fluidDir;
       std::string simStaticDir;
       fluidDir = IRAD::Sys::CWD() + "/SimpleStatic/fluid";
       simStaticDir = IRAD::Sys::CWD() + "/SimpleStatic";
       if(!(IRAD::Sys::FILEEXISTS(fluidDir)||(IRAD::Sys::FILEEXISTS(simStaticDir)))){
         std::cout << "SimpleStatic / fluid Folders do not exists!" << std::endl;
         works = false;
         result.UpdateResult("fsiCoupler:Works",works);
         return;
       }
       else{
         IntDir = IRAD::Sys::ChDir(simStaticDir);
         if(IntDir == -1){
           std::cout << "GetInputData Error: Could not change directory to "
                     << fluidDir << ". Exiting (fail). " << std::endl;
           works = false;
           result.UpdateResult("fsiCoupler:Works",works);
         }
         std::system("chmod 755 Allclean Allrun AllrunPar makeLinks makeSerialLinks removeSerialLinks");
         std::system("./Allclean");
         std::system("./Allrun");
         IntDir = IRAD::Sys::ChDir(fluidDir);
         if(IntDir == -1){
           std::cout << "GetInputData Error: Could not change directory to "
                     << fluidDir << ". Exiting (fail). " << std::endl;
           works = false;
           result.UpdateResult("fsiCoupler:Works",works);
         }
       }
       fsicoupling fsiCoupler(global);
       std::string fluidSolverName("OpenFoamFSI");
       std::string solidSolverName("ElmerCSC");
       std::string transferServiceName("SurfX");
       std::string runMode("1");
       COM_load_module(fluidSolverName.c_str(),"FluidsComponentInterface");
       COM_load_module(solidSolverName.c_str(),"StructuresComponentInterface");
       COM_load_module("SurfUtil","SurfUtil");
       COM_load_module("Simpal","Simpal");
       std::vector<std::string> componentInterfaceNames;
       componentInterfaceNames.push_back("FluidsComponentInterface");
       componentInterfaceNames.push_back("StructuresComponentInterface");
       componentInterfaceNames.push_back("TransferInterface");
       componentInterfaceNames.push_back("SurfUtil");
       componentInterfaceNames.push_back("Simpal");
       fsiCoupler.SetRunMode(runMode);
       fsiCoupler.SetVerbLevel(verblevel);
       fsiCoupler.Initialize(componentInterfaceNames, time_final, timestep);
       // Mimicing FsiCoupler::run, intializing variables, etc.
       int innerCount = 0;
       int maxSubSteps = 1000;
       int dumpinterval = 1;
       int systemStep = 0;
           if(!(fsiCoupler.getRunMode())){
                 fsiCoupler.TransferDisplacementsToFluid(fsiCoupler.getStructureAgent(),fsiCoupler.getFluidAgent());
           }
       double simultime = fsiCoupler.getSimulationTime();
       std::cout << "simultime is =" << simultime << std::endl;
       if(fsiCoupler.getRunMode() < 2){
         fsiCoupler.getFluidAgent()->InitializeTimeStep(simultime);
         fsiCoupler.getFluidAgent()->Run(fsiCoupler.getSimulationTime()+fsiCoupler.getSimulationFinalTime());
       }
       // setting a traction value so that you have bigger numbers for solid displacement later
       double * tractions;
       int stride = 0;
       int cap = 0;
       // Get the traction vector values for fluid domain.
           COM_get_array((fsiCoupler.getFluidIntName()+".traction").c_str(),101,&tractions,&stride,&cap);
       std::cout << "stride and cap = " << stride << "," << cap << std::endl;
       //traction becomes Ycoord * 3 + 2
       int isize = cap * stride ;
       for(int i = 0; i < isize/3 ; i++){
         //tractions[3*i+1] = 3*fsiCoupler.getFluidAgent()->Coordinates()[3*i+2]+2;
         //tractions[3*i+1] = fsiCoupler.getFluidAgent()->Coordinates()[3*i+2];
         //tractions[3*i+1] = 1;
         tractions[3*i+1] = 50000;
                 std::cout << "tractions[" << i << "] = " << tractions[3*i] << ",  " << tractions[3*i+1] << ",  " << tractions[3*i+2] << std::endl;
       }
       if(!fsiCoupler.getRunMode()) fsiCoupler.TransferLoadsToStructures(fsiCoupler.getFluidAgent(), fsiCoupler.getStructureAgent());
       // Solid Agent Run executing
       if( fsiCoupler.getRunMode() !=1){
         fsiCoupler.getStructureAgent()->InitializeTimeStep(simultime);
         fsiCoupler.getStructureAgent()->Run(fsiCoupler.getSimulationTime()+fsiCoupler.getSimulationFinalTime());
       }
           double *solidDisp = NULL;
       // Get the displacement vector values for solid.
           std::string solidsCoordinateName(fsiCoupler.getSolidIntName()+".Displacements");
           COM_get_array(solidsCoordinateName.c_str(),(fsiCoupler.getStructureAgent())->PaneID(),&solidDisp);
       works = DisplacementCheck(solidDisp, 300);
       result.UpdateResult("SolidAgentRun:Works",works);
     }