ElmerFoamFSI: ElmerModuleDriver::TestingObject::Test__TrapezoidQuadrature
virtual void Test__TrapezoidQuadrature (ResultsType & result) inline virtual
Test for ElmerModuleDriver::TrapezoidQuadrature.
Parameters
result ElmerModuleDriver::TestResults object to store test results.
This function implements a simple test of the function ElmerModuleDriver::TrapezoidQuadrature - which is designed to integrate a function, f, over an n-way partitioned interval .
The test first makes sure that the method integrates a linear function exactly, and then that the error term has the proper dependence on the spacings.
Definition at line 179 of file ElmerModuleDriverTest.H.
References ElmerModuleDriver::TestFixture::F1(), ElmerModuleDriver::TestFixture::F2(), TestingObject< ResultsType >::N, and ElmerModuleDriver::TrapezoidQuadrature().
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       std::ostringstream Ostr;
       std::vector<double> E;
       size_t n = 2*N.size();
       bool runs = true;
       for(std::vector<int>::iterator i = N.begin();i != N.end();i++){
         double Ii = 0.0;
         try {
           Ii = ElmerModuleDriver::TrapezoidQuadrature(TestFixture::F1,0,1,*i);
         } catch (...) {
           runs = false;
         }
         E.push_back(std::fabs(Ii-1.0));
       }
       bool order2 = (E[0] < 1e-14);
       for(std::vector<int>::iterator i = N.begin();i != N.end();i++){
         double Ii = 0.0;
         try {
           Ii = ElmerModuleDriver::TrapezoidQuadrature(TestFixture::F2,0,1,*i);
         } catch (...) {
           runs = false;
         }
         E.push_back(std::fabs(Ii-1.0));
       }
       result.UpdateResult("TrapezoidQuadrature:Runs",runs);
       result.UpdateResult("TrapezoidQuadrature:Accurate",E[n-1] < 1e-12);
       for(int i = N.size();i < n - 1;i++){
         double e = E[i+1]/E[i];
         double n1 = static_cast<double>(N[i-N.size()])/static_cast<double>(N[(i-N.size())+1]);
         double p = std::log(e)/std::log(n1);
         p -= 2;
         p = std::abs(p);
         if(p > 2e-2){
           order2 = false;
         }
       }
       result.UpdateResult("TrapezoidQuadrature:Order2",order2);
     }