ElmerFoamFSI: SolverUtils::TransferObject::Overlay
int Overlay (const std::string & w1, const std::string & w2) inline
Definition at line 298 of file InterfaceLayer.H.
References SolverUtils::COM_call_function(), COM_get_dataitem_handle(), TransferObject::overlayhandle, TransferObject::win1, and TransferObject::win2.
Referenced by fsicoupling::Initialize(), and fsicoupling::TransferPressuresToStructures().
     {
       win1 = w1;
       win2 = w2;
       int mesh1 = COM_get_dataitem_handle((w1+".mesh"));
       int mesh2 = COM_get_dataitem_handle((w2+".mesh"));
       if(mesh1 <= 0 || mesh2 <= 0)
         return(-1);
       COM_call_function(overlayhandle,&mesh1,&mesh2);
       return(0);
     };