ElmerFoamFSI: fsicoupling::SetRunMode
void SetRunMode (const std::string & inMode) inline
Definition at line 376 of file FsiCoupling.H.
References runMode.
Referenced by SerialDriverProgram::DriverRun(), TestingObject< ResultsType >::Test__FluidAgentRun(), TestingObject< ResultsType >::Test__fsiCouplerAgentsInitialize(), TestingObject< ResultsType >::Test__SolidAgentRun(), TestingObject< ResultsType >::Test__TransferDisplacementsToFluid(), and TestingObject< ResultsType >::Test__TransferLoadsToStructures().
   {
     std::stringstream outString;
     if(inMode == "Fluid" ||
        inMode == "fluid"){
       runMode = 1;
     } else if(inMode == "Structure" ||
               inMode == "structure" ||
               inMode == "Solid"     ||
               inMode == "solid"){
       runMode = 2;
     } else {
       runMode = 0;
     }
   };