ElmerFoamFSI: OpenFoamModuleDriver::TestingObject::GetInputData
virtual int GetInputData (std::string sourceDir, std::string destDir) inline virtual
Function to copy input data from source testing directory for use in unit tests.
Parameters
sourceDir std::string directory containing the input data
destDir std::string destination directory for the data
Definition at line 145 of file OpenFoamModuleDriverTest.H.
References IRAD::Sys::ChDir(), IRAD::Sys::CreateDirectory(), IRAD::Sys::CWD(), IRAD::Sys::FILEEXISTS(), IRAD::Sys::ISDIR(), IRAD::Sys::ISLINK(), and IRAD::Sys::SymLink().
Referenced by TestingObject< ResultsType >::Test__LoadUnitTestData(), TestingObject< ResultsType >::Test__ModuleFunctionInitialize(), TestingObject< ResultsType >::Test__ModuleFunctionStepFluid(), TestingObject< ResultsType >::Test__ModuleMeshRegistration(), and TestingObject< ResultsType >::Test__ModuleSurfaceData().
{
       //std::string DirName;
       std::string OrgDir;
       //Save original working directory for later
       OrgDir = IRAD::Sys::CWD();
       //Check if data directory exists
       if(!IRAD::Sys::FILEEXISTS(sourceDir)){
         std::cout << "GetInputData Error: Could not find data directory, "
                   << sourceDir << ". Exiting (fail)." << std::endl;
         return -1;
       }
       std::ifstream Inf;
       std::ofstream Ouf;
       std::string InFileName;
       std::string OutFileName;
       int IntDir;
       //Create destDir directory in current directory (if it doesn't
       //already exist) to run our tests in.
       if(!IRAD::Sys::FILEEXISTS(destDir)){
         IntDir = IRAD::Sys::CreateDirectory(destDir);
         if(IntDir == -1){
           std::cout << "GetInputData Error: Could not make directory, "
                     << destDir << ". Exiting (fail)." << std::endl;
           return -1;
         }
       }
       //Open the input test data directory
       IRAD::Sys::Directory SourceDir(sourceDir);
       //Change directories to destDir directory for running
       IntDir = IRAD::Sys::ChDir(destDir);
       if(IntDir == -1){
         std::cout << "GetInputData Error: Could not change directories to "
                   << destDir << ". Exiting (fail)." << std::endl;
         return -1;
       }
       //Copy input data to destDir directory for running
       for(std::vector<std::string>::iterator it = SourceDir.begin();
           it != SourceDir.end(); ++it){
         InFileName = sourceDir + "/" + *it;
         OutFileName = IRAD::Sys::CWD() + "/" + *it;
         if(IRAD::Sys::ISLINK(InFileName))
           // preserve links, don't traverse
           int IntDir = IRAD::Sys::SymLink(InFileName, OutFileName);
         else if(IRAD::Sys::ISDIR(InFileName)) {
           // recursively copy directories
           int IntDir = GetInputData(InFileName, OutFileName);
         } else {
           // copy files, travserse into directories recursively
           Inf.open(InFileName.c_str());
           Ouf.open(OutFileName.c_str());
           Ouf << Inf.rdbuf();
           Ouf.close();
           Inf.close();
         }
       }
       //Change directories to back to original directory
       IntDir = IRAD::Sys::ChDir(OrgDir);
       if(IntDir == -1){
         std::cout << "GetInputData Error: Could not change directories to "
                   << OrgDir << ". Exiting (fail)." << std::endl;
         return -1;
       }
       return 0;
     }