ElmerFoamFSI: Simple_manifold_2::get_origin
int get_origin (Edge_ID eID, Element_node_enumerator * ene_in = NULL) const inline
Get the ID of the origin of a given edge.
If the edge is between real and ghost, then consider the border edge as part of real.
Definition at line 335 of file Simple_manifold_2.h.
Referenced by get_a_border_node(), get_a_ghost_border_node(), get_a_real_border_node(), get_incident_edge(), and get_incident_real_edge().
{
     if ( eID.is_border()) {
       Edge_ID opp;
       if (is_real_border_edge( eID)) opp = get_opposite_real_edge_border( eID);
       else opp = get_opposite_ghost_edge_border( eID);
       Element_node_enumerator ene( _pane, opp.eid());
       return ene[opp.lid()+1==ene.size_of_edges()?0:opp.lid()+1];
     }
     else {
       if ( ene_in)
         return (*ene_in)[eID.lid()];
       else
         return Element_node_enumerator( _pane, eID.eid())[eID.lid()];
     }
   }