ElmerFoamFSI: Facet_ID::is_border
bool is_border () const inline
Determines whether the facet is on border.
Definition at line 40 of file Simple_manifold_2.h.
References BndID, and lid().
Referenced by Simple_manifold_2::get_border_edgeID(), Simple_manifold_2::get_destination(), Simple_manifold_2::get_incident_edge(), Simple_manifold_2::get_incident_ghost_edge(), Simple_manifold_2::get_incident_real_edge(), Simple_manifold_2::get_next_edge(), Simple_manifold_2::get_next_ghost_edge(), Simple_manifold_2::get_next_real_edge(), Simple_manifold_2::get_opposite_edge(), Simple_manifold_2::get_opposite_edge_border(), Simple_manifold_2::get_opposite_ghost_edge(), Simple_manifold_2::get_opposite_ghost_edge_border(), Simple_manifold_2::get_opposite_ghost_edge_interior(), Simple_manifold_2::get_opposite_real_edge_border(), Simple_manifold_2::get_opposite_real_edge_interior(), Simple_manifold_2::get_prev_ghost_edge(), Simple_manifold_2::get_prev_real_edge(), Simple_manifold_2::is_ghost_border_edge(), Simple_manifold_2::is_ghost_border_node(), Simple_manifold_2::is_isolated_node(), Simple_manifold_2::is_pure_real_border_edge(), Simple_manifold_2::is_real_border_edge(), and Simple_manifold_2::is_real_border_node().
 { return lid()==BndID; }