ElmerFoamFSI: Simple_manifold_2::get_prev_real_edge
Edge_ID get_prev_real_edge (const Edge_ID & eID) const inline
Get the ID of the previous real edge of the element or along the boundary.
Definition at line 266 of file Simple_manifold_2.h.
References get_next_real_edge_interior(), get_opposite_real_edge(), get_opposite_real_edge_interior(), get_prev_real_edge_interior(), and Facet_ID::is_border().
{
     if ( !eID.is_border())
       return get_prev_real_edge_interior( eID);
     else {
       Edge_ID oeID = get_opposite_real_edge( eID);
       while ( !oeID.is_border())
         oeID = get_opposite_real_edge_interior
           ( get_next_real_edge_interior( oeID));
       return oeID;
     }
   }