ElmerFoamFSI: OpenFoamModuleDriver::TestingObject::RunTest
virtual void RunTest (const std::string & name, ResultsType & result) inline virtual
Runs a test specified by name.
Parameters
name String name of the test to run.
result OpenFoamModuleDriver::TestResults object to store test results.
Reimplemented from TestingObject< ResultsType >.
Definition at line 1373 of file OpenFoamModuleDriverTest.H.
References TestingObject< ResultsType >::Epilogue(), TestingObject< ResultsType >::Prologue(), TestingObject< ResultsType >::Test__LoadUnitTestData(), TestingObject< ResultsType >::Test__ModuleFunctionInitialize(), TestingObject< ResultsType >::Test__ModuleFunctionStepFluid(), TestingObject< ResultsType >::Test__ModuleLoadUnload(), TestingObject< ResultsType >::Test__ModuleMeshRegistration(), and TestingObject< ResultsType >::Test__ModuleSurfaceData().
Referenced by TestingObject< ResultsType >::ProcessTests(), and OpenFoamModuleDriver::Test().
     {
       Prologue();
       if(name == "ModuleLoadUnload")
         Test__ModuleLoadUnload(result);
       else if(name == "LoadUnitTestData")
         Test__LoadUnitTestData(result);
       else if(name == "ModuleFunctionInitialize")
         Test__ModuleFunctionInitialize(result);
       else if(name == "ModuleMeshRegistration")
         Test__ModuleMeshRegistration(result);
       else if(name == "ModuleSurfaceData")
         Test__ModuleSurfaceData(result);
       else if(name == "ModuleFunctionStepFluid")
         Test__ModuleFunctionStepFluid(result);
       Epilogue();
     }