ElmerFoamFSI: Simple_manifold_2::get_incident_ghost_edge
Edge_ID get_incident_ghost_edge (int vID) const inline
Get the ID of an incident real edge within the pane of a given node The incident edge may encode an isolated node.
Definition at line 417 of file Simple_manifold_2.h.
References _ieIDs_ghost, _ieIDs_real_or_str, _is_str, _maxsize_real_nodes, _size_real_borders, COM_assertion_msg, Facet_ID::eid(), get_next_real_edge_interior(), get_opposite_real_edge_border(), get_opposite_real_edge_interior(), Facet_ID::is_border(), is_ghost_border_edge(), and is_ghost_node().
{
     bool isghost = is_ghost_node( vID);
     Edge_ID eID;
     if ( _is_str || !isghost)
       eID = _ieIDs_real_or_str[ vID-1];
     else
       eID = _ieIDs_ghost[ vID-_maxsize_real_nodes-1];
     if ( isghost) return eID;
     if ( eID.is_border() && eID.eid()<=_size_real_borders) {
       // If vID is between real and ghost, and on the real boundary,
       // get the border edge between real and ghost.
       eID = get_opposite_real_edge_border( eID);
       Edge_ID eID0 = eID;
       while ( (eID = get_opposite_real_edge_interior
                ( get_next_real_edge_interior(eID))) != eID0 &&
               !is_ghost_border_edge( eID));
       COM_assertion_msg( eID.is_border(),
                          "No ghost edge incident on given vertex");
     }
     return eID;
   }