ElmerFoamFSI: ElmerModuleDriver::TestingObject::Process
virtual void Process (ResultsType & results) inline virtual
Process all tests and populate a "results" object.
Reimplemented from TestingObject< ResultsType >.
Definition at line 1104 of file ElmerModuleDriverTest.H.
References TestingObject< ResultsType >::Epilogue(), TestingObject< ResultsType >::Prologue(), TestingObject< ResultsType >::Test__ElmerUnitTests(), TestingObject< ResultsType >::Test__ExampleFunction(), TestingObject< ResultsType >::Test__MidPointQuadrature(), and TestingObject< ResultsType >::Test__TrapezoidQuadrature().
Referenced by ElmerModuleDriver::Test().
{
       Prologue();
       Test__ExampleFunction(result);
       Test__TrapezoidQuadrature(result);
       Test__MidPointQuadrature(result);
       Test__ElmerUnitTests(result);
       Epilogue();
     }