ElmerFoamFSI: Element_node_vectors_k_const::operator()
const Value& operator() (int i, int j) const inline
Definition at line 247 of file Element_accessors.hpp.
References Element_node_vectors_k_const< Value >::_attr, Element_node_vectors_k_const< Value >::_offsets, Element_node_vectors_k_const< Value >::_vs, COM_assertion, and DataItem::size_of_components().
Referenced by Element_node_vectors_k< Value >::operator()(), Element_node_vectors_k_const< Value >::operator[](), and Element_node_vectors_k< Value >::operator[]().
{
     if ( _attr) {
       COM_assertion( _attr->size_of_components()>1);
       const DataItem *aj = _attr+j+1;
       return reinterpret_cast<const Value*>
         (aj->pointer())[_offsets[i]*aj->stride()];
     }
     else
       return _vs[i][j];
   }