ElmerFoamFSI: OpenFoamModuleDriver::TestingObject::Test__ModuleFunctionStepFluid
virtual void Test__ModuleFunctionStepFluid (ResultsType & result) inline virtual
Definition at line 543 of file OpenFoamModuleDriverTest.H.
References IRAD::Sys::ChDir(), COM_call_function(), COM_get_array(), COM_get_function_handle(), COM_get_panes(), COM_get_status(), COM_LOAD_MODULE_STATIC_DYNAMIC, COM_UNLOAD_MODULE_STATIC_DYNAMIC, IRAD::Sys::CWD(), TestingObject< ResultsType >::GetInputData(), and TestingObject< ResultsType >::SourceDirPath.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       std::cout << "Running Test__ModuleFunctionStepFluid" << std::endl;
       //load OpenFoam module
       COM_LOAD_MODULE_STATIC_DYNAMIC(OpenFoamFSI, "OFModule");
       bool works = false;
       //Call GetInputData to copy input test data to temp directory for running tests.
       std::string suffix = "/share/Testing/test_data/HronTurekFsi";
       std::string dirName = SourceDirPath + suffix;
       std::string testDir = IRAD::Sys::CWD() + "/UnitTestDataStepTest";
       int IntDir = GetInputData(dirName, testDir);
       std::string fluidDir = testDir + "/fluid";
       std::string OrgDir = IRAD::Sys::CWD();
       IntDir = IRAD::Sys::ChDir(fluidDir);
       // call init to setup the mesh
       int dummy1=1;
       char *dummy2[2];
       dummy2[0] = const_cast<char *>(std::string("StepFluid").c_str());
       dummy2[1] = NULL;
       int verb=3;
       int initHandle = COM_get_function_handle("OFModule.InitFoam");
       COM_call_function(initHandle, &dummy1, &dummy2, &verb);
       // list of panes in this window
       int numPanes;
       int* paneList;
       COM_get_panes("OFModule", &numPanes, &paneList);
       // only one pane for serial runs
       int pane = paneList[0];
       // check that the current simulation time and endTime are registered
       int status = COM_get_status("OFModule.time", pane);
       bool timeStatus = false;
       if(status <= 0) {
         std::cout << "ModuleFunctionStepFluid Error: time not a valid DataItem."
                   << "status = " << status << std::endl;
         result.UpdateResult("TimeData:Registered", false);
         return;
       } else {
         timeStatus = true;
       }
       status = COM_get_status("OFModule.endTime", pane);
       if(status <= 0) {
         std::cout << "ModuleFunctionStepFluid Error: endTime not a valid DataItem."
                   << "status = " << status << std::endl;
         result.UpdateResult("TimeData:Registered", false);
         return;
       } else {
         timeStatus = timeStatus && true;
       }
       result.UpdateResult("TimeData:Registered", timeStatus);
       double* time=NULL;
       COM_get_array("OFModule.time", pane, &time);
       double* endTime=NULL;
       COM_get_array("OFModule.endTime", pane, &endTime);
       works=false;
       double testTime = 0.;
       double testEndTime = 5.e-3;
       double toler = 1.e-9;
       if(*time - testTime < toler && *endTime - testEndTime < toler)
         works=true;
       else {
         std::cout << "ModuleFunctionStepFluid Error: time or endTime initialized incorrectly"
                   << std::endl;
         std::cout << " time = " << *time << " expected " << testTime << std::endl;
         std::cout << " endTime = " << *endTime << " expected " << testEndTime << std::endl;
       }
       result.UpdateResult("TimeData:Correct",works);
       // Test StepFluid function exists
       works = false;
       int stepHandle = COM_get_function_handle("OFModule.StepFluid");
       if(stepHandle > 0)
         works=true;
       else {
         std::cout << "ModuleFunctionStepFluid Error: Could not get function handle."
                   << std::endl;
         result.UpdateResult("StepFluidFunction:Exists",false);
         return;
       }
       result.UpdateResult("StepFluidFunction:Exists",works);
       // Test StepFluid function steps
       // check that the time got incremented as expected
       COM_call_function(stepHandle);
       works=false;
       testTime = 1.e-3;
       toler = 1.e-9;
       if(*time - testTime < toler )
         works=true;
       else {
         std::cout << "ModuleFunctionStepFluid Error: time did not increment"
                   << std::endl;
         std::cout << " time = " << *time << "expected " << testTime << std::endl;
       }
       result.UpdateResult("StepFluidFunction:Steps",works);
       // cleanup
       IntDir = IRAD::Sys::ChDir(OrgDir);
       //Unload OpenFoam module
       COM_UNLOAD_MODULE_STATIC_DYNAMIC(OpenFoamFSI, "OFModule");
       return;
     }