ElmerFoamFSI: OpenFoamModuleDriver::TestingObject::Test__ModuleFunctionInitialize
virtual void Test__ModuleFunctionInitialize (ResultsType & result) inline virtual
Definition at line 324 of file OpenFoamModuleDriverTest.H.
References TestingObject< ResultsType >::GetInputData(), and TestingObject< ResultsType >::SourceDirPath.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       std::cout << "Running Test__ModuleFunctionInitialize" << std::endl;
       //load OpenFoam module
       COM_LOAD_MODULE_STATIC_DYNAMIC(OpenFoamFSI, "OFModule");
       bool works = false;
       // Test Initalize function exists
       int initHandle = COM_get_function_handle("OFModule.InitFoam");
       if(initHandle > 0)
         works=true;
       else {
         std::cout << "ModuleFunctionInitialize Error: Could not get function handle."
                   << std::endl;
       }
       result.UpdateResult("InitFunction:Exists",works);
       if (!works)
         return;
       //Call GetInputData to copy input test data to temp directory for running tests.
       std::string suffix = "/share/Testing/test_data/HronTurekFsi";
       std::string dirName = SourceDirPath + suffix;
       std::string testDir = IRAD::Sys::CWD() + "/UnitTestDataHTFsi";
       int IntDir = GetInputData(dirName, testDir);
       std::string fluidDir = testDir + "/fluid";
       std::string OrgDir = IRAD::Sys::CWD();
       IntDir = IRAD::Sys::ChDir(fluidDir);
       // Test proper operation of init
       // For now, just test that the function returned 0 after running
       // We test the "correctness" of the registered data in subsequent tests
       int dummy1=1;
       char *dummy2[2];
       dummy2[0] = const_cast<char *>(std::string("functionInit").c_str());
       dummy2[1] = NULL;
       COM_call_function(initHandle, &dummy1, &dummy2);
       // check the status variable to determine success of initialize
       int* initStatus=NULL;
       int status = COM_get_status("OFModule.initStatus",101);
       if(status <= 0) {
         std::cout << "ModuleFunctionInitialize Error: initStatus not a valid DataItem."
                   << "status = " << status << std::endl;
         return;
       }
       COM_get_array("OFModule.initStatus", 101, &initStatus);
       works=false;
       if(*initStatus == 0)
         works=true;
       else {
         std::cout << "ModuleFunctionInitialize Error: initStatus not set to zero by InitFoam."
                   << std::endl;
       }
       result.UpdateResult("InitFunction:Runs",works);
       // cleanup
       IntDir = IRAD::Sys::ChDir(OrgDir);
       COM_UNLOAD_MODULE_STATIC_DYNAMIC(OpenFoamFSI, "OFModule");
       return;
     }