ElmerFoamFSI: ElmerFoamFSI::SerialDriverProgram::Initialize
virtual int Initialize (void) inline virtual
Initializes native data structures from commandline args.
Reimplemented from Program< GlobalType, ComLineType >.
Definition at line 218 of file Driver.H.
References Program< GlobalType, ComLineType >::_command_line, GlobalObj< StackType, int, ProfilerType >::ErrOut(), Program< GlobalType, ComLineType >::Initialize(), SerialDriverProgram::input_name, SolverUtils::Ostr, SerialDriverProgram::output_name, GlobalObj< StackType, int, ProfilerType >::SetDebugLevel(), GlobalObj< StackType, int, ProfilerType >::SetDebugStream(), GlobalObj< StackType, int, ProfilerType >::SetVerbLevel(), GlobalObj< StackType, int, ProfilerType >::StdOut(), and SerialDriverProgram::verblevel.
Referenced by ElmerFoamFSI::ExampleProgram::Driver(), ElmerModuleDriver::ExampleProgram::Driver(), and ElmerFoamFSI::Driver().
     {
       int retval = SerialProgramType::Initialize();
       if(!_command_line.GetOption("help").empty()){
         std::ostringstream Ostr;
         Ostr << _command_line.LongUsage() << std::endl;
         StdOut(Ostr.str());
         return(-1);
       }
       if(retval){
         std::ostringstream Ostr;
         Ostr << _command_line.ErrorReport() << std::endl
              << std::endl << _command_line.ShortUsage() << std::endl;
         ErrOut(Ostr.str());
         return(retval);
       }
       if(!_command_line.GetOption("debug").empty()){
         this->SetDebugLevel(2);
         this->SetDebugStream(std::cout);
       }
       // Check if output file is specified
       output_name = _command_line.GetOption("output");
       // Set input file to first argument
       std::vector<std::string> args(_command_line.GetArgs());
       input_name = args[0];
       // Check the verbosity level
       std::string sverb(_command_line.GetOption("verbosity"));
       if(sverb.empty() || sverb == ".true.")
         verblevel = 1;
       else {
         std::istringstream Vin(sverb);
         Vin >> verblevel;
         if(verblevel < 0)
           verblevel = 1;
       }
       //Set the verblevel within IRAD
       SetVerbLevel((char)verblevel);
       // If high verbosity, stick a configuration blurb to stdout.
       if(verblevel > 1){
         std::ostringstream Ostr;
         Ostr << "Configuration:" << std::endl
              << "verbosity           = " << verblevel << std::endl
              << "config file         = " << input_name << std::endl;
         if(!output_name.empty())
           Ostr << "output file         = " << output_name << std::endl;
         Ostr << std::endl;
         StdOut(Ostr.str());
       }
       return(0);
     };