ElmerFoamFSI: IRAD::DDFComLine::Initialize
void Initialize (void) inline virtual
virtual function for program specific Initialization.
Reimplemented from ComLineObject.
Definition at line 25 of file DiffDataFiles.H.
References ComLineObject::_description, ComLineObject::AddArgHelp(), ComLineObject::AddArgument(), ComLineObject::AddHelp(), ComLineObject::AddOption(), and SolverUtils::Ostr.
                      {
       std::ostringstream Ostr;
       AddArgument("file1",1);
       AddArgHelp("file1","First file to read in for comparison against file2.");
       AddArgument("file2",1);
       AddArgHelp("file2","Second file to read in for comparison against file1.");
       AddOption('h',"help");
       AddHelp("help","Print out long version of help and exit.");
       AddOption('v',"verblevel",1,"level");
       AddHelp("verblevel","Set the verbosity level. (default = 1)");
       AddOption('o',"output",2,"filename");
       AddHelp("output","Set the output file to <filename>. (default = stdout)");
       AddOption('t',"tolerance",2,"tolerance");
       Ostr << "Set the numerical tolerance for comparing numbers to <tolerance>."
 //           << "\n\t\t(The default for the tolerance is 1.0e-12.)"
            << "\n\t\t(The default behavior without -t is to compare numbers as strings.)"
            << "\n\t\t(This flag will automatically force the -b flag to be used.)";
       AddHelp("tolerance",Ostr.str());
       Ostr.str("");
       AddOption('p',"percent",2,"percent");
       Ostr << "Set the numerical tolerance for comparing numbers to be calculated as"
            << "\n\t\ta percent difference. Numbers will be listed as different if the"
            << "\n\t\tdifference between two numbers is greater than <percent> percent"
            << "\n\t\tof the number from the first file. This is useful for comparing"
            << "\n\t\tvery large numbers." // The default percent used is 1.0."
            << "\n\t\tNOTE: Using the '-n' flag will force the tolerance to be used,"
            << "\n\t\toverwriting the use of percent.";
       AddHelp("percent",Ostr.str());
       AddOption('n',"numbers");
       Ostr.str("");
       Ostr << "Only compare the numbers in the two files."
            << "\n\t\t(This flag will automatically force the -t flag to be used.)";
       AddHelp("numbers",Ostr.str());
       AddOption('b',"blank");
       AddHelp("blank","Ignore blank space between words (or numbers).");
       Ostr.str("");
       Ostr << "Command-line interface for comparing data files.";
       _description.assign(Ostr.str());
     };