ElmerFoamFSI: SolverUtils::TransferObjectPar::TransferObjectPar
TransferObjectPar (const std::string & inSurfxName, MPI_Comm inComm, int inVerbLevel = 1) inline
Definition at line 380 of file InterfaceLayer.H.
References TransferObjectPar::_nProc, TransferObjectPar::_rank, TransferObjectPar::clearhandle, COM_get_function_handle(), SolverUtils::COM_LOAD_MODULE_STATIC_DYNAMIC(), TransferObjectPar::interphandle, TransferObjectPar::loadtranshandle, TransferObjectPar::overlayhandle, TransferObjectPar::readhandle, TransferObjectPar::SetVerbosity(), TransferObjectPar::surfxWinName, TransferObjectPar::transferhandle, TransferObjectPar::verbhandle, and TransferObjectPar::writehandle.
                                                                                           :
       surfxWinName(inSurfxName), _comm(inComm), verbLevel(inVerbLevel),
       nItrLsqTrans(100), tolLsqTrans(1.0e-6)
     {
       MPI_Comm_rank(inComm, &_rank);
       MPI_Comm_size(inComm, &_nProc);
       COM_LOAD_MODULE_STATIC_DYNAMIC(SurfX, surfxWinName.c_str());
       readhandle      = COM_get_function_handle((surfxWinName+std::string(".read_overlay")).c_str());
       writehandle     = COM_get_function_handle((surfxWinName+std::string(".write_overlay")).c_str());
       clearhandle     = COM_get_function_handle((surfxWinName+std::string(".clear_overlay")).c_str());
       verbhandle      = COM_get_function_handle((surfxWinName+std::string(".set_verbose")).c_str());
       overlayhandle   = COM_get_function_handle((surfxWinName+std::string(".overlay")).c_str());
       interphandle    = COM_get_function_handle((surfxWinName+std::string(".interpolate")).c_str());
       transferhandle  = COM_get_function_handle((surfxWinName+std::string(".least_squares_transfer")).c_str());
       loadtranshandle = COM_get_function_handle((surfxWinName+std::string(".load_transfer")).c_str());
       SetVerbosity();
     };