ElmerFoamFSI: ElmerFoamFSI::TestingObject::Test__fsiCouplerAgentsInitialize
virtual void Test__fsiCouplerAgentsInitialize () inline virtual
Initalize function for the fsiCoupler and agents.
Definition at line 611 of file ElmerFoamFSITest.H.
References TestingObject< ResultsType >::__helper(), IRAD::Sys::ChDir(), COM_load_module(), TestingObject< ResultsType >::componentInterfaceNames, IRAD::Sys::CWD(), IRAD::Sys::FILEEXISTS(), TestingObject< ResultsType >::fsiCoupler, fsicoupling::SetRunMode(), fsicoupling::SetVerbLevel(), TestingObject< ResultsType >::TestfluidsAgent, TestingObject< ResultsType >::TeststructuresAgent, and TestingObject< ResultsType >::verblevel.
Referenced by TestingObject< ResultsType >::Test__ElmerStructures(), TestingObject< ResultsType >::Test__FsiCoupler(), and TestingObject< ResultsType >::Test__OpenFoamFluids().
{
       int work =__helper();
       int IntDir;
       verblevel = 3;
       TeststructuresAgent = new solidagent;
       TestfluidsAgent = new fluidagent;
       std::string fluidDir;
       std::string simStaticDir;
       fluidDir = IRAD::Sys::CWD() + "/SimpleStatic/fluid";
       simStaticDir = IRAD::Sys::CWD() + "/SimpleStatic";
       if(work == 1)
         std::cout << "GetInputData failed 2!" << std::endl;
       else if (work == 2)
         std::cout << "Could not find directory for running tests" << std::endl;
       if(!(IRAD::Sys::FILEEXISTS(fluidDir)||(IRAD::Sys::FILEEXISTS(simStaticDir)))){
         std::cout << "SimpleStatic / fluid Folders do not exists!" << std::endl;
         return;
       }
       else{
         IntDir = IRAD::Sys::ChDir(simStaticDir);
         if(IntDir == -1){
           std::cout << "GetInputData Error: Could not change directory to "
                     << fluidDir << ". Exiting (fail). " << std::endl;
         }
         std::system("chmod 755 Allclean Allrun AllrunPar makeLinks makeSerialLinks removeSerialLinks");
         std::system("./Allclean");
         std::system("./Allrun");
         IntDir = IRAD::Sys::ChDir(fluidDir);
         if(IntDir == -1){
           std::cout << "GetInputData Error: Could not change directory to "
                     << fluidDir << ". Exiting (fail). " << std::endl;
         }
       }
       std::string fluidSolverName("OpenFoamFSI");
       std::string solidSolverName("ElmerCSC");
       std::string transferServiceName("SurfX");
       std::string runMode("1");
       std::cout << "COM loading all modules" << std::endl;
       COM_load_module(fluidSolverName.c_str(),"FluidsComponentInterface");
       COM_load_module(solidSolverName.c_str(),"StructuresComponentInterface");
       COM_load_module("SurfUtil","SurfUtil");
       COM_load_module("Simpal","Simpal");
       componentInterfaceNames.push_back("FluidsComponentInterface");
       componentInterfaceNames.push_back("StructuresComponentInterface");
       componentInterfaceNames.push_back("TransferInterface");
       componentInterfaceNames.push_back("SurfUtil");
       componentInterfaceNames.push_back("Simpal");
       fsiCoupler.SetRunMode(runMode);
       fsiCoupler.SetVerbLevel(verblevel);
       std::cout << "fsiCouplerAgentsInitialize Successful!" << std::endl;
     }