ElmerFoamFSI: ElmerModuleDriver::TestingObject::Test__MidPointQuadrature
virtual void Test__MidPointQuadrature (ResultsType & result) inline virtual
Test for ElmerModuleDriver::MidPointQuadrature.
Parameters
result ElmerModuleDriver::TestResults object to store test results.
This function implements a simple test of the function ElmerModuleDriver::MidPointQuadrature - which is designed to integrate a function, f, over an interval .
The test first makes sure that the method integrates a linear function exactly, and then that the error term has the proper dependence on the spacings.
Definition at line 229 of file ElmerModuleDriverTest.H.
References ElmerModuleDriver::TestFixture::F1(), ElmerModuleDriver::TestFixture::F2(), ElmerModuleDriver::MidPointQuadrature(), and TestingObject< ResultsType >::N.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       std::ostringstream Ostr;
       std::vector<double> Ibar;
       std::vector<double> E;
       size_t n = 2*N.size();
       bool runs = true;
       bool order2 = true;
       for(std::vector<int>::iterator i = N.begin();i != N.end();i++){
         double Ii = 0.0;
         try {
           Ii = ElmerModuleDriver::MidPointQuadrature(TestFixture::F1,0,1,*i);
         } catch (...) {
           runs = false;
         }
         Ibar.push_back(Ii);
         E.push_back(std::fabs(Ii-1.0));
       }
       order2 = (E[0] < 1e-14);
       for(std::vector<int>::iterator i = N.begin();i != N.end();i++){
         double Ii = 0.0;
         try {
           Ii = ElmerModuleDriver::MidPointQuadrature(TestFixture::F2,0,1,*i);
         } catch (...) {
           runs = false;
         }
         Ibar.push_back(Ii);
         E.push_back(std::fabs(Ii-1.0));
       }
       result.UpdateResult("MidPointQuadrature:Runs",runs);
       result.UpdateResult("MidPointQuadrature:Accurate",E[n-1] < 1e-12);
       for(int i = N.size();i < n - 1;i++){
         double e = E[i+1]/E[i];
         double n1 = static_cast<double>(N[i-N.size()])/static_cast<double>(N[(i-N.size())+1]);
         double p = std::log(e)/std::log(n1);
         p -= 2;
         p = std::abs(p);
         if(p > 1e-2){
           order2 = false;
         }
       }
       result.UpdateResult("MidPointQuadrature:Order2",order2);
     }