ElmerFoamFSI: OpenFoamModuleDriver::TestingObject::Test__ModuleSurfaceData
virtual void Test__ModuleSurfaceData (ResultsType & result) inline virtual
Definition at line 396 of file OpenFoamModuleDriverTest.H.
References TestingObject< ResultsType >::GetInputData(), and TestingObject< ResultsType >::SourceDirPath.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       std::cout << "Running Test__ModuleSurfaceData" << std::endl;
       //load OpenFoam module
       COM_LOAD_MODULE_STATIC_DYNAMIC(OpenFoamFSI, "OFModule");
       //Call GetInputData to copy input test data to temp directory for running tests.
       std::string suffix = "/share/Testing/test_data/HronTurekFsi";
       std::string dirName = SourceDirPath + suffix;
       std::string testDir = IRAD::Sys::CWD() + "/UnitTestDataSurfaceData";
       int IntDir = GetInputData(dirName, testDir);
       std::string fluidDir = testDir + "/fluid";
       std::string OrgDir = IRAD::Sys::CWD();
       IntDir = IRAD::Sys::ChDir(fluidDir);
       // call init to setup the mesh
       int dummy1=1;
       char *dummy2[2];
       dummy2[0] = const_cast<char *>(std::string("DataReg").c_str());
       dummy2[1] = NULL;
       int initHandle = COM_get_function_handle("OFModule.InitFoam");
       COM_call_function(initHandle, &dummy1, &dummy2);
       // list of panes in this window
       int numPanes;
       int* paneList;
       COM_get_panes("OFModule", &numPanes, &paneList);
       // only one pane for serial runs
       int pane = paneList[0];
       // check that the pressure is registered
       int status = COM_get_status("OFModule.pressure", pane);
       if(status <= 0) {
         std::cout << "ModuleSurfaceData Error: pressure not a valid DataItem. "
                   << "status = " << status << std::endl;
         result.UpdateResult("PressureData:Registered", false);
         return;
       } else {
         result.UpdateResult("PressureData:Registered", true);
       }
       // get some information about how the item was registered
       char getDataItemLoc;
       COM_Type getDataItemType;
       int getDataItemComponents;
       std::string getDataItemUnits;
       COM_get_dataitem("OFModule.pressure", &getDataItemLoc, &getDataItemType,
                    &getDataItemComponents, &getDataItemUnits);
       double* pressure=NULL;
       COM_get_array("OFModule.pressure", pane, &pressure);
       // check the array size against what we expect
       // pressures are scalars stored at the cell centers
       // assumes a single connectivity for this pane
       bool pressureCorrect = false;
       int numPres = 0;
       int numPresExpected = 168;
       int numPresCompExpected = 1;
       COM_get_size("OFModule.pressure", pane, &numPres);
       if (numPres != numPresExpected || numPresCompExpected != getDataItemComponents) {
         std::cout << "Wrong number of pressures registered for this mesh." << std::endl;
         std::cout << "Got " << numPres << " Items, Expected: " << numPresExpected << std::endl;
         std::cout << "Got " << getDataItemComponents << " Components, Expected: "
                   << numPresCompExpected << std::endl;
       } else {
         pressureCorrect = true;
       }
       // traction
       status = COM_get_status("OFModule.traction", pane);
       if(status <= 0) {
         std::cout << "ModuleSurfaceData Error: traction not a valid DataItem."
                   << "status = " << status << std::endl;
         result.UpdateResult("TractionData:Registered", false);
         return;
       } else {
         result.UpdateResult("TractionData:Registered", true);
       }
       COM_get_dataitem("OFModule.traction", &getDataItemLoc, &getDataItemType,
                    &getDataItemComponents, &getDataItemUnits);
       double* traction=NULL;
       COM_get_array("OFModule.traction", pane, &traction);
       // check the array size against what we expect
       // tractions are 3-dimensional vectors stored at the cell centers
       bool tractionCorrect = false;
       int numTrac = 0;
       int numTracExpected = 168;
       int numTracCompExpected = 3;
       COM_get_size("OFModule.traction", pane, &numTrac);
       if (numTrac != numTracExpected || numTracCompExpected != getDataItemComponents) {
         std::cout << "Wrong number of tractions registered for this mesh." << std::endl;
         std::cout << "Got " << numTrac << " Items, Expected: " << numTracExpected << std::endl;
         std::cout << "Got " << getDataItemComponents << " Components, Expected: "
                   << numTracCompExpected << std::endl;
       } else {
         tractionCorrect = true;
       }
       // now step the solution and compare the pressure and traction vs what
       // we expect from the sample problem
       int stepHandle = COM_get_function_handle("OFModule.StepFluid");
       COM_call_function(stepHandle);
       bool works=false;
       //testTime = 1.e-3;
       //toler = 1.e-9;
       if(0)
         works=true;
       else {
         std::cout << "ModuleSurfaceData Error: pressure incorrect "
                   << std::endl;
       }
       result.UpdateResult("PressureData:Correct", pressureCorrect);
       result.UpdateResult("TractionData:Correct", tractionCorrect);
       // cleanup
       IntDir = IRAD::Sys::ChDir(OrgDir);
       //Unload OpenFoam module
       COM_UNLOAD_MODULE_STATIC_DYNAMIC(OpenFoamFSI, "OFModule");
       return;
     }