ElmerFoamFSI: Element_node_enumerator_uns::next
void next () inline
Definition at line 152 of file Element_accessors.hpp.
References Element_node_enumerator::_conn, Element_node_enumerator::_pane, Element_node_enumerator::_res, Element_node_enumerator::_start, Pane::connectivity(), Connectivity::index_offset(), Connectivity::pointer(), Connectivity::size_of_elements(), and Connectivity::size_of_nodes_pe().
               {
     if ( --_res==0) {
       _conn = _pane->connectivity( _conn->index_offset()+1+
                                    _conn->size_of_elements());
       if ( _conn) {
         _start = _conn->pointer();
         _res = _conn->size_of_elements();
       }
       else {
         _start = NULL;
         _res = -1;
       }
     }
     else
       _start += _conn->size_of_nodes_pe();
   }