ElmerFoamFSI: SolverModuleDriver::run
int run ()
Get the handle for the run function and call it
Definition at line 103 of file ElmerFSI/trunk/src/SolverModuleDriver.C.
References Connectivity::AddElements(), SolutionMetaData::AddField(), changeLoads, COM_call_function(), COM_get_array(), COM_get_dataitem_handle(), COM_get_function_handle(), COM_get_size(), UnstructuredMesh::con, Conn, connCorrect, ConnSize, Coord, coord_handle, coordData, CoordSize, SolverAgent::CreateSoln(), Disp, DispPass, DispSize, elems, NodalCoordinates::init(), isFSI, Loads, LoadsPass, LoadsSize, SolverAgent::Mesh(), SolutionData::Meta(), UnstructuredMesh::nc, runs, SolutionData::SetFieldBuffer(), SolverAgent::Solution(), ss, tNext, SolverAgent::WriteMeshToStream(), SolverAgent::WriteSolnMetaToStream(), and SolverUtils::WriteVTKToStream().
Referenced by main().
{
   if(isFSI){
     // Check coordinate values
     coord_handle = COM_get_dataitem_handle("Window1.nc");
     CoordSize=0;
     coordData = (coord_handle > 0);
     std::cout << "SoverModuleDriver:run: coord_handle = " << coord_handle << std::endl;
     if(coordData){
       COM_get_size("Window1.nc",11,&CoordSize);
       // Get the FSI mesh from the structures solver and print
       // it out to check
       COM_get_array("Window1.nc",11,&Coord);
       std::cout << "SoverModuleDriver:run: Coord: " << std::endl;
       for(int i=0; i < CoordSize; i++){
         for(int j=0; j < 3; j++){
           std::cout << Coord[i*3+j] << " ";
         }
         std::cout << std::endl;
       }
       Mesh().nc.init(CoordSize, Coord);
     }
     // Check connectivity values
     connCorrect = true;
     ConnSize = 0;
     // Get the FSI mesh from the structures solver
     COM_get_array("Window1.:b2:",11,&Conn);
     if(Conn){
       // Get the FSI mesh size from the structures solver
       COM_get_size("Window1.:b2:",11,&ConnSize);
       // check the values
       std::cout << "SoverModuleDriver:run: Conn: " << std::endl;
       for(int i=0; i < ConnSize; i++){
         for(int j=0; j < 2; j++){
           std::cout << Conn[i*2+j] << " ";
           elems.push_back(Conn[i*2+j]);
         }
         std::cout << std::endl;
       }
       Mesh().con.AddElements(ConnSize,2,elems);
     }
     if(Conn && coordData){
       std::cout << "SoverModuleDriver:run: WriteMeshToStream: " << std::endl;
       WriteMeshToStream(std::cout);
       std::cout << std::endl;
     }
     // Check displacement data
     COM_get_array("Window1.Displacements",11,&Disp);
     if (Disp){
       // Get the FSI displacement size from the structures solver
       COM_get_size("Window1.Displacements",11,&DispSize);
       std::cout << "SoverModuleDriver:run: Checking displacements" << std::endl;
       for(int i=0; i < DispSize; i++){
          for(int j=0; j < 3; j++){
             std::cout << Disp[i*3+j] << " ";
             DispPass.push_back(Disp[i*3+j]);
          }
          std::cout << std::endl;
       }
     }
   }
   std::cout << "Line = " << __LINE__ << std::endl;
   //If we want to prescribe loads here's where we do it
   Loads = NULL;
   LoadsSize = 0;
   // Get the FSI loads from the structures solver
   if(isFSI && changeLoads){
     COM_get_array("Window1.Loads",11,&Loads);
     if(Loads){
       std::cout << "SoverModuleDriver:run: Loads not NULL" << std::endl;
       // Get the FSI load size from the structures solver
       COM_get_size("Window1.Loads",11,&LoadsSize);
       // Check load data
       std::cout << "SoverModuleDriver:run: Checking loads" << std::endl;
       for(int i=0; i < LoadsSize; i++){
          for(int j=0; j < 3; j++){
             Loads[i*3 + j] = double(i*3 + j);
             std::cout << Loads[i*3+j] << " ";
             LoadsPass.push_back(Loads[i*3+j]);
          }
          std::cout << std::endl;
       }
     }
   }
   std::cout << "SoverModuleDriver:run: Line = " << __LINE__ << std::endl;
   //Put the displacements and loads in the Solution object
   //so we can use its utilities and write a vtk file
   if(Disp && isFSI){
     Solution().Meta().AddField("displacement",'n',3,8,"m");
     std::cout << "SoverModuleDriver:run: WriteSolnMetaToStream:" << std::endl;
     WriteSolnMetaToStream(std::cout);
     std::cout << std::endl;
   }
   if(Loads && isFSI){
     Solution().Meta().AddField("loads",'n',3,8,"");
     std::cout << "SoverModuleDriver:run: WriteSolnMetaToStream:" << std::endl;
     WriteSolnMetaToStream(std::cout);
     std::cout << std::endl;
   }
   std::cout << "SoverModuleDriver:run: Line = " << __LINE__ << std::endl;
   if((Disp && isFSI) || Loads){
     CreateSoln();
   }
   std::cout << "SoverModuleDriver:run: Line = " << __LINE__ << std::endl;
   if(Disp && isFSI)
     Solution().SetFieldBuffer("displacement",DispPass);
   if(Loads && isFSI)
     Solution().SetFieldBuffer("loads",LoadsPass);
   std::cout << "SoverModuleDriver:run: Line = " << __LINE__ << std::endl;
   //Write vtk file for timestep 0
   if(isFSI && Conn && Coord){
     std::ofstream Ouf;
     std::string filename;
     filename = "fsi0.vtk";
     Ouf.open(filename.c_str());
     if(!Ouf){
         std::cerr << "SoverModuleDriver:run: SolverModuleDriver::DumpSolution:Error: Could not open output file, "
                   << filename << "." << std::endl;
         return -1;
       }
       std::cout << "SoverModuleDriver:run: WriteVTKToStream time 0" << std::endl;
       SolverUtils::WriteVTKToStream("Window1",*this,Ouf);
       Ouf.close();
   }
   int run_handle = COM_get_function_handle("Window1.Run");
   bool run_func = (run_handle > 0);
   runs = 0;
   if(run_func){
     int timestep = 0;
     for(int i=0; i < tNext.size(); i++){
       //Change the load values as a test
       if(Loads && isFSI){
          std::cout << "SoverModuleDriver:run: Changing load values" << std::endl;
          for(int k=0; k < LoadsSize; k++){
             for(int j=0; j < 3; j++){
                Loads[k*3 + j] = double(k*3 + j) + tNext[i];
                std::cout << Loads[k*3 + j] << " ";
                LoadsPass[k*3 + j] = Loads[k*3 + j];
             }
             std::cout << std::endl;
          }
       }
       std::cout << "SoverModuleDriver:run: Calling run function from driver" << std::endl;
       COM_call_function(run_handle,&runs,&tNext[i]);
       //Update Solution's displacments for writing vtk file
       if(isFSI && Disp){
         std::cout << "SoverModuleDriver:run: Checking displacements" << std::endl;
         for(int k=0; k < DispSize; k++){
            for(int j=0; j < 3; j++){
               std::cout << Disp[k*3+j] << " ";
               DispPass[k*3+j] = Disp[k*3+j];
            }
            std::cout << std::endl;
         }
       }
       timestep++;
       //Write vtk file for timestep
       if(isFSI && Conn && Coord){
         std::ofstream Ouf;
         ss.clear();
         ss.str("");
         ss << timestep;
         std::string filename;
         filename = "fsi" + ss.str() + ".vtk";
         Ouf.open(filename.c_str());
         if(!Ouf){
             std::cerr << "SolverModuleDriver::DumpSolution:Error: Could not open output file, "
                       << filename << "." << std::endl;
             return -1;
           }
           SolverUtils::WriteVTKToStream("Window1",*this,Ouf);
           Ouf.close();
       }
     }
   }
   return 0;
 }