ElmerFoamFSI: ElmerFoamFSI::TestingObject::Test__ElmerStructures
virtual void Test__ElmerStructures (ResultsType & result) inline virtual
Run an initialization check to make sure that the ElmerStructures are running as they should.
Definition at line 726 of file ElmerFoamFSITest.H.
References TestingObject< ResultsType >::componentInterfaceNames, elmeragent::Initialize(), elmeragent::returnNodeCoords(), TestingObject< ResultsType >::Test__fsiCouplerAgentsInitialize(), TestingObject< ResultsType >::TeststructuresAgent, and TestingObject< ResultsType >::verblevel.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
         bool works = true;
         std::cout << "Initalizing Structure..." << std::endl;
         Test__fsiCouplerAgentsInitialize();
         int initresult = TeststructuresAgent->Initialize(componentInterfaceNames[1], verblevel);
         std::cout << "Initialization Completed!" << std::endl;
         //Make sure the initializing doesn't return an error
         if (initresult != 0){
                 std::cout << "structuresAgent->Initialize returns error. " <<
                              "Refer to ElmerAgent.H for more information. " << std::endl;
                 works = false;
         }
         //Test to make sure the node coordinates are populated
         //More of an exercise to make sure the data is loaded correctly
         //face coordinates are not in use currently
         std::vector<double> nodecoordinates(TeststructuresAgent->returnNodeCoords());
         std::cout << "Node size is: " << nodecoordinates.size() << std::endl;
         if (nodecoordinates.size() < 0){
                 std::cout << "There is a problem with obtaining the nodecoordinate data" <<
                              "Refer to ElmerAgent.H for more information. " << std::endl;
                 works = false;
         }
         double arr[306] = {0.1, 0.1, 0, 0, 0.1, 0, 0, 0.1, 0.02, 0.1, 0.1, 0.02, 0, 0.1, 0.04, 0.1, 0.1, 0.04, 0, 0.1, 0.06, 0.1, 0.1, 0.06, 0, 0.1, 0.08, 0.1, 0.1, 0.08, 0, 0.1, 0.1, 0.1, 0.1, 0.1, 0, 0.1, 0.12, 0.1, 0.1, 0.12, 0, 0.1, 0.14, 0.1, 0.1, 0.14, 0, 0.1, 0.16, 0.1, 0.1, 0.16, 0, 0.1, 0.18, 0.1, 0.1, 0.18, 0, 0.1, 0.2, 0.1, 0.1, 0.2, 0, 0.1, 0.22, 0.1, 0.1, 0.22, 0, 0.1, 0.24, 0.1, 0.1, 0.24, 0, 0.1, 0.26, 0.1, 0.1, 0.26, 0, 0.1, 0.28, 0.1, 0.1, 0.28, 0, 0.1, 0.3, 0.1, 0.1, 0.3, 0, 0.1, 0.32, 0.1, 0.1, 0.32, 0, 0.1, 0.34, 0.1, 0.1, 0.34, 0, 0.1, 0.36, 0.1, 0.1, 0.36, 0, 0.1, 0.38, 0.1, 0.1, 0.38, 0, 0.1, 0.4, 0.1, 0.1, 0.4, 0, 0.1, 0.42, 0.1, 0.1, 0.42, 0, 0.1, 0.44, 0.1, 0.1, 0.44, 0, 0.1, 0.46, 0.1, 0.1, 0.46, 0, 0.1, 0.48, 0.1, 0.1, 0.48, 0, 0.1, 0.5, 0.1, 0.1, 0.5, 0, 0.1, 0.52, 0.1, 0.1, 0.52, 0, 0.1, 0.54, 0.1, 0.1, 0.54, 0, 0.1, 0.56, 0.1, 0.1, 0.56, 0, 0.1, 0.58, 0.1, 0.1, 0.58, 0, 0.1, 0.6, 0.1, 0.1, 0.6, 0, 0.1, 0.62, 0.1, 0.1, 0.62, 0, 0.1, 0.64, 0.1, 0.1, 0.64, 0, 0.1, 0.66, 0.1, 0.1, 0.66, 0, 0.1, 0.68, 0.1, 0.1, 0.68, 0, 0.1, 0.7, 0.1, 0.1, 0.7, 0, 0.1, 0.72, 0.1, 0.1, 0.72, 0, 0.1, 0.74, 0.1, 0.1, 0.74, 0, 0.1, 0.76, 0.1, 0.1, 0.76, 0, 0.1, 0.78, 0.1, 0.1, 0.78, 0, 0.1, 0.8, 0.1, 0.1, 0.8, 0, 0.1, 0.82, 0.1, 0.1, 0.82, 0, 0.1, 0.84, 0.1, 0.1, 0.84, 0, 0.1, 0.86, 0.1, 0.1, 0.86, 0, 0.1, 0.88, 0.1, 0.1, 0.88, 0, 0.1, 0.9, 0.1, 0.1, 0.9, 0, 0.1, 0.92, 0.1, 0.1, 0.92, 0, 0.1, 0.94, 0.1, 0.1, 0.94, 0, 0.1, 0.96, 0.1, 0.1, 0.96, 0, 0.1, 0.98, 0.1, 0.1, 0.98, 0, 0.1, 1, 0.1, 0.1, 1};
         for (int i = 0; i < 306; i++){
                 if (arr[i] != nodecoordinates.at(i)){
                         std::cout << "Node Coordinate Inconsistencies." << std::endl;
                         works = false;
                         break;
                 }
         }
         result.UpdateResult("ElmerStructures:Works",works);
         delete TeststructuresAgent;
     }