ElmerFoamFSI: fsicouplingpar::Initialize
virtual int Initialize (std::vector< std::string > & componentInterfaceNames, double finalTime, double timeStep) inline virtual
Definition at line 254 of file FsiCouplingPar.H.
References COM_set_array(), ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Communicator(), couplingbase::componentAgents, fluidsAgent, fluidsInterfaceName, fluidsWinFnameHDF, GlobalObj< StackType, ErrorType, ProfilerType >::FunctionEntry(), GlobalObj< StackType, ErrorType, ProfilerType >::FunctionExit(), openfoamagentpar::Initialize(), elmeragentpar::Initialize(), TransferObjectPar::Overlay(), probNdeId, probProcId, probSolverName, runMode, setsProb, simoutInterfaceName, simpalInterfaceName, simulationFinalTime, simulationTime, simulationTimeStep, GlobalObj< StackType, ErrorType, ProfilerType >::StdOut(), structuresAgent, structuresInterfaceName, structuresWinFnameHDF, surfUtilInterfaceName, transferAgent, transferInterfaceName, verblevel, and writeWin().
{
     FunctionEntry("Initialize");
     std::stringstream outString;
     outString << "Final Time = " << finalTime << std::endl;
     outString << "Time Step  = " << timeStep << std::endl;
     StdOut(outString.str(),0,true);
     outString.clear();
     outString.str("");
     if(componentInterfaceNames.size() < 2)
       return(1);
     fluidsInterfaceName     = componentInterfaceNames[0];
     structuresInterfaceName = componentInterfaceNames[1];
     transferInterfaceName   = componentInterfaceNames[2];
     surfUtilInterfaceName   = componentInterfaceNames[3];
     simpalInterfaceName     = componentInterfaceNames[4];
     simoutInterfaceName     = componentInterfaceNames[5];
     fluidsAgent     = new fluidagentpar;
     structuresAgent = new solidagentpar;
     transferAgent   = new transferagentpar(transferInterfaceName, (this->Communicator()).GetCommunicator(),
                                         verblevel);
     // Initialize the fluids module and writing the window
     if(runMode != 2)
       fluidsAgent->Initialize(fluidsInterfaceName, verblevel);
     Communicator().Barrier();
     writeWin((const char *)fluidsInterfaceName.c_str(), "0", fluidsWinFnameHDF);
     Communicator().Barrier();
     // Initialize the structures module and writing the window
     if(runMode != 1)
       structuresAgent->Initialize(structuresInterfaceName, verblevel);
     writeWin((const char *)structuresInterfaceName.c_str(), "0", structuresWinFnameHDF);
     Communicator().Barrier();
     // accessing a dataitem for fast debugging
     /*
     double* Disps;
     int stride, cap;
     COM_get_array((structuresInterfaceName+".Displacements").c_str(), structuresAgent->PaneID(),
                    &Disps, &stride, &cap);
     for (int i=0; i<stride*cap; i++)
        std::cout << "Rank " << Rank()
                  << "Item = " << Disps[i]
                  << std::endl;
     */
     // Initialize the transfer module's common refinement
     if(runMode == 0) {
       transferAgent->Overlay(structuresInterfaceName, fluidsInterfaceName,
                              structuresWinFnameHDF, fluidsWinFnameHDF);
       //TestTransfer();
     }
     // setting up probe for the solver
     // only implementd for fluids solver
     COM_set_array((fluidsInterfaceName+".setsProb").c_str(),0,&setsProb);
     if(setsProb){
       std::string newDataItemName(probSolverName+".probProcId");
       COM_set_array(newDataItemName.c_str(),0,&probProcId);
       newDataItemName = probSolverName+".probNdeId";
       COM_set_array(newDataItemName.c_str(),0,&probNdeId);
     }
     componentAgents.resize(2);
     componentAgents[0] = fluidsAgent;
     componentAgents[1] = structuresAgent;
     simulationTime = 0; // ? (restart)
     simulationFinalTime = finalTime;
     simulationTimeStep = timeStep;
     //DumpSolution();
     FunctionExit("Initialize");
     return(0);
   };