ElmerFoamFSI: fsicouplingpar::Run
virtual int Run () inline virtual
Reimplemented from couplingbase.
Definition at line 340 of file FsiCouplingPar.H.
References ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Communicator(), agentbase::FinalizeTimeStep(), fluidsAgent, GlobalObj< StackType, ErrorType, ProfilerType >::FunctionEntry(), GlobalObj< StackType, ErrorType, ProfilerType >::FunctionExit(), agentbase::InitializeTimeStep(), ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::NProc(), openfoamagentpar::Run(), elmeragentpar::Run(), runMode, simulationFinalTime, simulationTime, simulationTimeStep, GlobalObj< StackType, ErrorType, ProfilerType >::StdOut(), structuresAgent, TransferDisplacementsToFluid(), and TransferLoadsToStructures().
                    {
     FunctionEntry("Run");
     // Enter timestepping
     int innerCount = 0;
     int maxSubSteps = 1000;
     int dumpinterval = 1;
     int systemStep = 0;
     // gathering some information for user
     time_t nowStart = time(0);
     char* dtChar = ctime(&nowStart);
     char* hostName;
     gethostname(hostName, 150);
     std::stringstream outString;
     outString << std::endl << std::endl
               << "************************************************* " << std::endl;
     outString << "*           Starting Stepping in Time           * " << std::endl;
     outString << "************************************************* " << std::endl;
     outString << "* Starting Simulation at " <<  dtChar;
     outString << "* Summary of the simulation:                      " << std::endl;
     outString << "* " << std::endl;
     outString << "*     Simulation Type       = ElmerFoamFSIPar     " << std::endl;
     outString << "*     Simulation start time = " << simulationTime << std::endl;
     outString << "*     Simulation final time = " << simulationFinalTime << std::endl;
     outString << "*     Simulation time step  = " << simulationTimeStep << std::endl;
     outString << "*     Number of time steps  = " << int(simulationFinalTime/simulationTimeStep) << std::endl;
     outString << "* " <<std::endl;
     outString << "*     Hostname = " << hostName << std::endl;
     outString << "*     Number of processors  = " << NProc() << std::endl;
     outString << "************************************************* " << std::endl;
     outString << std::endl;
     StdOut(outString.str(),0,true);
     outString.clear();
     outString.str("");
     while(simulationTime < simulationFinalTime){
       // Write some stuff to screen
       outString << "System timestep " << ++systemStep
                 << " @ Time = " << simulationTime << std::endl;
       StdOut(outString.str(),1,true);
       outString.clear();
       outString.str("");
       if(!runMode){
         // Transfer displacements @ Tn to fluids
         outString << "Transferring displacements from structures to fluids @ time("
                   << simulationTime << ")" << std::endl;
         StdOut(outString.str(),1,true);
         outString.clear();
         outString.str("");
         TransferDisplacementsToFluid(structuresAgent,fluidsAgent);
       }
       if(runMode < 2){
         fluidsAgent->InitializeTimeStep(simulationTime);
         // Step fluids to get loads @ T(n+1)
         outString << "Stepping fluids to time("
                   << simulationTime+simulationTimeStep << ")" << std::endl;
         StdOut(outString.str(),1,true);
         outString.clear();
         outString.str("");
         fluidsAgent->Run(simulationTime+simulationTimeStep);
       }
       if(!runMode){
         outString << "Transferring loads from fluids to structures @ time("
                   << simulationTime << ")" << std::endl;
         StdOut(outString.str(),1,true);
         // Transfer loads @ T(n+1) to structures
         //std::cout << "FSICoupling: Transferring loads from fluids to structures @ time("
         //          << simulationTime+simulationTimeStep << ")" << std::endl;
         TransferLoadsToStructures(fluidsAgent,structuresAgent);
       }
       if(!(runMode==1)){
         structuresAgent->InitializeTimeStep(simulationTime);
         // Step structures to get displacements @ T(n+1)
         outString << "Stepping structures to time("
                   << simulationTime+simulationTimeStep << ")" << std::endl;
         StdOut(outString.str(),1,true);
         outString.clear();
         outString.str("");
         structuresAgent->Run(simulationTime+simulationTimeStep);
       }
       // Finalize timestep and advance time T(n) --> T(n+1)
       bool converged = true;
       if(converged){
         simulationTime += simulationTimeStep;
         outString << "Converged at time("
                   << simulationTime << ")" << std::endl;
         StdOut(outString.str(),1,true);
         outString.clear();
         outString.str("");
         if(runMode < 2)
           fluidsAgent->FinalizeTimeStep(simulationTime+simulationTimeStep);
         if(!(runMode == 1))
           structuresAgent->FinalizeTimeStep(simulationTime+simulationTimeStep);
         innerCount = 0;
       } else {
         innerCount++;
         if(innerCount > maxSubSteps){
           outString << "Failed to converge after "
                     << maxSubSteps << ", giving up." << std::endl;
           StdOut(outString.str(),0,true);
           outString.clear();
           outString.str("");
           return(1);
         }
       }
       StdOut(outString.str(),0,true);
       outString.clear();
       outString.str("");
       if(!(systemStep%dumpinterval)){
         //DumpSolution();
       }
     }
     Communicator().Barrier();
     // gathering some information for user
     time_t nowEnd = time(0);
     dtChar = ctime(&nowEnd);
     outString << std::endl << std::endl
               << "************************************************* " << std::endl;
     outString << "*           Finishing Stepping in Time          * " << std::endl;
     outString << "************************************************* " << std::endl;
     outString << "* Ending simulation at " <<  dtChar;
     outString << "* Total simulation time (s) = " <<  nowEnd - nowStart << std::endl;
     outString << "* Summary of the simulation:                      " << std::endl;
     outString << "* " << std::endl;
     outString << "*     Simulation Type       = ElmerFoamFSIPar     " << std::endl;
     outString << "*     Simulation final time = " << simulationFinalTime << std::endl;
     outString << "*     Simulation time step  = " << simulationTimeStep << std::endl;
     outString << "*     Number of time steps  = " << int(simulationFinalTime/simulationTimeStep) << std::endl;
     outString << "* " <<std::endl;
     outString << "*     Hostname = " << hostName << std::endl;
     outString << "*     Number of processors  = " << NProc() << std::endl;
     outString << "************************************************* " << std::endl;
     outString << std::endl;
     StdOut(outString.str(),0,true);
     FunctionExit("Run");
     return(0);
   };