ElmerFoamFSI: ElmerFoamFSI::TestingObject::Prologue
virtual void Prologue () inline virtual
Sets up the data fixtures for the tests.
This function gives the object a chance to allocate and set up any "fixtures" before the tests are run.
Reimplemented from TestingObject< ResultsType >.
Definition at line 136 of file ElmerFoamFSITest.H.
References COM_init(), TestingObject< ResultsType >::ExampleTestFixture, and TestingObject< ResultsType >::N.
Referenced by TestingObject< ResultsType >::Process(), TestingObject< ResultsType >::ProcessTests(), and TestingObject< ResultsType >::RunTest().
{
       ExampleTestFixture.assign("ExampleTestData");
       for(int i = 10;i < 10000000;i*=10) N.push_back(i);
       // initializing COM
       bool runs = false;
       int nargs_dupe = 2;
       char **args_dupe;
       args_dupe = new char * [3];
       args_dupe[0] = const_cast<char *>("test");
       args_dupe[1] = const_cast<char *>("-com-mpi");
       args_dupe[2] = NULL;
       COM_init(&nargs_dupe,&args_dupe);
     }