ElmerFoamFSI: IcoFoamMod::IcoFoamModule::Load
static void Load (const std::string & name) inline static
"Loads" IcoFoamModule
Definition at line 100 of file icoFoamModule.C.
References COM_INT, COM_new_dataitem(), COM_new_window(), COM_RAWDATA, COM_set_member_function(), COM_set_object(), COM_VOID, COM_window_init_done(), IcoFoamModule::IcoFoamModule(), IcoFoamModule::IcoFoamModuleFunction(), and IcoFoamModule::my_window_name.
Referenced by IcoFoamModule_load_module().
{
       std::cout << "Loading IcoFoamModule with name " << name
                 << "." << std::endl;
       IcoFoamModule *module_pointer = new IcoFoamModule();
       COM_new_window(name, MPI_COMM_NULL);
       module_pointer->my_window_name = name;
       std::string global_name(name+".global");
       COM_new_dataitem(global_name.c_str(),'w',COM_VOID,1,"");
       COM_set_object(global_name.c_str(),0,module_pointer);
       std::vector<COM_Type> types(13,COM_INT);
       types[0] = COM_RAWDATA;
       types[2] = COM_VOID;
       COM_set_member_function( (name+".IcoFoamModuleFunction").c_str(),
                                (Member_func_ptr)(&IcoFoamModule::IcoFoamModuleFunction),
                                global_name.c_str(), "bii", &types[0]);
       COM_window_init_done(name);
     }