ElmerFoamFSI: SolverUtils::FEM::SolverAgent::ReportMeshToStream
std::ostream& ReportMeshToStream (std::ostream & Ostr) inline
Definition at line 58 of file SolverAgent.H.
References UnstructuredMesh::con, SolverUtils::Mesh::GetCoordinateBounds(), SolverAgent::mesh, UnstructuredMesh::nc, Connectivity::Nelem(), GenericElement::ShapeOK(), and NodalCoordinates::Size().
     {
       Mesh::IndexType number_of_nodes = mesh.nc.Size();
       Ostr << "Number of nodes: " << number_of_nodes << std::endl;
       std::vector<double> bounds(6,0.0);
       Mesh::GetCoordinateBounds(mesh.nc,bounds);
       Ostr << "Mesh Bounds: (" << bounds[0] << "," << bounds[1]
            << ") (" << bounds[2] << "," << bounds[3]
            << ") (" << bounds[4] << "," << bounds[5] << ")" << std::endl;
       Mesh::Connectivity::iterator ci = mesh.con.begin();
       bool bump_node_indices_plus1 = false;
       if(bump_node_indices_plus1){
         while(ci != mesh.con.end()){
           std::vector<Mesh::IndexType>::iterator ii = ci->begin();
           while(ii != ci->end())
             (*ii++)++;
           ci++;
         }
         ci = mesh.con.begin();
       }
       Mesh::IndexType ntet  = 0;
       Mesh::IndexType nhex  = 0;
       Mesh::IndexType npyr  = 0;
       Mesh::IndexType npris = 0;
       Mesh::IndexType ntri  = 0;
       Mesh::IndexType nquad = 0;
       while(ci != mesh.con.end()){
         Mesh::IndexType esize = ci->size();
         Mesh::GenericElement el(4);
         bool known_element_type = false;
         switch(esize){
         case 3:
           ntri++;
           break;
         case 4:
           if(el.ShapeOK(*ci,mesh.nc))
             ntet++;
           else
             nquad++;
           break;
         case 5:
           npyr++;
           break;
         case 6:
           npris++;
           break;
         case 8:
           nhex++;
           break;
         case 10:
           ntet++;
           break;
         case 20:
           nhex++;
           break;
         default:
           assert(known_element_type);
         }
         ci++;
       }
       Mesh::IndexType number_of_elements = mesh.con.Nelem();
       Ostr << "Number of elements: " << number_of_elements
            << std::endl;
       if(ntet > 0)
         Ostr << "Number of tetrahedra: " << ntet << std::endl;
       if(npyr > 0)
         Ostr << "Number of pyramids:   " << npyr << std::endl;
       if(npris > 0)
         Ostr << "Number of prisms:     " << npris << std::endl;
       if(nhex > 0)
         Ostr << "Number of hexahedra:  " << nhex << std::endl;
       if(ntri > 0)
         Ostr << "Number of triangles:  " << ntri << std::endl;
       if(nquad > 0)
         Ostr << "Number of quads:      " << nquad << std::endl;
       return(Ostr);
     };