ElmerFoamFSI: fsicoupling::WriteAgentToVTK
int WriteAgentToVTK (const std::string & nameRoot, SolverUtils::FEM::SolverAgent & solverAgent) inline
Definition at line 453 of file FsiCoupling.H.
References couplingbase::outStream, simulationTime, GlobalObj< StackType, ErrorType, ProfilerType >::StdOut(), and SolverUtils::WriteVTKToStream().
Referenced by DumpSolution().
   {
     std::stringstream outString;
     std::ofstream outStream;
     std::ostringstream timeString;
     timeString << simulationTime;
     std::string fileName(nameRoot+"_"+timeString.str()+".vtk");
     outStream.open(fileName.c_str());
     if(!outStream){
       outString << "FSICoupling::DumpSolution:Error: Could not open output file, "
                 << fileName << "." << std::endl;
       StdOut(outString.str(),0,true);
       outString.clear();
       outString.str("");
       return(1);
     }
     SolverUtils::WriteVTKToStream(nameRoot, solverAgent, outStream);
     outStream.close();
   };