ElmerFoamFSI: Point_3::operator+=
Point_3& operator+= (const Vector_3< T > & v) inline
Assign operators.
Definition at line 144 of file mapbasic.h.
References Vector_3< T >::_x, Vector_3< T >::_y, Vector_3< T >::_z, Vector_3< Type >::x(), Vector_3< Type >::y(), and Vector_3< Type >::z().
   { _x+=v.x(); _y+=v.y(); _z+=v.z(); return *this; }