ElmerFoamFSI: OpenFoamModuleDriver::TestingObject::ProcessTests
virtual void ProcessTests (std::list< std::string > & test_names, ResultsType & result) inline virtual
Runs a list of tests specified by name.
Parameters
test_names list of string test names
result OpenFoamModuleDriver::TestResults object to store test results.
Definition at line 1392 of file OpenFoamModuleDriverTest.H.
References TestingObject< ResultsType >::Epilogue(), TestingObject< ResultsType >::Prologue(), and TestingObject< ResultsType >::RunTest().
{
       Prologue();
       std::list<std::string>::iterator tni = test_names.begin();
       while(tni != test_names.end())
         RunTest(*tni++,result);
       Epilogue();
     }