ElmerFoamFSI: SolverUtils::GeoPrim::CBox::empty
bool empty () const inline
Definition at line 1633 of file GeoPrimitives.H.
References CBox::p1, CBox::p2, SolverUtils::GeoPrim::TOL, CPoint::x(), CPoint::y(), and CPoint::z().
Referenced by CBox::collide().
                        {return ((std::fabs(p2.x()-p1.x()) < TOL) ||
                                 (std::fabs(p2.y()-p1.y()) < TOL) ||
                                 (std::fabs(p2.z()-p1.z()) < TOL));};