ElmerFoamFSI: ElmerFoamFSI::TestingObject::__helper
virtual int __helper () inline virtual
Definition at line 568 of file ElmerFoamFSITest.H.
References TestingObject< ResultsType >::GetInputData().
Referenced by TestingObject< ResultsType >::Test__FluidAgentRun(), TestingObject< ResultsType >::Test__fsiCouplerAgentsInitialize(), TestingObject< ResultsType >::Test__GetInput(), TestingObject< ResultsType >::Test__SolidAgentRun(), TestingObject< ResultsType >::Test__TransferDisplacementsToFluid(), and TestingObject< ResultsType >::Test__TransferLoadsToStructures().
{
       int IntDir;
       std::string OrgDir, TestDir;
       //call GetInputData to copy input test data to temp directory for running tests.
       std::string suffix = "/testing/share/Testing/test_data/SimpleStatic";
       //Make path for directory to run the test in
       TestDir = IRAD::Sys::CWD() + "/SimpleStatic";
       std::cout << "Getting Input Data!!" << std::endl;
       IntDir  = GetInputData(suffix, TestDir);
       //check if GetInputData exited correctly.
       if(IntDir != 0){
         std::cout << "GetInputData failed!"
                   << std::endl;
         return 1;
       }
       // Check if TestDir directory exists in current Directory
       if(!IRAD::Sys::FILEEXISTS(TestDir)){
         std::cout << "Could not find directory, "
                   << TestDir << ", for running tests." << std::endl;
         return 2;
       }
       return 0;
     }