ElmerFoamFSI: Simple_manifold_2::get_destination
int get_destination (Edge_ID eID, Element_node_enumerator * ene_in = NULL) const inline
Get the ID of the destination of a given edge.
Definition at line 353 of file Simple_manifold_2.h.
References _pane, Facet_ID::eid(), get_opposite_ghost_edge_border(), get_opposite_real_edge_border(), Facet_ID::is_border(), is_real_border_edge(), and Facet_ID::lid().
{
     if ( eID.is_border()) {
       Edge_ID opp;
       if (is_real_border_edge( eID)) opp = get_opposite_real_edge_border( eID);
       else opp = get_opposite_ghost_edge_border( eID);
       Element_node_enumerator ene( _pane, opp.eid());
       return ene[opp.lid()];
     }
     else {
       if ( ene_in)
         return (*ene_in)[eID.lid()+1==ene_in->size_of_edges()?0:eID.lid()+1];
       else {
         Element_node_enumerator ene( _pane, eID.eid());
         return ene[eID.lid()+1==ene.size_of_edges()?0:eID.lid()+1];
       }
     }
   }