ElmerFoamFSI: IRAD::Comm::CommunicatorObject::Gather
int Gather (DataType & sendval, std::vector< DataType > & recvvec, int root = 0) inline
Definition at line 307 of file COMM.H.
References CommunicatorObject::_comm, CommunicatorObject::_rc, CommunicatorObject::Rank(), and CommunicatorObject::Size().
Referenced by CommunicatorObject::AllGatherMO(), CommunicatorObject::AllGatherMOV(), CommunicatorObject::GatherMO(), CommunicatorObject::GatherMOV(), and CommunicatorObject::Gatherv().
       {
         size_t messagesize = sizeof(DataType);
         if(this->Rank() == root){
           recvvec.resize(this->Size());
         }
         _rc = MPI_Gather((void *)&sendval,messagesize,MPI_CHAR,
                          (void *)&recvvec[0],messagesize,MPI_CHAR,
                          root,_comm);
         assert(_rc == 0);
         return(_rc);
       };