ElmerFoamFSI: ElmerFoamFSI::TestingObject::Test__TransferDisplacementsToFluid
virtual void Test__TransferDisplacementsToFluid (ResultsType & result) inline virtual
Test for fsiCoupling::TrasferDisplacementsToFluid function.
Parameters
result ElmerFoamFSI::TestResults object to store test results.
This function uses simple static problem data to test the transferagent->interpolate function. Displacement vector for solid agent is set to be the value of linear function along the z direction. After interpolation, displacement vector for fluid agent should have received these values (approximately).
Definition at line 818 of file ElmerFoamFSITest.H.
References TestingObject< ResultsType >::__helper(), TestingObject< ResultsType >::componentInterfaceNames, elmeragent::Coordinates(), TestingObject< ResultsType >::fsiCoupler, fsicoupling::getFluidAgent(), fsicoupling::getFluidIntName(), fsicoupling::getRunMode(), fsicoupling::getSolidIntName(), fsicoupling::getStructureAgent(), TestingObject< ResultsType >::global, fsicoupling::Initialize(), fsicoupling::SetRunMode(), fsicoupling::SetVerbLevel(), fsicoupling::TransferDisplacementsToFluid(), and TestingObject< ResultsType >::verblevel.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       double time_final = 0.05;
       double timestep = 2.0e-3;
       int verblevel = 3;
       bool works = true;
       int IntDir;
       // Copying the SimpleStatic data using getinputdata() helper function.
       bool work =__helper();
       std::string fluidDir;
       std::string simStaticDir;
       fluidDir = IRAD::Sys::CWD() + "/SimpleStatic/fluid";
       simStaticDir = IRAD::Sys::CWD() + "/SimpleStatic";
       if(!(IRAD::Sys::FILEEXISTS(fluidDir)||(IRAD::Sys::FILEEXISTS(simStaticDir)))){
         std::cout << "SimpleStatic / fluid Folders do not exists!" << std::endl;
         works = false;
         result.UpdateResult("fsiCoupler:Works",works);
         return;
       }
       else{
         IntDir = IRAD::Sys::ChDir(simStaticDir);
         if(IntDir == -1){
           std::cout << "GetInputData Error: Could not change directory to "
                     << fluidDir << ". Exiting (fail). " << std::endl;
           works = false;
           result.UpdateResult("fsiCoupler:Works",works);
         }
         std::system("chmod 755 Allclean Allrun AllrunPar makeLinks makeSerialLinks removeSerialLinks");
         std::system("./Allclean");
         std::system("./Allrun");
         IntDir = IRAD::Sys::ChDir(fluidDir);
         if(IntDir == -1){
           std::cout << "GetInputData Error: Could not change directory to "
                     << fluidDir << ". Exiting (fail). " << std::endl;
           works = false;
           result.UpdateResult("fsiCoupler:Works",works);
         }
       }
       fsicoupling fsiCoupler(global);
       std::string fluidSolverName("OpenFoamFSI");
       std::string solidSolverName("ElmerCSC");
       std::string transferServiceName("SurfX");
       std::string runMode("1");
       std::cout << "COM loading all this junks" << std::endl;
       COM_load_module(fluidSolverName.c_str(),"FluidsComponentInterface");
       COM_load_module(solidSolverName.c_str(),"StructuresComponentInterface");
       COM_load_module("SurfUtil","SurfUtil");
       COM_load_module("Simpal","Simpal");
       std::vector<std::string> componentInterfaceNames;
       componentInterfaceNames.push_back("FluidsComponentInterface");
       componentInterfaceNames.push_back("StructuresComponentInterface");
       componentInterfaceNames.push_back("TransferInterface");
       componentInterfaceNames.push_back("SurfUtil");
       componentInterfaceNames.push_back("Simpal");
       fsiCoupler.SetRunMode(runMode);
       fsiCoupler.SetVerbLevel(verblevel);
       fsiCoupler.Initialize(componentInterfaceNames, time_final, timestep);
       // Mimicing FsiCoupler::run, intializing variables, etc.
       int innerCount = 0;
       int maxSubSteps = 1000;
       int dumpinterval = 1;
       int systemStep = 0;
           double *fluidDisp1 = NULL;
           double *fluidDisp2 = NULL;
           double *solidDisp1 = NULL;
           double *solidDisp2 = NULL;
       // Get the displacement vector values for both solid and fluid domain.
           std::string fluidsCoordinateName(fsiCoupler.getFluidIntName()+".solidDisplacement");
           std::string solidsCoordinateName(fsiCoupler.getSolidIntName()+".Displacements");
           COM_get_array(fluidsCoordinateName.c_str(),(fsiCoupler.getFluidAgent())->PaneID(),&fluidDisp1);
           COM_get_array(solidsCoordinateName.c_str(),(fsiCoupler.getStructureAgent())->PaneID(),&solidDisp1);
       // Setting Y-component of the displacement vector to be the linear function displacement
       // along z direction throughout nodes
       for(int i = 0; i <fsiCoupler.getStructureAgent()->Coordinates().size()/3; i++){
         solidDisp1[3*i+1] = fsiCoupler.getStructureAgent()->Coordinates()[3*i+2];
       }
           if(!(fsiCoupler.getRunMode())){
                 fsiCoupler.TransferDisplacementsToFluid(fsiCoupler.getStructureAgent(),fsiCoupler.getFluidAgent());
           }
       // After transferDisplacementToFluids, get displacement vectors for both agents to compare
       COM_get_array(fluidsCoordinateName.c_str(),(fsiCoupler.getFluidAgent())->PaneID(),&fluidDisp2);
       COM_get_array(solidsCoordinateName.c_str(),(fsiCoupler.getStructureAgent())->PaneID(),&solidDisp2);
       double totalFluidDis, totalSolidDis = 0;
       // Calculate the total displacements for solid displacements and fluid displacements after transfer
       for(int i=0; i < fsiCoupler.getStructureAgent()->Coordinates().size()/3; i++){
         totalFluidDis += fluidDisp2[3*i+1];
         totalSolidDis += solidDisp2[3*i+1];
       }
       std::cout << "total fluid dis = " << totalFluidDis << std::endl;
       std::cout << "total solid dis = " << totalSolidDis << std::endl;
       // Using Error % = (Experimented value - Theoretical value) / Theoretical value
       double totalError = (totalFluidDis - totalSolidDis) / totalSolidDis;
       // If the error % is greater than 5%, let's call it a fail.
       std::cout << "total error = " << totalError << std::endl;
       if(totalError  >= .05) works = false;
       result.UpdateResult("TransferDisplacementsToFluid:Works",works);
     }