ElmerFoamFSI: ElmerModuleDriver::TestingObject::Test__ElmerUnitTests
virtual void Test__ElmerUnitTests (ResultsType & result) inline virtual
Definition at line 415 of file ElmerModuleDriverTest.H.
References TestingObject< ResultsType >::GetInputData().
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       std::cout << "Running Test__ElmerUnitTests" << std::endl;
       int IntDir;
       std::string OrgDir, TestDir;
       bool ItAllWorks = true;
       // Arrays that old data for check *******************************************
       double CoordCheck[15][3] =
           { {2.2999999999999998, 0.19296300000000000, 0.0000000000000000},
             {2.2999999999999998, 0.00000000000000000, 0.0000000000000000},
             {2.2999999999999998, 0.39523399999999997, 0.0000000000000000},
             {2.2999999999999998, 0.60476600000000003, 0.0000000000000000},
             {2.2999999999999998, 0.80703700000000000, 0.0000000000000000},
             {2.2999999999999998, 1.00000000000000000, 0.0000000000000000},
             {2.3585799999999999, 1.14142000000000010, 0.0000000000000000},
             {2.5000000000000000, 1.20000000000000000, 0.0000000000000000},
             {2.6414200000000001, 1.14142000000000010, 0.0000000000000000},
             {2.7000000000000002, 1.00000000000000000, 0.0000000000000000},
             {2.7000000000000002, 0.80703700000000000, 0.0000000000000000},
             {2.7000000000000002, 0.60476600000000003, 0.0000000000000000},
             {2.7000000000000002, 0.39523399999999997, 0.0000000000000000},
             {2.7000000000000002, 0.19296300000000000, 0.0000000000000000},
             {2.7000000000000002, 0.00000000000000000, 0.0000000000000000} };
       int ConnCheck[14][2] =
            { {1,2}, {3,1}, {4,3}, {5,4}, {6,5}, {7,6}, {8,7}, {9,8}, {10,9},
            {11,10}, {12,11}, {13,12}, {14,13}, {15,14} };
       // Getting Input data********************************************************
       //***************************************************************************
       //Call GetInputData to copy input test data to temp directory for running tests.
       std::string suffix = "/share/Testing/test_data/FSIobstacle";
       //Make path for directory to run the test in.
       TestDir = IRAD::Sys::CWD() + "/UnitTestData";
       IntDir = GetInputData(suffix, TestDir);
       //Check if GetInputData exited correctly.
       if(IntDir != 0){
         std::cout << "ElmerUnitTests Error: GetInputData call failed."
                   << std::endl;
         result.UpdateResult("ElmerUnitTests:Run", false);
         return;
       }
       //Check if TestDir directory (from GetInputData) exists in current directory
       if(!IRAD::Sys::FILEEXISTS(TestDir)){
         std::cout << "ElmerUnitTests Error: Could not find directory, "
                   << TestDir << ", for running tests." << std::endl;
         result.UpdateResult("ElmerUnitTests:Run", false);
         return;
       }
       //Save original directory name for later
       OrgDir = IRAD::Sys::CWD();
       //Change directories to TestDir directory for running
       IntDir = IRAD::Sys::ChDir(TestDir);
       if(IntDir == -1){
         std::cout << "ElmerUnitTests Error: Could not change directories to "
                   << TestDir << "." << std::endl;
         result.UpdateResult("ElmerUnitTests:Run", false);
         return;
       }
       //load Elmer module**********************************************************
       //***************************************************************************
       COM_LOAD_MODULE_STATIC_DYNAMIC( ElmerCSC, "Window1");
       bool load_unload = true;
       //Get Winodw handle
       int h=COM_get_window_handle("Window1");
       if(h <= 0){
         std::cout << " After loading, COM_get_window_handle(\"Window1\") returns "
                   << h << std::endl;
         load_unload=false;
         std::cout << "ElmerUnitTests Error: Could not get window handle."
                   << "." << std::endl;
         result.UpdateResult("LoadSolverModule:Works",false);
         result.UpdateResult("ElmerUnitTests:Run", false);
         return;
       }
       else
         result.UpdateResult("LoadSolverModule:Works",true);
       // Get Initialize function handle and call Function
       int init_handle = COM_get_function_handle("Window1.Initialize");
       bool init_func = (init_handle > 0);
       int init_runs = 0;
       int verb=3;
       std::cout << "init = " << init_handle << std::endl;
       if(init_handle){
         //Call the function
         COM_call_function(init_handle, &init_runs, &verb);
       }
       else{
         std::cout << "InitializeRuns Error: Could not get function handle."
                   << "." << std::endl;
         result.UpdateResult("Initialize:Runs", false);
         return;
       }
       //Check if function changed value of runs properly
       if(init_runs == 1){
         result.UpdateResult("Initialize:Runs", true);
       }
       else{
         result.UpdateResult("Initialize:Runs", false);
         ItAllWorks = false;
       }
       // Check coordinate values
       int coord_handle = COM_get_dataitem_handle("Window1.nc");
       int CoordSize=0;
       bool coordData = (coord_handle > 0);
       bool coordCorrect = true;
       std::cout << "coord_handle = " << coord_handle << std::endl;
       if(coordData){
         COM_get_size("Window1.nc",11,&CoordSize);
         if(CoordSize != 15){
           std::cout << "ElmerUnitTests Error:"
                     << " Coord array is incorrect size!" << std::endl;
           ItAllWorks = false;
           coordCorrect = false;
         }
         else{
           // Get the FSI mesh from the structures solver and print
           // it out to check
           double* Coord;
           COM_get_array("Window1.nc",11,&Coord);
           std::cout << "Coord:" << std::endl;
           for(int i=0; i < CoordSize; i++){
             for(int j=0; j < 3; j++){
               std::cout << Coord[i*3+j] << " ";
               if(fabs(CoordCheck[i][j] - Coord[i*3+j]) > 1.0e-12){
                 ItAllWorks = false;
                 coordCorrect = false;
               }
             }
             std::cout << std::endl;
           }
         }
         result.UpdateResult("CoordinateData:Correct", coordCorrect);
         result.UpdateResult("CoordinateData:Registered", true);
       }
       else{
         result.UpdateResult("CoordinateData:Registered", false);
         result.UpdateResult("CoordinateData:Correct", false);
         ItAllWorks = false;
       }
       // Check connectivity values
       bool connCorrect = true;
       int ConnSize = 0;
       int* Conn = NULL;
       // Get the FSI mesh from the structures solver
       COM_get_array("Window1.:b2:",11,&Conn);
       if(Conn){
         // Get the FSI mesh size from the structures solver
         COM_get_size("Window1.:b2:",11,&ConnSize);
         if(ConnSize != 14){
           std::cout << "ElmerUnitTests Error:"
                     << " Conn array is incorrect size!" << std::endl;
           ItAllWorks = false;
           connCorrect = false;
         }
         else{
           // check the values
           std::cout << "Conn:" << std::endl;
           for(int i=0; i < ConnSize; i++){
             for(int j=0; j < 2; j++){
               std::cout << Conn[i*2+j] << " ";
               if( (ConnCheck[i][j] - Conn[i*2+j]) != 0){
                 ItAllWorks = false;
                 connCorrect = false;
               }
             }
             std::cout << std::endl;
           }
         }
         result.UpdateResult("ConnectivityData:Correct", connCorrect);
         result.UpdateResult("ConnectivityData:Registered", true);
       }
       else{
         result.UpdateResult("ConnectivityData:Registered", false);
         result.UpdateResult("ConnectivityData:Correct", false);
         ItAllWorks = false;
       }
       // Check load registration & initialization
       double* Loads = NULL;
       int LoadsSize = 0;
       bool loadsRegistered = true, loadsInitialized = true;
       // Get the FSI loads from the structures solver
       COM_get_array("Window1.Loads",11,&Loads);
       if(Loads){
         std::cout << "Loads not NULL" << std::endl;
         // Get the FSI load size from the structures solver
         COM_get_size("Window1.Loads",11,&LoadsSize);
         if(LoadsSize != 15){
           std::cout << "ElmerUnitTests Error:"
                     << " Loads array is incorrect size!" << std::endl;
           ItAllWorks = false;
           loadsInitialized = false;
         }
         else{
           // check the values
           for(int i=0; i < LoadsSize; i++){
             for(int j=0; j < 3; j++){
               if(fabs(Loads[i*3 + j]) > 1.0e-12){
                 loadsInitialized = false;
                 ItAllWorks = false;
               }
             }
           }
         }
       }
       else{
         std::cout << "Loads are NULL" << std::endl;
         loadsRegistered = false;
         loadsInitialized = false;
         ItAllWorks = false;
       }
       result.UpdateResult("LoadData:Registered", loadsRegistered);
       result.UpdateResult("LoadData:Initialized", loadsInitialized);
       // Get TimeStepper function handle and call Function
       // Arrays that hold disp data for check *********************************
       double DispTime1[15][3] =
           {{  7.1605980866005031E-002,   3.5788052113870331E-002,   0.0000000000000000},
            { -6.8871825230548747E-026,  -6.7515261027908644E-026,   0.0000000000000000},
            {  0.16559117138148402    ,   6.1512134471618775E-002,   0.0000000000000000},
            {  0.27105716643234351    ,   7.0647177803958988E-002,   0.0000000000000000},
            {  0.37408733220172607    ,   6.6788253467455649E-002,   0.0000000000000000},
            {  0.46975382688278072    ,   5.5232228766620040E-002,   0.0000000000000000},
            {  0.53059533135003267    ,   1.7568173579321143E-002,   0.0000000000000000},
            {  0.54088718131665003    ,  -5.0723278288525193E-002,   0.0000000000000000},
            {  0.49733519851449115    ,  -0.10431856777439819    ,   0.0000000000000000},
            {  0.42342243323024942    ,  -0.11544236710979815    ,   0.0000000000000000},
            {  0.32858350010626158    ,  -9.6940873722311166E-002,   0.0000000000000000},
            {  0.22913389910789400    ,  -7.6890455177259009E-002,   0.0000000000000000},
            {  0.13256597264490513    ,  -5.4789959945688596E-002,   0.0000000000000000},
            {  5.4547795662606154E-002,  -2.9570884780950012E-002,   0.0000000000000000},
            { -6.8871825230548747E-026,  -6.7515261027908632E-026,   0.0000000000000000}};
       double DispTime2[15][3] =
            {{  7.8382763777475994E-002,    3.7159701956680058E-002,   0.0000000000000000},
             { -1.3908554346559520E-053,   -1.3634598387444821E-053,   0.0000000000000000},
             {  0.17746729339780631    ,    6.3782065644847119E-002,   0.0000000000000000},
             {  0.28589059231716707    ,    7.3724507560836025E-002,   0.0000000000000000},
             {  0.39007099539893136    ,    7.0647599706400666E-002,   0.0000000000000000},
             {  0.48577572075292708    ,    5.9851545424915178E-002,   0.0000000000000000},
             {  0.54619785916039254    ,    2.2562624600359866E-002,   0.0000000000000000},
             {  0.55515630051911513    ,   -4.5683794688744256E-002,   0.0000000000000000},
             {  0.51164185034902454    ,   -9.8434990773815095E-002,   0.0000000000000000},
             {  0.43876588136755668    ,   -0.10966508014917155    ,   0.0000000000000000},
             {  0.34337311330396592    ,   -9.2057033659364212E-002,   0.0000000000000000},
             {  0.24185886373003795    ,   -7.3235312951635573E-002,   0.0000000000000000},
             {  0.14168683127415216    ,   -5.2598213602584751E-002,   0.0000000000000000},
             {  5.9082767678702033E-002,   -2.8938645702423191E-002,   0.0000000000000000},
             { -1.3908554346559520E-053,   -1.3634598387444801E-053,   0.0000000000000000}};
       //*********************************************************************
       int runs_handle = COM_get_function_handle("Window1.Run");
       bool runs_func = (runs_handle > 0);
       bool DispCorrect = true;
       int runs_runs = 0;
       double time1 =  8.0;
       double time2 = 100.0;
       double* Disp = NULL;
       int DispSize = 0;
       COM_get_array("Window1.Displacements",11,&Disp);
       std::cout << "runs = " << runs_handle << std::endl;
       if(runs_handle){
         //Call the run function for Time1
         if(Loads){
            std::cout << "Changing load values" << std::endl;
            for(int i=0; i < LoadsSize; i++){
               for(int j=0; j < 3; j++){
                  Loads[i*3 + j] = double(i*3 + j);
                  std::cout << Loads[i*3 + j] << " ";
               }
               std::cout << std::endl;
            }
         }
         COM_call_function(runs_handle, &runs_runs, &time1);
       }
       else{
         std::cout << "TimeStepperRuns Error: Could not get function handle."
                   << "." << std::endl;
         result.UpdateResult("TimeStepper:Runs", false);
         return;
       }
       //Check if function changed value of runs properly
       if(runs_runs > 0){
         result.UpdateResult("TimeStepper:Runs", true);
       }
       else{
         result.UpdateResult("TimeStepper:Runs", false);
         ItAllWorks = false;
       }
       // Check reigstration of displacement data
       if (Disp){
          result.UpdateResult("DisplacementData:Registered", true);
          // Get the FSI displacement size from the structures solver
          COM_get_size("Window1.Displacements",11,&DispSize);
          if(DispSize != 15){
            std::cout << "ElmerUnitTests Error:"
                      << " Disp array is incorrect size!" << std::endl;
            ItAllWorks = false;
            DispCorrect = false;
          }
       }
       else{
         result.UpdateResult("DisplacementData:Registered", false);
         DispCorrect = false;
         ItAllWorks = false;
       }
       // Check values of displacements after Run func @ Time1
       if (Disp && runs_handle && DispCorrect){
         std::cout << "Checking Displacements Time 1 (" << time1 << ")" << std::endl;
         for(int i=0; i < DispSize; i++){
            for(int j=0; j < 3; j++){
               std::cout << Disp[i*3+j] << " ";
               if(fabs(DispTime1[i][j] - Disp[i*3+j]) > 1.0e-12){
                 ItAllWorks = false;
                 DispCorrect = false;
               }
            }
            std::cout << std::endl;
         }
         //Change the load values again for testing
         if(Loads){
            std::cout << "Changing load values" << std::endl;
            for(int i=0; i < LoadsSize; i++){
               for(int j=0; j < 3; j++){
                  Loads[i*3 + j] = double(i*3 + j) + 1.0;
                  std::cout << Loads[i*3 + j] << " ";
               }
               std::cout << std::endl;
            }
         }
         //Call the run function for Time2
         int runs_runs2 = 0;
         COM_call_function(runs_handle, &runs_runs2, &time2);
         // Check values of displacements after Run func @ Time1
         std::cout << "Checking Displacements Time 2 (" << time2 << ")" << std::endl;
         for(int i=0; i < DispSize; i++){
            for(int j=0; j < 3; j++){
               std::cout << Disp[i*3+j] << " ";
               if(fabs(DispTime2[i][j] - Disp[i*3+j]) > 1.0e-12){
                 ItAllWorks = false;
                 DispCorrect = false;
               }
            }
            std::cout << std::endl;
         }
         //Check if function changed value of runs properly in Loads function
         if(runs_runs > 1 && runs_runs2 > 1){
           result.UpdateResult("TimeLoads:Runs", true);
         }
         else{
           std::cout << "runs_runs = " << runs_runs << std::endl;
           std::cout << "runs_runs2 = " << runs_runs2 << std::endl;
           result.UpdateResult("TimeLoads:Runs", false);
           ItAllWorks = false;
         }
       }
       result.UpdateResult("DisplacementData:Correct", DispCorrect);
       // Get Finalize function handle and call Function
       int final_handle = COM_get_function_handle("Window1.Finalize");
       bool final_func = (final_handle > 0);
       int final_runs = 0;
       std::cout << "final = " << final_handle << std::endl;
       if(final_handle){
         //Call the function
         COM_call_function(final_handle, &final_runs);
       }
       else{
         std::cout << "FinalizeRuns Error: Could not get function handle."
                   << "." << std::endl;
         result.UpdateResult("Finalize:Runs", false);
         return;
       }
       //Check if function changed value of runs properly
       if(final_runs == 1){
         result.UpdateResult("Finalize:Runs", true);
       }
       else{
         result.UpdateResult("Finalize:Runs", false);
         ItAllWorks = false;
       }
       //Unload Elmer module********************************************************
       //***************************************************************************
       COM_UNLOAD_MODULE_STATIC_DYNAMIC( ElmerCSC, "Window1");
       //Make sure module unloaded
       h=COM_get_window_handle("Window1");
       if(h > 0){
         std::cout << "After unloading, COM_get_window_handle(\"Window1\") returns "
                   << h << std::endl;
         load_unload=false;
         std::cout << "ElmerUnitTests Error: Did not properly unload module."
                   << "." << std::endl;
         result.UpdateResult("ElmerUnitTests:Run", false);
         result.UpdateResult("UnloadSolverModule:Works",false);
         return;
       }
       else
         result.UpdateResult("UnloadSolverModule:Works",true);
       //Change directories out of TestDir directory back to original directory
       IntDir = IRAD::Sys::ChDir(OrgDir);
       if(IntDir == -1){
         std::cout << "ElmerUnitTests Error: Could not change directories to "
                   << OrgDir << "." << std::endl;
         result.UpdateResult("ElmerUnitTests:Run", false);
         return;
       }
       result.UpdateResult("ElmerUnitTests:Run", ItAllWorks);
     }