ElmerFoamFSI: Simple_manifold_2::is_ghost_element
bool is_ghost_element (int eid) const inline
Is the element incident on the give edge a ghost element?
Definition at line 609 of file Simple_manifold_2.h.
References _is_str, _isghostelmt, and _maxsize_real_elmts.
Referenced by get_next_edge_interior(), get_next_ghost_edge_interior(), get_next_real_edge_interior(), get_opposite_ghost_edge(), get_opposite_ghost_edge_interior(), get_opposite_real_edge_interior(), get_prev_edge_interior(), get_prev_ghost_edge_interior(), and get_prev_real_edge_interior().
{
     if ( !_is_str) // Unstructured mesh
       return eid > _maxsize_real_elmts;
     else // Structured
       return !_isghostelmt.empty() && _isghostelmt[ eid-1];
   }