ElmerFoamFSI: ElmerModuleDriver::TestingObject::RunTest
virtual void RunTest (const std::string & name, ResultsType & result) inline virtual
Runs a test specified by name.
Parameters
name String name of the test to run.
result ElmerModuleDriver::TestResults object to store test results.
Reimplemented from TestingObject< ResultsType >.
Definition at line 1119 of file ElmerModuleDriverTest.H.
References TestingObject< ResultsType >::Epilogue(), TestingObject< ResultsType >::Prologue(), TestingObject< ResultsType >::Test__ElasticBeam3D_LoadFunction(), TestingObject< ResultsType >::Test__ElmerUnitTests(), TestingObject< ResultsType >::Test__ExampleFunction(), TestingObject< ResultsType >::Test__MidPointQuadrature(), and TestingObject< ResultsType >::Test__TrapezoidQuadrature().
Referenced by TestingObject< ResultsType >::ProcessTests(), and ElmerModuleDriver::Test().
     {
       Prologue();
       if(name == "ExampleFunction")
         Test__ExampleFunction(result);
       else if(name == "TrapezoidQuadrature")
         Test__TrapezoidQuadrature(result);
       else if(name == "MidPointQuadrature")
         Test__MidPointQuadrature(result);
       else if(name == "ElmerUnitTests")
         Test__ElmerUnitTests(result);
       else if(name == "ElasticBeam3D_LoadFunction")
         Test__ElasticBeam3D_LoadFunction(result);
       Epilogue();
     }