ElmerFoamFSI: SolverUtils::Mesh::BSExtent::CreateUnstructuredMesh
void CreateUnstructuredMesh (Connectivity & conn) inline
Definition at line 200 of file BSMesh.H.
References BSExtent< T >::_N, BSExtent< T >::_nd, Connectivity::AddElement(), BSExtent< T >::GetFlatIndices(), and Connectivity::Sync().
     {
       // get coordinates of lower left hand coordinates:
       // istart to (iend - 1), or istart
       // jstart to (jend - 1), or jstart
       // kstart to (kend - 1), or kstart
       assert(_nd == 3);
       BSExtent<T> lowerleft(*this);
       int mesh_nd = 3;
       for(int i = 0;i < 3;i++){
         if(_N[i] > 1)
           lowerleft[i][1]--;
         else
           mesh_nd--;
       }
       assert(mesh_nd > 1);
       std::vector<T> indices;
       GetFlatIndices(lowerleft,indices);
       IndexType offset = (_N[0] > 1 ? _N[0] : _N[1]);
       IndexType planeoffset = (mesh_nd == 2 ? 0 : offset*_N[1]);
       IndexType number_of_elements = indices.size();
       for(IndexType i = 0;i < number_of_elements;i++){
         std::vector<IndexType> element;
         element.push_back(indices[i]);
         element.push_back(indices[i]+1);
         element.push_back(indices[i]+1+offset);
         element.push_back(indices[i]+offset);
         if(planeoffset > 0){
           element.push_back(indices[i]+planeoffset);
           element.push_back(indices[i]+1+planeoffset);
           element.push_back(indices[i]+planeoffset+offset+1);
           element.push_back(indices[i]+planeoffset+offset);
         }
         conn.AddElement(element);
       }
       conn.Sync();
     };