ElmerFoamFSI: ElmerFoamFSI::TestingObject::Test__ElmerModuleLoad
virtual void Test__ElmerModuleLoad (ResultsType & result) inline virtual
Definition at line 291 of file ElmerFoamFSITest.H.
References COM_get_window_handle(), COM_LOAD_MODULE_STATIC_DYNAMIC, and COM_UNLOAD_MODULE_STATIC_DYNAMIC.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       std::cout << "Running Test__ElmerModuleLoad" << std::endl;
       // load Elmer module
       std::cout << "Loading Elmer Module" << std::endl;
       COM_LOAD_MODULE_STATIC_DYNAMIC(ElmerCSC, "ElmerModule");
       bool works = false;
       // get window handle
       int h=COM_get_window_handle("ElmerModule");
       if(h <= 0){
         std::cout << " After loading, COM_get_window_handle(\"ElmerModule\") returns "
                   << h << std::endl;
         std::cout << "ModuleLoadUnload Error: Could not get window handle."
                   << std::endl;
       }
       else{
         works=true;
         std::cout << "Elmer Module Loaded" << std::endl;
       }
       result.UpdateResult("LoadElmerModule:Works",works);
       // unload Elmer Module
       std::cout << "Unloading Elmer Module" << std::endl;
       COM_UNLOAD_MODULE_STATIC_DYNAMIC(ElmerCSC, "ElmerModule");
       works=false;
       // make sure module unloaded
       h=COM_get_window_handle("ElmerModule");
       if(h > 0){
         std::cout << "After unloading, COM_get_window_handle(\"ElmerModule\") returns "
                   << h << std::endl;
         std::cout << "ModuleLoadUnload Error: Did not properly unload module."
                   << std::endl;
       }
       else{
         works=true;
         std::cout << "Elmer Module Unloaded" << std::endl;
       }
       result.UpdateResult("UnloadElmerModule:Works",works);
       return;
     }