ElmerFoamFSI: DataItem::stride
int stride () const inline
Obtain the stride of the dataitem in base datatype.
Definition at line 210 of file DataItem.hpp.
References _status, _strd, and root().
Referenced by is_staggered(), Element_node_vectors_k_const< Value >::set(), and Element_vectors_k_const< Value >::set().
 { return _status?_strd:root()->_strd; }