ElmerFoamFSI: SolverUtils::TransferObjectPar::Overlay
int Overlay (const std::string & w1, const std::string & w2, const std::string & w1FnameHdf, const std::string & w2FnameHdf) inline
Definition at line 443 of file InterfaceLayer.H.
References TransferObjectPar::_comm, TransferObjectPar::_rank, SolverUtils::COM_call_function(), COM_delete_window(), COM_get_dataitem_handle(), COM_set_default_communicator(), COM_window_init_done(), TransferObjectPar::overlayhandle, TransferObjectPar::read_file_rocin(), TransferObjectPar::readhandle, TransferObjectPar::win1, TransferObjectPar::win2, and TransferObjectPar::writehandle.
Referenced by fsicouplingpar::Initialize().
     {
       win1 = w1;
       win2 = w2;
       // waiting for all processes to finish
       MPI_Barrier(_comm);
       // generating and writing common refinement
       if (_rank == 0) {
          COM_set_default_communicator(MPI_COMM_NULL);
          std::string tmpW1 = w1 + "tmp";
          std::string tmpW2 = w2 + "tmp";
          read_file_rocin( w1FnameHdf.c_str(), tmpW1, MPI_COMM_SELF);
          COM_window_init_done(tmpW1);
          read_file_rocin( w2FnameHdf.c_str(), tmpW2, MPI_COMM_SELF);
          COM_window_init_done(tmpW2);
          int mesh1 = COM_get_dataitem_handle((tmpW1+".mesh").c_str());
          int mesh2 = COM_get_dataitem_handle((tmpW2+".mesh").c_str());
          if(mesh1 <= 0 || mesh2 <= 0)
            return(-1);
          COM_call_function(overlayhandle, &mesh1, &mesh2);
          const char *format = "HDF";
          COM_call_function(writehandle, &mesh1, &mesh2, w1.c_str(), w2.c_str(), format);
          COM_delete_window(tmpW1);
          COM_delete_window(tmpW2);
          COM_set_default_communicator(_comm);
       }
       // waiting for the overlay step to finish
       MPI_Barrier(_comm);
       // reading overlay
       int itm1 = COM_get_dataitem_handle((w1+".mesh").c_str());
       int itm2 = COM_get_dataitem_handle((w2+".mesh").c_str());
       if(itm1 <= 0 || itm2 <= 0)
         return(-1);
       COM_call_function(readhandle, &itm1, &itm2, &_comm, w1.c_str(), w2.c_str(), "HDF");
       return(0);
     };