ElmerFoamFSI: ElmerFoamFSI::TestingObject::Test__FsiCoupler
virtual void Test__FsiCoupler (ResultsType & result) inline virtual
Test the functionality of the fsiCoupler.
Definition at line 695 of file ElmerFoamFSITest.H.
References TestingObject< ResultsType >::componentInterfaceNames, TestingObject< ResultsType >::fsiCoupler, fsicoupling::getVariable(), fsicoupling::Initialize(), and TestingObject< ResultsType >::Test__fsiCouplerAgentsInitialize().
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       double time_final = 0.05;
       double timestep = 2.0e-3;
       bool works = true;
       //Call the Agents Initialize function above
       //as well as the Initialize function of fsiCoupler
       std::cout << "Initalizing..." << std::endl;
       Test__fsiCouplerAgentsInitialize();
       fsiCoupler.Initialize(componentInterfaceNames, time_final, timestep);
       std::cout << "Initialize Completed!" << std::endl;
       //test to make sure that classInterfaceNames are populated
       //correctly to match componentInterfaceNames
       std::vector<std::string> classInterfaceNames;
       classInterfaceNames =  fsiCoupler.getVariable();
       for(int i = 0; i < componentInterfaceNames.size(); i++){
         if(componentInterfaceNames.at(i) != classInterfaceNames.at(i)){
           works = false;
           break;
         }
       }
       result.UpdateResult("fsiCoupler:Works",works);
     }