ElmerFoamFSI: fsicouplingpar::writeWin
virtual void writeWin (const char * winName, std::string timeMark, std::string & wFnameHdf) inline virtual
Definition at line 226 of file FsiCouplingPar.H.
References COM_call_function(), COM_get_dataitem_handle(), COM_get_function_handle(), ParallelGlobalObj< CommunicatorType, StackType, ErrorType, ProfilerType >::Rank(), and simoutInterfaceName.
Referenced by Initialize().
   {
      int OUT_set = COM_get_function_handle( (simoutInterfaceName + ".set_option").c_str());
      int OUT_write = COM_get_function_handle( (simoutInterfaceName + ".write_dataitem").c_str());
      int OUT_write_ctrl = COM_get_function_handle( (simoutInterfaceName + ".write_rocin_control_file").c_str());
      std::string win_out_pre( winName);
      win_out_pre.append(".");
      int OUT_all = COM_get_dataitem_handle((win_out_pre+"all").c_str());
      std::stringstream ss;
      ss.clear();
      ss.str("");
      ss << "_proc_"
         << Rank();
      std::string hdf_fname, ctrl_fname;
      hdf_fname = (std::string)winName +"_window" + ss.str();
      ctrl_fname = (std::string)winName + "_time_" + timeMark +".txt";
      COM_call_function( OUT_set, "format", "HDF4");
      COM_call_function( OUT_write, (hdf_fname + ".hdf").c_str(), &OUT_all, winName, "0000");
      COM_call_function( OUT_write_ctrl, winName, hdf_fname.c_str(), ctrl_fname.c_str());
      wFnameHdf = (std::string)winName +"_window_proc_*.hdf";
   }