ElmerFoamFSI: OpenFoamModuleDriver::TestingObject::Test__LoadUnitTestData
virtual void Test__LoadUnitTestData (ResultsType & result) inline virtual
Definition at line 274 of file OpenFoamModuleDriverTest.H.
References TestingObject< ResultsType >::GetInputData(), and TestingObject< ResultsType >::SourceDirPath.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       std::cout << "Running Test__LoadUnitTestData" << std::endl;
       bool works=false;
       //Call GetInputData to copy input test data to temp directory for running tests.
       std::string suffix = "/share/Testing/test_data/HronTurekFsi";
       std::string dirName = SourceDirPath + suffix;
       //Make path for directory to run the test in.
       std::string TestDir = IRAD::Sys::CWD() + "/UnitTestData";
       int IntDir = GetInputData(dirName, TestDir);
       //Check if GetInputData exited correctly.
       if(IntDir != 0){
         std::cout << "LoadUnitTestData Error: GetInputData call failed."
                   << std::endl;
         result.UpdateResult("LoadUnitTestData:Works", false);
         return;
       }
       //Check if TestDir directory (from GetInputData) exists in current directory
       if(!IRAD::Sys::FILEEXISTS(TestDir)){
         std::cout << "LoadUnitTestData Error: Could not find directory, "
                   << TestDir << ", for running tests." << std::endl;
         result.UpdateResult("LoadUnitTestData:Works", false);
         return;
       }
       //Save original directory name for later
       std::string OrgDir = IRAD::Sys::CWD();
       //Change directories to TestDir directory for running
       IntDir = IRAD::Sys::ChDir(TestDir);
       if(IntDir == -1){
         std::cout << "LoadUnitTestData Error: Could not change directories to "
                   << TestDir << "." << std::endl;
         result.UpdateResult("LoadUnitTestData:Works", false);
         return;
       }
       result.UpdateResult("LoadUnitTestData:Works", true);
       IntDir = IRAD::Sys::ChDir(OrgDir);
       return;
     }