ElmerFoamFSI: SolverUtils::Mesh::BSExtent::GetFlatIndices
void GetFlatIndices (const BSExtent< T > & extent, std::vector< T > & indices) inline
Definition at line 140 of file BSMesh.H.
References BSExtent< T >::dir_loop(), and BSExtent< T >::ND().
Referenced by BSExtent< T >::CreateUnstructuredMesh().
     {
       int nd = ND();
       indices.resize(0);
       std::vector<T> N(nd);
       std::vector<T> NP(nd);
       for(int nc = 0;nc < nd;nc++){
         N[nc] = (*this)[nc][1] - (*this)[nc][0] + 1;
         NP[nc] = (nc == 0 ? 1 : N[nc-1] * NP[nc-1]);
       }
       NP[0] = 0;
       dir_loop(nd,0,0,N,NP,extent,indices);
     };