ElmerFoamFSI: fsicouplingpar::TestTransfer
void TestTransfer () inline
Definition at line 101 of file FsiCouplingPar.H.
References COM_get_array(), openfoamagentpar::Coordinates(), elmeragentpar::Coordinates(), fluidsAgent, fluidsInterfaceName, TransferObjectPar::Interpolate(), openfoamagentpar::PaneID(), elmeragentpar::PaneID(), GlobalObj< StackType, ErrorType, ProfilerType >::StdOut(), structuresAgent, structuresInterfaceName, and transferAgent.
   {
     std::stringstream outString;
     double *fluidCoordinates = NULL;
     double *solidCoordinates = NULL;
     std::string fluidsCoordinateName(fluidsInterfaceName+".nc");
     std::string solidsCoordinateName(structuresInterfaceName+".nc");
     COM_get_array(fluidsCoordinateName.c_str(),fluidsAgent->PaneID(),&fluidCoordinates);
     COM_get_array(solidsCoordinateName.c_str(),structuresAgent->PaneID(),&solidCoordinates);
     int numberFluidNodes = fluidsAgent->Coordinates().size()/3;
     int numberSolidNodes = structuresAgent->Coordinates().size()/3;
     if(!fluidCoordinates || !solidCoordinates){
       outString << "FSICoupling::TestTransfer:Error: Failed to get coordinate arrays. Exiting."
                 << std::endl;
       StdOut(outString.str(),0,true);
       outString.clear();
       outString.str("");
       exit(1);
     }
     double tolerance = 1e-12;
     double maxdiff = 0;
     const std::vector<double> &fluidCoordArray(fluidsAgent->Coordinates());
     const std::vector<double> &structCoordArray(structuresAgent->Coordinates());
     outString << "BEFORE TRANSFER: " << std::endl;
     for(int i = 0; i < numberFluidNodes;i++){
       outString << "F(" << fluidCoordArray[i*3] << "," << fluidCoordArray[i*3+1] << ","
                 << fluidCoordArray[i*3+2] << ")" << std::endl;
     }
     for(int i = 0; i < numberSolidNodes;i++){
       outString << "S(" << structCoordArray[i*3] << "," << structCoordArray[i*3+1] << ","
                 << structCoordArray[i*3+2] << ")" << std::endl;
     }
     StdOut(outString.str(),3,true);
     outString.clear();
     outString.str("");
     transferAgent->Interpolate("coords","coords"); // transfer from structures to fluids the node coordinates
     //transferAgent->Transfer("coords","coords"); // transfer from structures to fluids the node coordinates
     outString << "FLUIDS AFTER TRANSFER: " << std::endl;
     for(int i = 0; i < numberFluidNodes;i++){
       double diff1 = std::abs(fluidCoordinates[i*3] - fluidCoordArray[i*3]);
       double diff2 = std::abs(fluidCoordinates[i*3+1] - fluidCoordArray[i*3+1]);
       double diff3 = std::abs(fluidCoordinates[i*3+2] - fluidCoordArray[i*3+2]);
       double diff = std::sqrt(diff1*diff1 + diff2*diff2 + diff3*diff3);
       if(diff > maxdiff) maxdiff = diff;
       if(diff > tolerance){
         outString << "FSICoupling::TestTransfer: Coordinate transfer tolerance exceeded for node " << i+1
                   << " (" << diff << ")" << std::endl
                   << "(" << fluidCoordinates[i*3] << "," << fluidCoordinates[i*3+1] << "," << fluidCoordinates[i*3+2]
                   << ") : (" << fluidCoordArray[i*3] << "," << fluidCoordArray[i*3+1] << "," << fluidCoordArray[i*3+2]
                   << ")" << std::endl;
       }
     }
     outString << "FSICoupling::TestTransfer: Maximum transferred (s->f) coordinate difference: " << maxdiff << std::endl;
     StdOut(outString.str(),3,true);
     outString.clear();
     outString.str("");
   };