ElmerFoamFSI: IRAD::Global::GlobalObj::StdOut
virtual int StdOut (const std::string & outstr, unsigned char inlev = 0, bool stack = false) inline virtual
Definition at line 400 of file Global.H.
Referenced by ElmerFoamFSI::ExampleProgram::Driver(), ElmerModuleDriver::ExampleProgram::Driver(), ElmerFoamFSI::Driver(), fsicouplingpar::DumpSolution(), fsicoupling::DumpSolution(), fsicouplingpar::Initialize(), fsicoupling::Initialize(), fsicouplingpar::Run(), fsicoupling::Run(), fsicouplingpar::TestTransfer(), fsicoupling::TestTransfer(), fsicoupling::TransferLoadsToStructures(), fsicoupling::TransferPressuresToStructures(), fsicouplingpar::WriteAgentToVTK(), and fsicoupling::WriteAgentToVTK().
       {
         if(_OutStream && _verb_level >= inlev){
           std::string line;
           std::istringstream Istr(outstr);
           while(std::getline(Istr,line)){
             if(stack){
               *_OutStream << _Stack.front() << ": " << line;
             }
             else{
               *_OutStream << (Name().empty() ? "" : std::string(Name()+std::string(": ")))
                           << line;
             }
             *_OutStream << (Istr.good() ? "\n" : "");
           }
         }
         else
           return(1);
         return(0);
       };