ElmerFoamFSI: fsicoupling::Initialize
virtual int Initialize (std::vector< std::string > & componentInterfaceNames, double finalTime, double timeStep) inline virtual
Definition at line 498 of file FsiCoupling.H.
References couplingbase::componentAgents, fluidsAgent, fluidsInterfaceName, GlobalObj< StackType, ErrorType, ProfilerType >::FunctionEntry(), GlobalObj< StackType, ErrorType, ProfilerType >::FunctionExit(), openfoamagent::Initialize(), elmeragent::Initialize(), TransferObject::Overlay(), runMode, simpalInterfaceName, simulationFinalTime, simulationTime, simulationTimeStep, GlobalObj< StackType, ErrorType, ProfilerType >::StdOut(), structuresAgent, structuresInterfaceName, surfUtilInterfaceName, transferAgent, transferInterfaceName, and verblevel.
Referenced by SerialDriverProgram::DriverRun(), TestingObject< ResultsType >::Test__FluidAgentRun(), TestingObject< ResultsType >::Test__FsiCoupler(), TestingObject< ResultsType >::Test__SolidAgentRun(), TestingObject< ResultsType >::Test__TransferDisplacementsToFluid(), and TestingObject< ResultsType >::Test__TransferLoadsToStructures().
{
     FunctionEntry("Initialize");
     std::stringstream outString;
     //Masoud
     outString << "Final Time = " << finalTime << std::endl;
     outString << "Time Step  = " << timeStep << std::endl;
     //Masoud: End
     StdOut(outString.str(),0,true);
     outString.clear();
     outString.str("");
     if(componentInterfaceNames.size() < 2)
       return(1);
     fluidsInterfaceName     = componentInterfaceNames[0];
     structuresInterfaceName = componentInterfaceNames[1];
     transferInterfaceName   = componentInterfaceNames[2];
     surfUtilInterfaceName   = componentInterfaceNames[3];
     simpalInterfaceName     = componentInterfaceNames[4];
     fluidsAgent     = new fluidagent;
     structuresAgent = new solidagent;
     transferAgent   = new transferagent(transferInterfaceName);
     // Initialize the fluids module
     if(runMode != 2)
       fluidsAgent->Initialize(fluidsInterfaceName, verblevel);
     // Initialize the structures module
     if(runMode != 1)
       structuresAgent->Initialize(structuresInterfaceName, verblevel);
     // Initialize the transfer module's common refinement
     if(runMode == 0) {
       transferAgent->Overlay(structuresInterfaceName,fluidsInterfaceName);
       //      TestTransfer();
     }
     //    exit(1);
     componentAgents.resize(2);
     componentAgents[0] = fluidsAgent;
     componentAgents[1] = structuresAgent;
     simulationTime = 0; // ? (restart)
     simulationFinalTime = finalTime;
     simulationTimeStep = timeStep;
     //DumpSolution();
     FunctionExit("Initialize");
     return(0);
   };