ElmerFoamFSI: IRAD::Comm::CommunicatorObject::AllGatherv
int AllGatherv (std::vector< DataType > & sendvec, std::vector< DataType > & recvvec) inline
Definition at line 293 of file COMM.H.
References CommunicatorObject::_AllGatherv(), CommunicatorObject::_nproc, CommunicatorObject::AllGather(), CommunicatorObject::AllReduce(), IRAD::Comm::DTINT, and IRAD::Comm::SUMOP.
       {
         int datasize = sizeof(DataType);
         int mysendcnt = sendvec.size();
         int totalcnt = 0;
         std::vector<int> nsend_all;
         nsend_all.resize(_nproc,0);
         this->AllGather(mysendcnt,nsend_all);
         this->AllReduce(mysendcnt,totalcnt,DTINT,SUMOP);
         recvvec.resize(totalcnt);
         return(_AllGatherv(&sendvec[0],mysendcnt,datasize,&recvvec[0]));
       };