ElmerFoamFSI: SolverUtils::FEM::SolutionData::Create
int Create (const Mesh::UnstructuredMesh & mesh) inline
Definition at line 222 of file FieldData.H.
References UnstructuredMesh::con, SolutionData::data, SolutionData::meta, UnstructuredMesh::nc, Connectivity::Nelem(), and NodalCoordinates::Size().
Referenced by SolverAgent::CreateSoln(), and SolverUtils::CreateSolutionFromPane().
     {
       int all_data_size = 0;
       //      if(meta.empty())
       //        return(-1);
       assert(!meta.empty());
       data.resize(meta.size());
       FEM::SolutionMetaData::iterator mdi = meta.begin();
       Mesh::IndexType number_of_cells = mesh.con.Nelem();
       Mesh::IndexType number_of_nodes = mesh.nc.Size();
       Mesh::IndexType data_index = 0;
       while(mdi != meta.end()){
         // location can be:
         // (s) - solver global
         // (m) - mesh global
         // (c) - mesh cells
         // (n) - mesh nodes
         Mesh::IndexType nitems = ((mdi->loc == 's' || mdi->loc == 'm') ? 1 :
                                    mdi->loc == 'c' ? number_of_cells :
                                    mdi->loc == 'n' ? number_of_nodes :
                                   0);
         // Masoud : commenting out non zero-sized assertion check
         /*
         if(nitems == 0){
           std::cerr << "SolutionData::Create: Error, unknown location: " << mdi->loc << std::endl;
         }
         assert(nitems > 0);
         */
         // Masoud : end
         // Total size will be the number of components (i.e. scalar = 1, vector = 2,3, etc) times
         // the number of items (i.e. number of nodes, elements, etc) times the size of each item
         Mesh::IndexType total_size = nitems * mdi->dsize * mdi->ncomp;
         all_data_size += total_size;
         data[data_index++].Allocate(nitems*mdi->ncomp,mdi->dsize);
         mdi++;
       }
       return(all_data_size);
     };