ElmerFoamFSI: OpenFoamModuleDriver::TestingObject::Process
virtual void Process (ResultsType & result) inline virtual
Definition at line 1356 of file OpenFoamModuleDriverTest.H.
References TestingObject< ResultsType >::Epilogue(), TestingObject< ResultsType >::Prologue(), TestingObject< ResultsType >::Test__LoadUnitTestData(), TestingObject< ResultsType >::Test__ModuleFunctionInitialize(), TestingObject< ResultsType >::Test__ModuleFunctionStepFluid(), TestingObject< ResultsType >::Test__ModuleLoadUnload(), TestingObject< ResultsType >::Test__ModuleMeshRegistration(), and TestingObject< ResultsType >::Test__ModuleSurfaceData().
Referenced by OpenFoamModuleDriver::Test().
{
       Prologue();
       Test__ModuleLoadUnload(result);
       Test__LoadUnitTestData(result);
       Test__ModuleFunctionInitialize(result);
       Test__ModuleMeshRegistration(result);
       Test__ModuleSurfaceData(result);
       Test__ModuleFunctionStepFluid(result);
       Epilogue();
     }