ElmerFoamFSI: SolverUtils::Mesh::MeshUtilityObject::FormConnectivity
int FormConnectivity (const MeshConType type) inline
Definition at line 542 of file Mesh.H.
References MeshUtilityObject::_connectivities, MeshUtilityObject::ECon(), MeshUtilityObject::ENDUAL, Connectivity::Inverse(), and MeshUtilityObject::NC().
Referenced by MeshUtilityObject::GetCon().
       {
         switch(type)
           {
           case ENDUAL:
             //    if(_connectivities[type]){
             //      _connectivities[type]->destroy();
             //    }
             //    else
             //      _connectivities[type] = new Connectivity();
             ECon().Inverse(_connectivities[type],NC().Size());
             break;
           default:
             bool connectivity_known_type = false;
             assert(connectivity_known_type);
             break;
           }
         return(0);
       };