ElmerFoamFSI: KD_tree_3::build
void build (const double * pnts, int np, int maxn = 0) inline
Definition at line 33 of file KD_tree_3.h.
References _bboxes, _maxout, _npnts, _tree, kdtree_bboxes_3(), and kdtree_build_3().
Referenced by KD_tree_3().
{
     assert(np>=0);
     _npnts = np;
     if (maxn) _maxout = maxn; else _maxout = np;
     if (_npnts) {
       _tree = new int[2*_npnts-1];
       _bboxes = new double[12*_npnts-6];
       kdtree_build_3( pnts, _npnts);
       /* Compute bboxes in linear time */
       kdtree_bboxes_3( pnts);
     }
   }