ElmerFoamFSI: Simple_manifold_2::get_incident_edge
Edge_ID get_incident_edge (int vID) const inline
Get the ID of an incident edge within the pane of a given node that originated from the node.
If the vertex is on the pane boundary, it will return a border edge. For isolated nodes, it returns an ID similar to that for a border edge, except that the element ID given will be the index of the isolated node (starting from 1) plus the total number of border edges.
Definition at line 378 of file Simple_manifold_2.h.
References _beIDs, _ieIDs_ghost, _ieIDs_real_or_str, _is_str, _maxsize_real_nodes, _oeIDs_real_or_str, _size_real_borders, _size_rg_borders, COM_assertion, Facet_ID::eid(), get_edge_index(), get_origin(), Facet_ID::is_border(), and is_ghost_node().
{
     Edge_ID eID;
     if ( _is_str || !is_ghost_node( vID))
       eID = _ieIDs_real_or_str[ vID-1];
     else
       eID = _ieIDs_ghost[ vID-_maxsize_real_nodes-1];
     // If the edge is between real and ghost, then return the real edge.
     if ( eID.is_border() && eID.eid()>_size_real_borders &&
          eID.eid()<=_size_real_borders+_size_rg_borders) {
       eID = _oeIDs_real_or_str[ get_edge_index(_beIDs[eID.eid()-1])];
       COM_assertion( get_origin( eID)==vID);
     }
     return eID;
   }