ElmerFoamFSI: SolverUtils::TransferObjectPar::SetVerbosity
void SetVerbosity () inline
Definition at line 490 of file InterfaceLayer.H.
References SolverUtils::COM_call_function(), COM_get_function_handle(), TransferObjectPar::surfxWinName, and TransferObjectPar::verbLevel.
Referenced by TransferObjectPar::TransferObjectPar().
     {
       COM_call_function(COM_get_function_handle((surfxWinName+".set_verbose").c_str()),&verbLevel);
     };