ElmerFoamFSI: ElmerFoamFSI::TestingObject::RunTest
virtual void RunTest (const std::string & name, ResultsType & result) inline virtual
Runs a test specified by name.
Parameters
name String name of the test to run.
result ElmerFoamFSI::TestResults object to store test results.
Reimplemented from TestingObject< ResultsType >.
Definition at line 1871 of file ElmerFoamFSITest.H.
References TestingObject< ResultsType >::Epilogue(), TestingObject< ResultsType >::Prologue(), TestingObject< ResultsType >::Test__ElmerHandlesCheck(), TestingObject< ResultsType >::Test__ElmerModuleLoad(), TestingObject< ResultsType >::Test__ElmerStructures(), TestingObject< ResultsType >::Test__ExampleFunction(), TestingObject< ResultsType >::Test__FluidAgentRun(), TestingObject< ResultsType >::Test__FsiCoupler(), TestingObject< ResultsType >::Test__MidPointQuadrature(), TestingObject< ResultsType >::Test__OFModuleLoad(), TestingObject< ResultsType >::Test__OpenFoamFluids(), TestingObject< ResultsType >::Test__SolidAgentRun(), TestingObject< ResultsType >::Test__TransferDisplacementsToFluid(), TestingObject< ResultsType >::Test__TransferLoadsToStructures(), and TestingObject< ResultsType >::Test__TrapezoidQuadrature().
Referenced by TestingObject< ResultsType >::ProcessTests(), and ElmerFoamFSI::Test().
     {
       Prologue();
       if(name == "ExampleFunction")
         Test__ExampleFunction(result);
       else if(name == "TrapezoidQuadrature")
         Test__TrapezoidQuadrature(result);
       else if(name == "MidPointQuadrature")
         Test__MidPointQuadrature(result);
       else if(name == "ElmerModuleLoad")
         Test__ElmerModuleLoad(result);
       else if(name == "OpenFoamModuleLoad")
         Test__OFModuleLoad(result);
       else if(name == "ElmerHandlesCheck")
         Test__ElmerHandlesCheck(result);
       else if(name == "FsiCoupler")
         Test__FsiCoupler(result);
       else if(name == "TransferDisplacementsToFluid")
         Test__TransferDisplacementsToFluid(result);
       else if(name == "FluidAgentRun")
         Test__FluidAgentRun(result);
       else if(name == "TransferLoadsToStructures")
         Test__TransferLoadsToStructures(result);
       else if(name == "SolidAgentRun")
         Test__SolidAgentRun(result);
       else if(name == "ElmerStructures")
         Test__ElmerStructures(result);
       else if(name == "OpenFoamFluids")
         Test__OpenFoamFluids(result);
       Epilogue();
     }