ElmerFoamFSI: ElmerFoamFSI::TestingObject::Process
virtual void Process (ResultsType & result) inline virtual
Runs all tests implemented by the ElmerFoamFSI::TestingObject.
Parameters
result ElmerFoamFSI::TestResults object to store test results.
Definition at line 1843 of file ElmerFoamFSITest.H.
References TestingObject< ResultsType >::Epilogue(), TestingObject< ResultsType >::Prologue(), TestingObject< ResultsType >::Test__ElmerHandlesCheck(), TestingObject< ResultsType >::Test__ElmerModuleLoad(), TestingObject< ResultsType >::Test__ElmerStructures(), TestingObject< ResultsType >::Test__ExampleFunction(), TestingObject< ResultsType >::Test__FluidAgentRun(), TestingObject< ResultsType >::Test__FsiCoupler(), TestingObject< ResultsType >::Test__MidPointQuadrature(), TestingObject< ResultsType >::Test__OFModuleLoad(), TestingObject< ResultsType >::Test__OpenFoamFluids(), TestingObject< ResultsType >::Test__SolidAgentRun(), TestingObject< ResultsType >::Test__TransferDisplacementsToFluid(), TestingObject< ResultsType >::Test__TransferLoadsToStructures(), and TestingObject< ResultsType >::Test__TrapezoidQuadrature().
Referenced by ElmerFoamFSI::Test().
{
       Prologue();
       Test__ExampleFunction(result);
       Test__TrapezoidQuadrature(result);
       Test__MidPointQuadrature(result);
       Test__ElmerModuleLoad(result);
       Test__OFModuleLoad(result);
       // WK: Start
       Test__ElmerHandlesCheck(result);
       Test__FsiCoupler(result);
       Test__TransferDisplacementsToFluid(result);
       Test__FluidAgentRun(result);
           Test__TransferLoadsToStructures(result);
       Test__SolidAgentRun(result);
       // WK: End
       // NS: Start
       Test__ElmerStructures(result);
       Test__OpenFoamFluids(result);
       // NS: End
       Epilogue();
     }