ElmerFoamFSI: COM::SolverModuleDriver::vtkDump
int vtkDump (double timeMark)
Definition at line 337 of file SolverModuleDriverParallel.C.
References SolverModuleDriver::Conn, SolverModuleDriver::Coord, SolverModuleDriver::Disp, SolverModuleDriver::isFSI, SolverModuleDriver::Loads, SolverModuleDriver::locDisp, SolverModuleDriver::locLoads, SolverModuleDriver::locPress, SolverModuleDriver::myAgent, SolverModuleDriver::myAgentIsInit, SolverModuleDriver::myRank, SolverModuleDriver::nDisp, SolverModuleDriver::nElem, SolverModuleDriver::nElemNodes, SolverModuleDriver::nLoads, SolverModuleDriver::nNodes, SolverModuleDriver::nPress, SolverModuleDriver::Press, SolverModuleDriver::ss, SolverModuleDriver::typeDisp, SolverModuleDriver::typeLoads, SolverModuleDriver::typePress, SolverModuleDriver::updateSolution(), and SolverUtils::WriteVTKToStream().
Referenced by SolverModuleDriver::run().
{
       // only for FSI problems
       if (!isFSI)
          return(0);
       char getDataItemLoc;
       COM_Type getDataItemType;
       std::string getDataItemUnits;
       // creating solverAgent if not yet
       if (!myAgentIsInit) {
           myAgentIsInit = true;
           // put elements into a vector so we can build the solver agent
           std::vector<unsigned int> connVector;
           for (int i=0; i<nElem; ++i) {
             for (int j=0; j<nElemNodes; ++j) {
               connVector.push_back((Conn[i*nElemNodes+j]));
             }
           }
           // make a solverAgent to store our data
           myAgent.Solution().Meta().AddField("time", 's', 1, 8, "s");
           myAgent.Solution().Meta().AddField("endTime", 's', 1, 8, "s");
           myAgent.Mesh().nc.init(nNodes, Coord);
           myAgent.Mesh().con.AddElements(nElem, nElemNodes, connVector);
       }
       // updating datastructures
       updateSolution();
       // displacements
       myAgent.Solution().Meta().AddField("Displacement", locDisp, nDisp,
                                   typeDisp, "");
       // loads
       myAgent.Solution().Meta().AddField("Load", locLoads, nLoads,
                                            typeLoads, "");
       // get pressures
       myAgent.Solution().Meta().AddField("Pressure", locPress, nPress,
                                          typePress, "");
       // create buffers for the actual data
       myAgent.CreateSoln();
       unsigned int nnodes = myAgent.Mesh().nc.NNodes();
       unsigned int nelem = myAgent.Mesh().con.Nelem();
       // reset the buffers to be our own local buffers
       myAgent.Solution().SetFieldBuffer("Displacement", Disp);
       myAgent.Solution().SetFieldBuffer("Load", Loads);
       myAgent.Solution().SetFieldBuffer("Pressure", Press);
       // write initial mesh data out to a VTK file
       std::ofstream Ouf;
       ss.clear();
       ss.str("");
       ss << timeMark
          << "_proc_"
          << myRank;
       std::string filename;
       filename = "fsi_" + ss.str() +".vtk";
       Ouf.open(filename.c_str());
       if(!Ouf){
             std::cerr << "ELMModuleDriver:main: DumpSolution: Error: Could not open output file, "
                       << filename << "." << std::endl;
             return -1;
       }
       std::cout << "Rank #" << myRank
                 << ", ELMModuleDriver:main: WriteVTKToStream for " << timeMark << std::endl;
       SolverUtils::WriteVTKToStream("ELMModule", myAgent, Ouf);
       Ouf.close();
     }