ElmerFoamFSI: ElmerFoamFSI::TestingObject::Test__ElmerHandlesCheck
virtual void Test__ElmerHandlesCheck (ResultsType & result) inline virtual
Definition at line 383 of file ElmerFoamFSITest.H.
References COM_get_dataitem_handle(), COM_get_function_handle(), COM_get_window_handle(), COM_LOAD_MODULE_STATIC_DYNAMIC, and COM_UNLOAD_MODULE_STATIC_DYNAMIC.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       bool works, loadWorks, globWorks, initWorks, runWorks, finWorks, unloadWorks = false;
       std::cout << "Running Test__ElmerHandlesCheck" << std::endl;
       //Loading Elmer Module
       std::cout << "Loading Elmer Module" << std::endl;
       COM_LOAD_MODULE_STATIC_DYNAMIC(ElmerCSC,"ElmerModule");
       //Checking Elmer Module is indeed loaded.
       int ElmerHandle = COM_get_window_handle("ElmerModule");
       if(ElmerHandle <=0){
         std::cout << "After loading, COM_get_window_handle(\"ElmerModule\") returns "
                   << ElmerHandle << std::endl;
         std::cout << "Error : Could not get window handle." << std::endl;
       }
       else{
         loadWorks = true;
         std::cout << "Elmer Module Loaded." << std::endl;
       }
       //Checking the registration of global data.
       int globHandle = COM_get_dataitem_handle("ElmerModule.global");
       if(globHandle <= 0){
         std::cout << "After loading, COM_get_dataitem_handle(\"ElmerModule.global\") returns "
                   << globHandle << std::endl;
         std::cout << "Error : Could not get the data item handle." << std::endl;
       }
       else{
         globWorks = true;
         std::cout << "Global data handle accessed." << std::endl;
       }
       //Checking the ElmerModule function Initialize handle
       int initHandle = COM_get_function_handle("ElmerModule.Initialize");
       if(initHandle <= 0){
         std::cout << "After loading, COM_get_function_handle(\"ElmerModule.Initialize\") returns "
                   << initHandle << std::endl;
         std::cout << "Error : Could not get the Initialize function handle." << std::endl;
       }
       else{
         initWorks = true;
         std::cout << "Initialize function handle accessed." << std::endl;
       }
       //Checking the ElmerModule function Run handle
       int runHandle = COM_get_function_handle("ElmerModule.Run");
       if(runHandle <= 0){
         std::cout << "After loading, COM_get_function_handle(\"ElmerModule.Run\") returns "
                   << runHandle << std::endl;
         std::cout << "Error : Could not get the Run function handle." << std::endl;
       }
       else{
         runWorks = true;
         std::cout << "Run function handle accessed." << std::endl;
       }
       //Checking the ElmerModule function Finalize handle
       int finHandle = COM_get_function_handle("ElmerModule.Finalize");
       if(finHandle <= 0){
         std::cout << "After loading, COM_get_function_handle(\"ElmerModule.Finalize\") returns "
                   << finHandle << std::endl;
         std::cout << "Error : Could not get the Finalize function handle." << std::endl;
       }
       else{
         finWorks = true;
         std::cout << "Finalize function handle accessed." << std::endl;
       }
       //Unloading Elmer Module
       std::cout << "Unloading Elmer Module" << std::endl;
       COM_UNLOAD_MODULE_STATIC_DYNAMIC(ElmerCSC, "ElmerModule");
       //Checking Elmer Module is indeed unloaded.
       ElmerHandle = COM_get_window_handle("ElmerModule");
       if(ElmerHandle > 0){
         std::cout << "After unloading, COM_get_window_handle(\"ElmerModule\") returns "
                   << ElmerHandle << std::endl;
         std::cout << "Error : Module was not properly unloaded." << std::endl;
       }
       else{
         unloadWorks = true;
         std::cout << "ElmerModule Unloaded." << std::endl;
       }
       if(loadWorks & globWorks & initWorks & runWorks & finWorks & unloadWorks) works = true;
       result.UpdateResult("ElmerHandlesCheck:Works",works);
     }