ElmerFoamFSI: Simple_manifold_2::get_next_edge_interior
Edge_ID get_next_edge_interior (const Edge_ID & eID) const inline private
Definition at line 789 of file Simple_manifold_2.h.
References _is_str, _maxsize_real_elmts, _nspe, _oeIDs_ghost, _oeIDs_real_or_str, Facet_ID::eid(), get_edge_index(), is_ghost_element(), and Facet_ID::lid().
Referenced by get_next_edge().
{
     // If not a border edge, then track it within an element.
     int i=eID.lid()+1;
     if ( i>=_nspe) return Edge_ID( eID.eid(), 0);
     if ( _is_str || !is_ghost_element( eID.eid())) {
       int eindex = get_edge_index( Edge_ID(eID.eid(), i));
       if ( _oeIDs_real_or_str[eindex]==Edge_ID()) i=0;
     }
     else {
       int eindex = get_edge_index( Edge_ID(eID.eid(), i), _maxsize_real_elmts);
       if ( _oeIDs_ghost[eindex]==Edge_ID()) i=0;
     }
     return Edge_ID( eID.eid(), i);
   }