ElmerFoamFSI: fsicoupling::TransferDisplacementsToFluid
int TransferDisplacementsToFluid (solidagent * solidAgent, fluidagent * fluidAgent) inline
Definition at line 59 of file FsiCoupling.H.
References COM_get_array(), openfoamagent::Coordinates(), elmeragent::Coordinates(), fluidsAgent, fluidsInterfaceName, TransferObject::Interpolate(), openfoamagent::PaneID(), elmeragent::PaneID(), structuresAgent, structuresInterfaceName, transferAgent, and verblevel.
Referenced by Run(), TestingObject< ResultsType >::Test__FluidAgentRun(), TestingObject< ResultsType >::Test__SolidAgentRun(), TestingObject< ResultsType >::Test__TransferDisplacementsToFluid(), and TestingObject< ResultsType >::Test__TransferLoadsToStructures().
   {
     std::stringstream outString;
     // Masoud: Checking quality of coordinate transfer
     std::vector<double> crdVecSolid1(solidAgent->Coordinates());
     std::vector<double> crdVecFluid1(fluidAgent->Coordinates());
     if ( verblevel >= 3 ) {
        outString << "Solid Coodinates are : " << std::endl;
        for (int i = 0; i < crdVecSolid1.size()/3; i++)
           outString << crdVecSolid1[i*3] << " "
                     << crdVecSolid1[i*3+1] << " "
                     << crdVecSolid1[i*3+2] << std::endl;
        //StdOut(outString.str(),0, true);
        std::cout << outString.str() << std::endl;
        outString.clear();
        outString.str("");
        outString << " Fluid Coodinates are : " << std::endl;
        for (int i = 0; i < crdVecFluid1.size()/3; i++)
           outString << crdVecFluid1[i*3]   << " "
                     << crdVecFluid1[i*3+1] << " "
                     << crdVecFluid1[i*3+2] << std::endl;
        //StdOut(outString.str(),0,true);
        std::cout << outString.str() << std::endl;
        outString.clear();
        outString.str("");
     }
     // Masoud: End
     // Masoud: Checking quality of displacement transfer
     double *fluidDisp1 = NULL;
     double *fluidDisp2 = NULL;
     double *solidDisp1 = NULL;
     double *solidDisp2 = NULL;
     std::string fluidsCoordinateName(fluidsInterfaceName+".solidDisplacement");
     std::string solidsCoordinateName(structuresInterfaceName+".Displacements");
     COM_get_array(fluidsCoordinateName.c_str(),fluidsAgent->PaneID(),&fluidDisp1);
     COM_get_array(solidsCoordinateName.c_str(),structuresAgent->PaneID(),&solidDisp1);
     int numberFluidNodes = fluidsAgent->Coordinates().size()/3;
     int numberSolidNodes = structuresAgent->Coordinates().size()/3;
     if (verblevel >= 3){
       outString << "Fluid displacements before transfer: " << std::endl;
       for (int i = 0; i < numberFluidNodes; i++)
           outString << fluidDisp1[i*3] << " "
                     << fluidDisp1[i*3+1] << " "
                     << fluidDisp1[i*3+2] << std::endl;
      //StdOut(outString.str(),0,true);
       std::cout << outString.str() << std::endl;
       outString.clear();
       outString.str("");
       outString << " Solid displacements before transfer " << std::endl;
       outString << "Number of nodes: " << numberSolidNodes  << std::endl;
       for (int i = 0; i < numberSolidNodes; i++)
           outString << solidDisp1[i*3] << " "
                     << solidDisp1[i*3+1] << " "
                     << solidDisp1[i*3+2] << std::endl;
       //StdOut(outString.str(),0,true);
       std::cout << outString.str() << std::endl;
       outString.clear();
       outString.str("");
     }
     transferAgent->Interpolate("Displacements","solidDisplacement");
     //transferAgent->Interpolate("solidDisplacement","Displacements");
     if (verblevel >= 3){
       COM_get_array(fluidsCoordinateName.c_str(),fluidsAgent->PaneID(),&fluidDisp2);
       COM_get_array(solidsCoordinateName.c_str(),structuresAgent->PaneID(),&solidDisp2);
       outString << "Number of fluid nodes: " << numberFluidNodes  <<std::endl;
       outString << "Fluid displacements after transfer : " << std::endl;
       for (int i = 0; i < numberFluidNodes; i++)
           outString << fluidDisp2[i*3] << " "
                     << fluidDisp2[i*3+1] << " "
                     << fluidDisp2[i*3+2] << std::endl;
       //StdOut(outString.str(),0,true);
       outString << "Number of solid nodes: " << numberFluidNodes  <<std::endl;
       outString << "solid displacements after transfer : " << std::endl;
       for (int i = 0; i < numberSolidNodes; i++)
           outString << solidDisp2[i*3] << " "
                     << solidDisp2[i*3+1] << " "
                     << solidDisp2[i*3+2] << std::endl;
           std::cout << outString.str() << std::endl;
       outString.clear();
       outString.str("");
       // Masoud: Cheking if displacements are updated properly
       std::vector<double> crdVecSolid2(solidAgent->Coordinates());
       std::vector<double> crdVecFluid2(fluidAgent->Coordinates());
       outString << "Fluid Coodinate Updates : " << std::endl;
       for (int i = 0; i < crdVecFluid2.size(); i = i + 3)
       {
           // adding some value to it
           outString << crdVecFluid2[i]   - crdVecFluid1[i]  << " "
                     << crdVecFluid2[i+1] - crdVecFluid1[i+1]<< " "
                     << crdVecFluid2[i+2] - crdVecFluid1[i+2]<< std::endl;
       }
       //StdOut(outString.str(),0,true);
       std::cout << outString.str() << std::endl;
       outString.clear();
       outString.str("");
       outString << "Solid Coodinate Updates : " << std::endl;
       for (int i = 0; i < crdVecSolid2.size(); i = i + 3)
       {
           outString << crdVecSolid2[i]   - crdVecSolid1[i]  << " "
                     << crdVecSolid2[i+1] - crdVecSolid1[i+1]<< " "
                     << crdVecSolid2[i+2] - crdVecSolid1[i+2]<< std::endl;
       }
       //StdOut(outString.str(),0,true);
       std::cout << outString.str() << std::endl;
       outString.clear();
       outString.str("");
     }
     // Masoud: End
     return(0);
   };