ElmerFoamFSI: Simple_manifold_2::get_incident_real_edge
Edge_ID get_incident_real_edge (int vID) const inline
Get the ID of an incident real edge within the pane of a given node.
The incident edge may encode an isolated node.
Definition at line 396 of file Simple_manifold_2.h.
References _beIDs, _ieIDs_real_or_str, _size_real_borders, _size_rg_borders, COM_assertion, COM_assertion_msg, Facet_ID::eid(), get_next_ghost_edge_interior(), get_opposite_ghost_edge_border(), get_opposite_ghost_edge_interior(), get_origin(), Facet_ID::is_border(), is_real_border_edge(), and is_real_node().
{
     COM_assertion( is_real_node( vID));
     Edge_ID eID = _ieIDs_real_or_str[ vID-1];
     if ( eID.is_border() && eID.eid()<=int(_beIDs.size()) &&
          eID.eid()>_size_real_borders+_size_rg_borders) {
       // If vID is between real and ghost, and on the ghost boundary,
       // get the border edge between real and ghost.
       Edge_ID eID0 = eID = get_opposite_ghost_edge_border( eID);
       while ( (eID = get_opposite_ghost_edge_interior
                ( get_next_ghost_edge_interior(eID))) != eID0 &&
               !is_real_border_edge( eID));
       COM_assertion_msg( eID.is_border() && get_origin( eID)==vID,
                          "No real edge incident on given vertex");
     }
     return eID;
   }