ElmerFoamFSI: SolverUtils::GeoPrim::C3Box::init
void init (double x0, double y0, double z0, double x1, double y1, double z1) inline
Definition at line 1860 of file GeoPrimitives.H.
References C3Box::initd, C3Box::p1, C3Box::p2, C3Point::x(), C3Point::y(), and C3Point::z().
     {
       initd = true;
       p1.x(x0);
       p1.y(y0);
       p1.z(z0);
       p2.x(x1);
       p2.y(y1);
       p2.z(z1);
     };