ElmerFoamFSI: OpenFoamModuleDriver::TestingObject::Prologue
virtual void Prologue () inline virtual
Sets up the data fixtures for the tests.
This function gives the object a chance to allocate and set up any "fixtures" before the tests are run.
Definition at line 122 of file OpenFoamModuleDriverTest.H.
References TestingObject< ResultsType >::ExampleTestFixture, and TestingObject< ResultsType >::N.
Referenced by TestingObject< ResultsType >::Process(), TestingObject< ResultsType >::ProcessTests(), and TestingObject< ResultsType >::RunTest().
{
       ExampleTestFixture.assign("ExampleTestData");
       for(int i = 10;i < 10000000;i*=10) N.push_back(i);
     }