ElmerFoamFSI: ElmerModuleDriver::TestingObject::GetInputData
virtual int GetInputData (std::string suffix, std::string TestDir) inline virtual
Function to copy input data from source testing directory for use in unit tests.
Parameters
suffix std::string for the input data location (it is appended to the source directory inputted on the command line)
TestDir std::string path for directory to run the test in
Definition at line 325 of file ElmerModuleDriverTest.H.
References IRAD::Sys::ChDir(), IRAD::Sys::CreateDirectory(), IRAD::Sys::CWD(), IRAD::Sys::FILEEXISTS(), IRAD::Sys::ISDIR(), IRAD::Sys::ISLINK(), TestingObject< ResultsType >::SourceDirPath, and IRAD::Sys::SymLink().
Referenced by TestingObject< ResultsType >::Test__ElasticBeam3D_LoadFunction(), and TestingObject< ResultsType >::Test__ElmerUnitTests().
{
       std::cout << "In GetInputData" << std::endl;
       std::string DirName;
       std::string OrgDir;
       //Save original working directory for later
       OrgDir = IRAD::Sys::CWD();
       //Create full path for test input data directory
       DirName = SourceDirPath + suffix;
       //Check if data directory exists
       if(!IRAD::Sys::FILEEXISTS(DirName)){
         std::cout << "GetInputData Error: Could not find data directory, "
                   << DirName << ". Exiting (fail)." << std::endl;
         return -1;
       }
       std::ifstream Inf;
       std::ofstream Ouf;
       std::string InFileName;
       std::string OutFileName;
       int IntDir;
       //Create TestDir directory in current directory (if it doesn't
       //already exist) to run our tests in.
       if(!IRAD::Sys::FILEEXISTS(TestDir)){
         IntDir = IRAD::Sys::CreateDirectory(TestDir);
         if(IntDir == -1){
           std::cout << "GetInputData Error: Could not make directory, "
                     << TestDir << ". Exiting (fail)." << std::endl;
           return -1;
         }
       }
       //Open the input test data directory
       IRAD::Sys::Directory SourceDir(DirName);
       //Change directories to TestDir directory for running
       IntDir = IRAD::Sys::ChDir(TestDir);
       if(IntDir == -1){
         std::cout << "GetInputData Error: Could not change directories to "
                   << TestDir << ". Exiting (fail)." << std::endl;
         return -1;
       }
       //Copy input data to TestDir directory for running
       for(std::vector<std::string>::iterator it = SourceDir.begin();
           it != SourceDir.end(); ++it){
         InFileName = DirName + "/" + *it;
         OutFileName = IRAD::Sys::CWD() + "/" + *it;
         // copy source to distnation recursively
         if(IRAD::Sys::ISLINK(InFileName))
           // preserve links, don't traverse
           int IntDir = IRAD::Sys::SymLink(InFileName, OutFileName);
         else if(IRAD::Sys::ISDIR(InFileName)) {
           // recursively copy directories
           int IntDir = GetInputData(InFileName, OutFileName);
         } else {
           // copy files, travserse into directories recursively
           Inf.open(InFileName.c_str());
           Ouf.open(OutFileName.c_str());
           Ouf << Inf.rdbuf();
           Ouf.close();
           Inf.close();
         }
       }
       //Change directories to back to original directory
       IntDir = IRAD::Sys::ChDir(OrgDir);
       if(IntDir == -1){
         std::cout << "GetInputData Error: Could not change directories to "
                   << OrgDir << ". Exiting (fail)." << std::endl;
         return -1;
       }
       return 0;
     }