ElmerFoamFSI: SolverUtils::GeoPrim::C3Box::AddPoint
void AddPoint (const C3Point & p) inline
Definition at line 1939 of file GeoPrimitives.H.
References C3Box::initd, C3Box::p1, C3Box::p2, C3Point::x(), C3Point::y(), and C3Point::z().
     {
       if(!initd){
         p1 = p;
         p2 = p;
         initd = true;
       }
       else{
         if(p.x() < p1.x()) p1.x() = p.x();
         if(p.x() > p2.x()) p2.x() = p.x();
         if(p.y() < p1.y()) p1.y() = p.y();
         if(p.y() > p2.y()) p2.y() = p.y();
         if(p.z() < p1.z()) p1.z() = p.z();
         if(p.z() > p2.z()) p2.z() = p.z();
       }
     };