ElmerFoamFSI: SolverUtils::GeoPrim::CPlane::CPlane
CPlane (const std::vector< CPoint > & vec) inline
Definition at line 2024 of file GeoPrimitives.H.
References CPlane::A(), CPlane::B(), CPlane::C(), CPlane::n, CVector::normalize(), and CVector::x().
       : p(vec[0])
     {
       double A = vec[0].y()*(vec[1].z() - vec[2].z()) +
         vec[1].y()*(vec[2].z() - vec[0].z()) +
         vec[2].y()*(vec[0].z() - vec[1].z());
       double B = vec[0].z()*(vec[1].x() - vec[2].x()) +
         vec[1].z()*(vec[2].x() - vec[0].x()) +
         vec[2].z()*(vec[0].x() - vec[1].x());
       double C = vec[0].x()*(vec[1].y() - vec[2].y()) +
         vec[1].x()*(vec[2].y() - vec[0].y()) +
         vec[2].x()*(vec[0].y() - vec[1].y());
       //      double D = -1.0 * ( p1.x()*(p2.y()*p3.z() - p3.y()*p2.z()) +
       //                          p2.x()*(p3.y()*p1.z() - p1.y()*p3.z()) +
       //                          p3.x()*(p1.y()*p2.z() - p2.y()*p1.z()) );
       n.x(A).y(B).z(C);
       n.normalize();
     } ;