ElmerFoamFSI: SolverUtils::TransferObject::Transfer
int Transfer (const std::string & src_att, const std::string & trg_att, bool reverse = false) inline
Definition at line 313 of file InterfaceLayer.H.
References SolverUtils::COM_call_function(), COM_get_dataitem_handle(), TransferObject::transferhandle, TransferObject::win1, and TransferObject::win2.
Referenced by fsicoupling::TransferLoadsToStructures(), and fsicoupling::TransferPressuresToStructures().
     {
       std::string srcwin((reverse ? win2 : win1));
       std::string trgwin((reverse ? win1 : win2));
       std::string srcatt = srcwin + "." + src_att;
       std::string trgatt = trgwin + "." + trg_att;
       int src_handle = COM_get_dataitem_handle(srcatt.c_str());
       int trg_handle = COM_get_dataitem_handle(trgatt.c_str());
       if((src_handle <= 0) || (trg_handle <= 0))
         return(-1);
       COM_call_function(transferhandle,&src_handle,&trg_handle);
       return(0);
     };