ElmerFoamFSI: ElmerModuleDriver::ExampleProgram::ExampleProgramComLine::Initialize
void Initialize (void) inline virtual
This is where the actual options and arguments are described.
For details about what can be done in this function, see the documentation for the IRAD::Util::ComLineObject.
Reimplemented from ComLineObject.
Definition at line 87 of file Third_Party_Modules/ElmerFSI/trunk/include/ExampleProgram.H.
References ComLineObject::_description, ComLineObject::AddArgHelp(), ComLineObject::AddArgument(), ComLineObject::AddHelp(), ComLineObject::AddOption(), and SolverUtils::Ostr.
{
         AddOption('h',"help");
         AddOption('v',"verbosity",1);
         AddOption('o',"output",2,"filename");
         AddArgument("input",1);
         AddHelp("help","Prints this long version of help.");
         AddHelp("output","Specifies the name of the output file.");
         std::ostringstream Ostr;
         Ostr << "Mode-dependent input: Input <filename> for serial example"
              << "\n\t\tprogram, or <number of divisions> for parallel example.";
         AddArgHelp("input",Ostr.str());
         // The following commented string formation is kept around to
         // illustrate the required tabs and newlines to make the output
         // look proper:
         //
         //    Ostr << "Use fixed problem size in scalability analysis.  Only makes"
         //         << "\n\t\tsense when scalability mode is enabled.";
         //    Ostr.str("");
         Ostr.str("");
         Ostr << "Example ElmerModuleDriver program.";
         _description.assign(Ostr.str());
       };