ElmerFoamFSI: COM_resize_array
void COM_resize_array (const char * wa_str, int pane_id, void ** addr, int strd, int cap) inline
Resize an dataitem on a specific pane and return the address by setting addr.
Resize for all panes if pane-id is 0, in which case, do not set addr. The difference between resize and allocate is that resize will reallocate memory only if the current array cannot accomodate the requested capacity.
Definition at line 177 of file com_c++.hpp.
References COM_get_com(), and COM_base::resize_array().
Referenced by SolverUtils::AgentToPane(), SolverUtils::SurfaceMeshToPane(), and SolverUtils::VolumeMeshToPane().
 { COM_get_com()->resize_array( wa_str, pane_id, addr, strd, cap); }