ElmerFoamFSI: COM_get_panes
void COM_get_panes (const char * wname, std::vector< int > & pane_ids, int rank = -2) inline
Definition at line 327 of file com_c++.hpp.
References COM_get_com(), and COM_base::get_panes().
Referenced by openfoamagent::Initialize(), openfoamagentpar::Initialize(), elmeragent::Initialize(), elmeragentpar::Initialize(), main(), COM::parallelProgram(), SolverUtils::PopulateSolverAgentFromWindow(), TestingObject< ResultsType >::Test__ModuleFunctionStepFluid(), TestingObject< ResultsType >::Test__ModuleMeshRegistration(), and TestingObject< ResultsType >::Test__ModuleSurfaceData().
 { COM_get_com()->get_panes( wname, pane_ids, rank); }