ElmerFoamFSI: main
int main (int argc, char * argv[])
Definition at line 42 of file icoFsiElasticNonLinULSolidFoam.C.
References fsifoam_module::CreateFluidFields(), fsifoam_module::CreateInterZoneInterpolators(), fsifoam_module::CreateStructuresFields(), fsifoam_module::Dump(), fsifoam_module::FindGlobalFaceZones(), fsifoam_module::InitFluidMesh(), fsifoam_module::InitStructuresMesh(), fsifoam_module::InitTransportProperties(), fsifoam_module::ReadCouplingProperties(), fsifoam_module::RunTime(), fsifoam_module::Step(), and IRAD::Profiler::Time().
 {
   fsifoam_module fsifoam(argc,argv);
   fsifoam.InitFluidMesh();
   fsifoam.InitTransportProperties();
   fsifoam.CreateFluidFields();
   fsifoam.InitStructuresMesh();
   fsifoam.CreateStructuresFields();
   fsifoam.ReadCouplingProperties();
   fsifoam.CreateInterZoneInterpolators();
   fsifoam.FindGlobalFaceZones();
   Foam::Time &runTime(fsifoam.RunTime());
   //* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
   Info << "\nicoFsiElasticNonLinULSolidFoam:main: Starting time loop\n" << endl;
   while(!runTime.end()){
     Info << "icoFsiElasticNonLinULSolidFoam:main: Time = " << runTime.timeName() << nl << endl;
     fsifoam.Step();
     Info<< "ExecutionTime = " << runTime.elapsedCpuTime() << " s"
         << "  ClockTime = " << runTime.elapsedClockTime() << " s"
         << endl << endl;
     if (runTime.outputTime())
       fsifoam.Dump();
   }
   Info<< "icoFsiElasticNonLinULSolidFoam:main: End\n" << endl;
   return(0);
 }