ElmerFoamFSI: main
int main (int argc, char * argv[])
Get the handle for the module function and call it
Definition at line 19 of file IcoFoamModuleDriver.C.
References COM_call_function(), COM_finalize(), COM_get_function_handle(), COM_init(), COM_LOAD_MODULE_STATIC_DYNAMIC, and COM_UNLOAD_MODULE_STATIC_DYNAMIC.
{
   COM_init( &argc, &argv);
   std::cout << "After COM_init" << std::endl;
   COM_LOAD_MODULE_STATIC_DYNAMIC( IcoFoamModule, "Window1");
   int icoFoamModuleFunction_handle = COM_get_function_handle("Window1.IcoFoamModuleFunction");
   bool func = (icoFoamModuleFunction_handle > 0);
   std::cout << "func = " << func << std::endl;
   if(func)
     COM_call_function(icoFoamModuleFunction_handle,&argc,argv);
   COM_UNLOAD_MODULE_STATIC_DYNAMIC( IcoFoamModule, "Window1");
   COM_finalize();
   std::cout << "After COM_finalize" << std::endl;
 }