ElmerFoamFSI: SolverUtils::PopulateSolverAgentFromWindow
int SolverUtils::PopulateSolverAgentFromWindow (const std::string & windowName, FEM::SolverAgent & solverAgent, bool copyMode = false)
Definition at line 883 of file InterfaceLayer.H.
References COM_get_panes(), COM_get_window_handle(), and PaneToAgent().
Referenced by openfoamagent::Initialize(), openfoamagentpar::Initialize(), elmeragent::Initialize(), and elmeragentpar::Initialize().
   {
     // First, check that the window exists, if not, return an error = 1
     int windowHandle = COM_get_window_handle(windowName);
     if(!(windowHandle > 0))
       return(1);
     // Next, check to make sure there is only one pane. Multi-pane windows are not
     // yet supported. Returns 2 on this error.
     std::vector<int> paneIDs;
     COM_get_panes(windowName.c_str(),paneIDs);
     if(paneIDs.size() > 1)
       return(2);
     int returnCode = PaneToAgent(windowName,paneIDs[0],solverAgent,copyMode);
     if(returnCode)
       return(returnCode+2);
     return(0);
   };