ElmerFoamFSI: SolverUtils::CreateDataItemsFromSolution
int SolverUtils::CreateDataItemsFromSolution (const std::string & name, FEM::SolutionData & soln)
Definition at line 544 of file InterfaceLayer.H.
References COM_CHAR, COM_DOUBLE, COM_INT, COM_new_dataitem(), COM_RAWDATA, COM_set_array(), COM_set_size(), SolutionData::Data(), FieldMetaData::dsize, FieldMetaData::loc, SolutionData::Meta(), FieldMetaData::name, FieldMetaData::ncomp, and FieldMetaData::unit.
Referenced by RegisterSolver(), and RegisterSolverInto().
   {
     FEM::SolutionData::DataContainer &data = soln.Data();
     FEM::SolutionMetaData &meta = soln.Meta();
     FEM::SolutionMetaData::iterator mdi = meta.begin();
     while(mdi != meta.end()){
       Mesh::IndexType data_index = mdi - meta.begin();
       FEM::FieldMetaData &md = *mdi++;
       std::string dataitem_name(name+"."+md.name);
       COM_Type datatype = (md.dsize == 1 ? COM_CHAR :
                            md.dsize == 4 ? COM_INT  :
                            md.dsize == 8 ? COM_DOUBLE :
                            COM_RAWDATA);
       assert(datatype >= 0);
       COM::DataItem::Shorter_size wloc = ( md.loc == 's' ? 'w' :
                                            md.loc == 'm' ? 'p' :
                                            md.loc == 'c' ? 'e' :
                                            md.loc == 'n' ? 'n' : '0');
       assert(wloc != '0');
       COM_new_dataitem(dataitem_name,wloc,datatype,md.ncomp,md.unit.c_str());
       // Can go ahead and set the arrays for the solver globals
       if(md.loc == 's') {
         Mesh::IndexType bufsize = md.dsize * md.ncomp;
         if(md.dsize == 1) bufsize = data[data_index].size();
         assert(data[data_index].size() == bufsize);
         bufsize = 1;
         if(md.dsize == 1) bufsize = data[data_index].size();
         COM_set_size(dataitem_name,0,bufsize); // all global data get a size of 1, except strings
         COM_set_array(dataitem_name,0,const_cast<char *>(reinterpret_cast<const char *>
                                                           (data[data_index].data())));
       }
     }
     return(0);
   };