ElmerFoamFSI: SolverUtils::AgentToPane
int SolverUtils::AgentToPane (const std::string & name, int pane_id, FEM::SolverAgent & agent, bool copy = false)
Definition at line 626 of file InterfaceLayer.H.
References COM_CHAR, COM_DOUBLE, COM_get_array(), COM_INT, COM_RAWDATA, COM_resize_array(), COM_set_array(), COM_set_size(), UnstructuredMesh::con, SolutionData::Data(), FieldMetaData::dsize, FieldMetaData::loc, SolverAgent::Mesh(), SolutionData::Meta(), FieldMetaData::name, UnstructuredMesh::nc, FieldMetaData::ncomp, Connectivity::Nelem(), NodalCoordinates::Size(), SolverAgent::Solution(), and SurfaceMeshToPane().
Referenced by RegisterSolver(), and RegisterSolverInto().
   {
     FEM::SolutionData &soln = agent.Solution();
     Mesh::UnstructuredMesh &mesh = agent.Mesh();
     // First create a new pane with the mesh
     // Since we *know* that this is to be used for surfaces,
     // we'll just use it for one surface in this proof-of-concept
     // implementation.  It *should* be set up so that each solver
     // can register multiple meshes, some 2d, and some 3d.
     SurfaceMeshToPane(name,pane_id,agent.Mesh(),copy);
     FEM::SolutionData::DataContainer &data = soln.Data();
     FEM::SolutionMetaData &meta = soln.Meta();
     FEM::SolutionMetaData::iterator mdi = meta.begin();
     while(mdi != meta.end()){
       Mesh::IndexType data_index = mdi - meta.begin();
       FEM::FieldMetaData &md = *mdi++;
       std::string dataitem_name(name+"."+md.name);
       COM_Type datatype = (md.dsize == 1 ? COM_CHAR :
                            md.dsize == 4 ? COM_INT  :
                            md.dsize == 8 ? COM_DOUBLE :
                            COM_RAWDATA);
       assert(datatype >= 0);
       COM::DataItem::Shorter_size wloc = (md.loc == 's' ? 'w' :
                                            md.loc == 'm' ? 'p' :
                                            md.loc == 'c' ? 'e' :
                                            md.loc == 'n' ? 'n' : '0');
       assert(wloc != '0');
       //      COM_new_dataitem(dataitem_name,wloc,datatype,md.ncomp,md.unit.c_str());
       // Can go ahead and set the arrays for the solver globals
       if(md.loc != 's') {
         Mesh::IndexType orig_bufsize = data[data_index].size();
         Mesh::IndexType datasize = md.dsize * md.ncomp;
         Mesh::IndexType wanted_bufsize = datasize * ((md.loc == 'm') ? 1 :
                                                      (md.loc == 'c') ? mesh.con.Nelem() :
                                                      (md.loc == 'n') ? mesh.nc.Size() : 0);
         if(md.dsize != 1)
           assert(wanted_bufsize == orig_bufsize);
         else
           wanted_bufsize = data[data_index].size();
         if(md.loc == 'm')  // all global data get a size of 1, except strings
           COM_set_size(dataitem_name,pane_id,wanted_bufsize);
         if(copy){
           COM_resize_array(dataitem_name,pane_id);
           void *the_array = NULL;
           COM_get_array(dataitem_name.c_str(),pane_id,&the_array);
           std::memcpy(the_array,
                       const_cast<char *>(reinterpret_cast<const char *>(data[data_index].data())),
                       wanted_bufsize);
         }
         else {
           COM_set_array(dataitem_name,pane_id,
                         const_cast<char *>(reinterpret_cast<const char *>
                                            (data[data_index].data())));
         }
       }
     }
     return(0);
   };