ElmerFoamFSI: SolverUtils::RegisterSolverInto
int SolverUtils::RegisterSolverInto (const std::string & name, FEM::SolverAgent & agent)
Definition at line 905 of file InterfaceLayer.H.
References AgentToPane(), COM_window_init_done(), CreateDataItemsFromSolution(), and SolverAgent::Solution().
   {
     // First, pass through the metadata and create new dataitems.  For
     // solver-global dataitems, go ahead and set the size and array.
     // For other, non solver-global dataitems, delay processing until
     // "pane" setup.
     //    COM_new_window(name);
     CreateDataItemsFromSolution(name,agent.Solution());
     // Now that the solver global data is handled, we work on
     // the mesh-specific or Window Pane-specific data.
     //
     int pane_id = 101; // default - arbitrary, shouldnt be zero
     AgentToPane(name,pane_id,agent);
     COM_window_init_done(name);
     return(0);
   };