ElmerFoamFSI: SolverUtils::WriteVTKToStream
int SolverUtils::WriteVTKToStream (const std::string & name, FEM::SolverAgent & agent, std::ostream & Ostr)
Definition at line 687 of file InterfaceLayer.H.
References UnstructuredMesh::con, DataBuffer::Data(), SolutionData::Data(), FieldMetaData::dsize, SolutionData::GetFieldData(), FieldMetaData::loc, SolverAgent::Mesh(), SolutionData::Meta(), FieldMetaData::name, UnstructuredMesh::nc, FieldMetaData::ncomp, Connectivity::Nelem(), NodalCoordinates::NNodes(), SolverAgent::Solution(), and SolverUtils::Mesh::WriteVTKToStream().
Referenced by main(), COM::parallelProgram(), SolverModuleDriver::run(), SolverModuleDriver::vtkDump(), fsicouplingpar::WriteAgentToVTK(), and fsicoupling::WriteAgentToVTK().
   {
     FEM::SolutionData &soln = agent.Solution();
     Mesh::UnstructuredMesh &mesh = agent.Mesh();
     Mesh::WriteVTKToStream(name,mesh,Ostr);
     FEM::SolutionData::DataContainer &data = soln.Data();
     FEM::SolutionMetaData &meta = soln.Meta();
     FEM::SolutionMetaData::iterator mdi = meta.begin();
     Mesh::IndexType nnodes = mesh.nc.NNodes();
     Mesh::IndexType ncells = mesh.con.Nelem();
     // Write Point Data:
     bool there_is_point_data = false;
     while(mdi != meta.end()){
       Mesh::IndexType data_index = mdi - meta.begin();
       FEM::FieldMetaData &md = *mdi++;
       // It's a scalar or a double at nodes (i.e. its nodal field or flag data)
       if(md.loc == 'n' && ((md.dsize == 4) || (md.dsize == 8))){
         if(!there_is_point_data){
           Ostr << "POINT_DATA " << nnodes << std::endl;
           there_is_point_data = true;
         }
         std::string dataname(md.name);
         std::string datatype = (md.dsize == 4 ? "integer" : "double");
         if(md.ncomp == 1)
           Ostr << "SCALARS " << dataname << " " << datatype << " 1" << std::endl
                << "LOOKUP_TABLE default" << std::endl;
         else
           Ostr << "VECTORS " << dataname << " " << datatype << std::endl;
         if(md.dsize == 4){
           int *the_array = agent.Solution().GetFieldData(dataname).Data<int>();
           for(Mesh::IndexType i = 0;i < nnodes;i++){
             for(Mesh::IndexType j = 0;j < md.ncomp;j++)
               Ostr << the_array[i*md.ncomp+j] << " ";
             Ostr << std::endl;
           }
         }
         else {
           double *the_array   = agent.Solution().GetFieldData(dataname).Data<double>();
           for(Mesh::IndexType i = 0;i < nnodes;i++){
             for(Mesh::IndexType j = 0;j < md.ncomp;j++)
               Ostr << the_array[i*md.ncomp+j] << " ";
             Ostr << std::endl;
           }
         }
       }
     }
     // Next pass for Cell data
     mdi = meta.begin();
     bool there_is_cell_data = false;
     while(mdi != meta.end()){
       Mesh::IndexType data_index = mdi - meta.begin();
       FEM::FieldMetaData &md = *mdi++;
       // It's a scalar or a double at cells (i.e. its nodal field or flag data)
       if(((md.loc == 'c') || (md.loc == 'e')) && ((md.dsize == 4) || (md.dsize == 8))){
         if(!there_is_cell_data){
           Ostr << "CELL_DATA " << ncells << std::endl;
           there_is_cell_data = true;
         }
         std::string dataname(md.name);
         std::string datatype = (md.dsize == 4 ? "integer" : "double");
         if(md.ncomp == 1)
           Ostr << "SCALARS " << dataname << " " << datatype << " 1" << std::endl
                << "LOOKUP_TABLE default" << std::endl;
         else
           Ostr << "VECTORS " << dataname << " " << datatype << std::endl;
         if(md.dsize == 4){
           int *the_array   = agent.Solution().GetFieldData(dataname).Data<int>();
           for(Mesh::IndexType i = 0;i < ncells;i++){
             for(Mesh::IndexType j = 0;j < md.ncomp;j++)
               Ostr << the_array[i*md.ncomp+j] << " ";
             Ostr << std::endl;
           }
         }
         else {
           double *the_array   = agent.Solution().GetFieldData(dataname).Data<double>();
           for(Mesh::IndexType i = 0;i < ncells;i++){
             for(Mesh::IndexType j = 0;j < md.ncomp;j++)
               Ostr << the_array[i*md.ncomp+j] << " ";
             Ostr << std::endl;
           }
         }
       }
     }
     return(0);
   };