ElmerFoamFSI: SolverUtils::PopulateSolutionMetaDataFromPane
int SolverUtils::PopulateSolutionMetaDataFromPane (const std::string & windowName, int paneID, FEM::SolutionData & soln)
Definition at line 590 of file InterfaceLayer.H.
References COM_CHAR, COM_CHARACTER, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_get_dataitem(), COM_INT, COM_INTEGER, COM_RAWDATA, COM_REAL, SolutionData::Data(), FieldMetaData::dsize, GetDataItemNames(), FieldMetaData::loc, SolutionData::Meta(), FieldMetaData::name, FieldMetaData::ncomp, and FieldMetaData::unit.
Referenced by CreateSolutionFromPane().
   {
     FEM::SolutionData::DataContainer &data(soln.Data());
     FEM::SolutionMetaData &meta(soln.Meta());
     std::vector<std::string> dataItemNames(GetDataItemNames(windowName));
     std::vector<std::string>::iterator itemNameIt = dataItemNames.begin();
     while(itemNameIt != dataItemNames.end()){
       std::string iName(*itemNameIt++);
       std::string aName(windowName+"."+iName);
       char loc = 0;
       COM_Type dataType = COM_RAWDATA;
       FEM::FieldMetaData metaData;
       metaData.name = iName;
       int dataNComp = 0;
       COM_get_dataitem(aName.c_str(),&loc,&dataType,&dataNComp,&(metaData.unit));
       metaData.dsize = (dataType == COM_CHAR   ? 1 :
                         dataType == COM_INT    ? 4 :
                         dataType == COM_DOUBLE ? 8 :
                         dataType == COM_CHARACTER ? 1 :
                         dataType == COM_INTEGER   ? 4 :
                         dataType == COM_REAL      ? 8 :
                         dataType == COM_DOUBLE_PRECISION ? 9 : 0);
       if(metaData.dsize == 0)
         continue;
       metaData.ncomp = dataNComp;
       metaData.loc = (loc == 'w' ? 's' :
                       loc == 'p' ? 'm' :
                       loc == 'e' ? 'c' :
                       loc == 'n' ? 'n' : '0');
       if(metaData.loc == '0')
         continue;
       meta.push_back(metaData);
     }
     return(0);
   };