ElmerFoamFSI: SolverUtils::VolumeMeshToPane
int SolverUtils::VolumeMeshToPane (const std::string & wname, int pane_id, Mesh::UnstructuredMesh & mesh, bool copy = true)
Creates a window from a Mesh object. (copies data)
Definition at line 167 of file InterfaceLayer.H.
References Connectivity::AddElement(), COM_get_array(), COM_resize_array(), COM_set_array(), COM_set_size(), UnstructuredMesh::con, UnstructuredMesh::nc, Connectivity::Nelem(), and NodalCoordinates::Size().
   {
     unsigned int number_of_nodes = mesh.nc.Size();
     COM_set_size((wname+".nc").c_str(),pane_id,number_of_nodes);
     if(copy){
       COM_resize_array((wname+".nc").c_str(),pane_id);
       double *nc = NULL;
       COM_get_array((wname+".nc").c_str(),pane_id,&nc);
       std::memcpy(nc,mesh.nc[1],number_of_nodes*3*sizeof(double));
     }
     else {
       COM_set_array((wname+".nc"),pane_id,mesh.nc[1]);
     }
     Mesh::Connectivity tets;
     Mesh::Connectivity bricks;
     Mesh::Connectivity pyrs;
     Mesh::Connectivity pris;
     Mesh::Connectivity::iterator ci = mesh.con.begin();
     bool known_element_type = false;
     while(ci != mesh.con.end()){
       if(ci->size() == 4)
         tets.AddElement(*ci++);
       else if (ci->size() == 5)
         pyrs.AddElement(*ci++);
       else if (ci->size() == 6)
         pris.AddElement(*ci++);
       else if (ci->size() == 8)
         bricks.AddElement(*ci++);
       else
         assert(known_element_type);
     }
     unsigned int number_of_tets   = tets.Nelem();
     unsigned int number_of_bricks = bricks.Nelem();
     unsigned int number_of_pyrs   = pyrs.Nelem();
     unsigned int number_of_pris   = pris.Nelem();
     int *con_array = NULL;
     if(number_of_tets > 0){
       COM_set_size((wname+".:T4:").c_str(),pane_id,number_of_tets);
       COM_resize_array((wname+".:T4:").c_str(),pane_id);
       COM_get_array((wname+".:T4:").c_str(),pane_id,&con_array);
       ci = tets.begin();
       while(ci != tets.end()){
         unsigned int element_id = ci - tets.begin() + 1;
         unsigned int element_index = element_id - 1;
         con_array[4*element_index]   = (*ci)[0];
         con_array[4*element_index+1] = (*ci)[1];
         con_array[4*element_index+2] = (*ci)[2];
         con_array[4*element_index+3] = (*ci)[3];
         ci++;
       }
     }
     if(number_of_pyrs > 0){
       COM_set_size((wname+".:P5:").c_str(),pane_id,number_of_pyrs);
       COM_resize_array((wname+".:P5:").c_str(),pane_id);
       COM_get_array((wname+".:P5:").c_str(),pane_id,&con_array);
       ci = pyrs.begin();
       while(ci != pyrs.end()){
         unsigned int element_id = ci - pyrs.begin() + 1;
         unsigned int element_index = element_id - 1;
         con_array[5*element_index]   = (*ci)[0];
         con_array[5*element_index+1] = (*ci)[1];
         con_array[5*element_index+2] = (*ci)[2];
         con_array[5*element_index+3] = (*ci)[3];
         con_array[5*element_index+4] = (*ci)[4];
         ci++;
       }
     }
     if(number_of_pris > 0){
       COM_set_size((wname+".:P6:").c_str(),pane_id,number_of_pris);
       COM_resize_array((wname+".:P6:").c_str(),pane_id);
       COM_get_array((wname+".:P6:").c_str(),pane_id,&con_array);
       ci = pris.begin();
       while(ci != pris.end()){
         unsigned int element_id = ci - pris.begin() + 1;
         unsigned int element_index = element_id - 1;
         con_array[6*element_index]   = (*ci)[0];
         con_array[6*element_index+1] = (*ci)[1];
         con_array[6*element_index+2] = (*ci)[2];
         con_array[6*element_index+3] = (*ci)[3];
         con_array[6*element_index+4] = (*ci)[4];
         con_array[6*element_index+4] = (*ci)[5];
         ci++;
       }
     }
     if(number_of_bricks > 0){
       COM_set_size((wname+".:B8:").c_str(),pane_id,number_of_bricks);
       COM_resize_array((wname+".:B8:").c_str(),pane_id);
       COM_get_array((wname+".:B8:").c_str(),pane_id,&con_array);
       ci = bricks.begin();
       while(ci != bricks.end()){
         unsigned int element_id = ci - bricks.begin() + 1;
         unsigned int element_index = element_id - 1;
         con_array[8*element_index]   = (*ci)[0];
         con_array[8*element_index+1] = (*ci)[1];
         con_array[8*element_index+2] = (*ci)[2];
         con_array[8*element_index+3] = (*ci)[3];
         con_array[8*element_index+4] = (*ci)[4];
         con_array[8*element_index+5] = (*ci)[5];
         con_array[8*element_index+6] = (*ci)[6];
         con_array[8*element_index+7] = (*ci)[7];
         ci++;
       }
     }
     return(0);
   }