ElmerFoamFSI: SolverUtils::PopulateSolutionDataFromPane
int SolverUtils::PopulateSolutionDataFromPane (const std::string & windowName, int paneID, FEM::SolutionData & solutionData, bool copyMode = false)
Definition at line 835 of file InterfaceLayer.H.
References COM_get_array(), SolutionData::Data(), FieldMetaData::loc, SolutionData::Meta(), FieldMetaData::name, and SolutionData::SetFieldBuffer().
Referenced by CreateSolutionFromPane().
   {
     FEM::SolutionData::DataContainer &data(solutionData.Data());
     FEM::SolutionMetaData &meta(solutionData.Meta());
     FEM::SolutionMetaData::iterator mdi = meta.begin();
     while(mdi != meta.end()){
       Mesh::IndexType dataIndex = mdi - meta.begin();
       FEM::FieldMetaData &metaData(*mdi++);
       std::string dataItemName(windowName+"."+metaData.name);
       int getPaneID = paneID;
       if(metaData.loc == 's')
         getPaneID = 0;
       Mesh::IndexType bufferSize = data[dataIndex].size();
       int dataStride = 0;
       void *dataArray = NULL;
       COM_get_array(dataItemName.c_str(),getPaneID,&dataArray,&dataStride);
       if(!dataArray)
         continue;
       if(copyMode){
         std::memcpy(const_cast<char *>(reinterpret_cast<const char *>(data[dataIndex].data())),
                     dataArray,bufferSize);
       } else {
         solutionData.SetFieldBuffer(metaData.name,dataArray);
       }
     }
     return(0);
   };