ElmerFoamFSI: SolverUtils::SurfaceMeshToPane
int SolverUtils::SurfaceMeshToPane (const std::string & wname, int pane_id, Mesh::UnstructuredMesh & mesh, bool copy = true)
Creates a window pane from a Mesh object. (copy mode or use mode)
Definition at line 97 of file InterfaceLayer.H.
References Connectivity::AddElement(), COM_get_array(), COM_resize_array(), COM_set_array(), COM_set_size(), UnstructuredMesh::con, UnstructuredMesh::nc, Connectivity::Nelem(), and NodalCoordinates::Size().
Referenced by AgentToPane().
   {
     unsigned int number_of_nodes = mesh.nc.Size();
     COM_set_size((wname+".nc").c_str(),pane_id,number_of_nodes);
     if(copy){
       COM_resize_array((wname+".nc").c_str(),pane_id);
       double *nc = NULL;
       COM_get_array((wname+".nc").c_str(),pane_id,&nc);
       std::memcpy(nc,mesh.nc[1],number_of_nodes*3*sizeof(double));
     }
     else {
       // Masoud : adding condition to check any nodes resgistered
       if (number_of_nodes != 0)
          COM_set_array((wname+".nc"),pane_id,mesh.nc[1]);
     }
     // Connectivities are *always* copied - this is because
     // the native format does not sort the elements into their
     // respective types.  It is also not a contiguous data
     // structure as in the Window.
     Mesh::Connectivity tris;
     Mesh::Connectivity quads;
     Mesh::Connectivity::iterator ci = mesh.con.begin();
     bool known_element_type = false;
     while(ci != mesh.con.end()){
       if(ci->size() == 3)
         tris.AddElement(*ci++);
       else if (ci->size() == 4)
         quads.AddElement(*ci++);
       else
         assert(known_element_type);
     }
     unsigned int number_of_tris  = tris.Nelem();
     unsigned int number_of_quads = quads.Nelem();
     int *con_array = NULL;
     if(number_of_tris > 0){
       COM_set_size((wname+".:t3:").c_str(),pane_id,number_of_tris);
       COM_resize_array((wname+".:t3:").c_str(),pane_id);
       COM_get_array((wname+".:t3:").c_str(),pane_id,&con_array);
       ci = tris.begin();
       while(ci != tris.end()){
         unsigned int element_id = ci - tris.begin() + 1;
         unsigned int element_index = element_id - 1;
         con_array[3*element_index]   = (*ci)[0];
         con_array[3*element_index+1] = (*ci)[1];
         con_array[3*element_index+2] = (*ci)[2];
         ci++;
       }
     }
     if(number_of_quads > 0){
       COM_set_size((wname+".:q4:").c_str(),pane_id,number_of_quads);
       COM_resize_array((wname+".:q4:").c_str(),pane_id);
       COM_get_array((wname+".:q4:").c_str(),pane_id,&con_array);
       ci = quads.begin();
       while(ci != quads.end()){
         unsigned int element_id = ci - quads.begin() + 1;
         unsigned int element_index = element_id - 1;
         con_array[4*element_index]   = (*ci)[0];
         con_array[4*element_index+1] = (*ci)[1];
         con_array[4*element_index+2] = (*ci)[2];
         con_array[4*element_index+3] = (*ci)[3];
         ci++;
       }
     }
     //  COM_window_init_done(wname.c_str());
     return(0);
   }