#!/bin/bash

export ElmerFoamTop=$1
export installDir=$ElmerFoamTop/support_install
noTest=false

if [ "$1" = "notest" ] || [ "$1" = "NoTest" ] || [ "$1" = "NOTEST" ] || [ "$2" = "notest" ] || [ "$2" = "NoTest" ] || [ "$2" = "NOTEST" ] 
then
  noTest=true
fi

source $ElmerFoamTop/BuildTools/BashSourceScript $ElmerFoamTop
if [ $? -ne 0 ]; then exit 1; fi

cd $ElmerFoamTop
mkdir build
cd build
cmake .. -DCMAKE_PREFIX_PATH=$installDir
if [ $? -ne 0 ]; then exit 1; fi
make
if [ $? -ne 0 ]; then exit 1; fi
if $noTest
then
  echo "Not running tests for ElmerFoamFSI Driver"
else
  make test
  if [ $? -ne 0 ]; then exit 1; fi
fi
