#!/bin/bash

export ElmerFoamTop=$1
export installDir=$ElmerFoamTop/support_install

isFirst=false
yesTest=true
buildFoam=true
runPatch=true

for var in "$@"
do
  var="$(echo "$var" | awk '{print tolower($0)}')"
  if [ "$var" = "first" ] 
  then
    isFirst=true
  fi
  if [ "$var" = "notest" ]  
  then
    yesTest=false
  fi
  if [ "$var" = "nofoam" ]  
  then
    buildFoam=false
  fi
  if [ "$var" = "nopatch" ]
  then
    runPatch=false
  fi
done

source $ElmerFoamTop/BuildTools/BashSourceScript $ElmerFoamTop
if [ $? -ne 0 ]; then exit 1; fi

cd $ElmerFoamTop/IMPACT
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$installDir
if [ $? -ne 0 ]; then exit 1; fi
make
if [ $? -ne 0 ]; then exit 1; fi
make install
if [ $? -ne 0 ]; then exit 1; fi
if $yesTest 
then 
  make test
fi
if [ $? -ne 0 ]; then exit 1; fi
cd $topSourceDir
