#!/bin/bash

export ElmerFoamTop=$1
export installDir=$ElmerFoamTop/support_install

source $ElmerFoamTop/BuildTools/BashSourceScript $ElmerFoamTop
if [ $? -ne 0 ]; then exit 1; fi

cd $ElmerFoamTop/Third_Party_Modules/OpenFoamFSI/trunk/
mkdir build
cd build
cmake .. -DCMAKE_PREFIX_PATH=$installDir
if [ $? -ne 0 ]; then exit 1; fi
make
if [ $? -ne 0 ]; then exit 1; fi
make test
cd $ElmerFoamTop
