#!/bin/bash

export ElmerFoamTop=$1

i=$((${#ElmerFoamTop}-1))
char="${ElmerFoamTop:$i:1}"

if [ "$char" = "/" ]
then
  ElmerFoamTop="${ElmerFoamTop:0:$i}"
fi

source $ElmerFoamTop/BuildTools/BashSourceScript $ElmerFoamTop
if [ $? -ne 0 ]; then exit 1; fi

isFirst=false
 
 if [ "$2" = "First" ] || [ "$2" = "FIRST" ] || [ "$2" = "first" ]
 then
   isFirst=true
 fi


cd ~/foam/foam-extend-3.0
if $isFirst
then
  ./Allwmake.firstInstall
  if [ $? -ne 0 ]; then exit 1; fi
else 
  ./Allwmake
  if [ $? -ne 0 ]; then exit 1; fi
fi
