#!/bin/bash

status=0

# Set our current directory, which should be the top
# level source for ElmerFoamFSI
topSourceDir=$1
installDir="$topSourceDir/support_install"

# Patch Openfoam build files

cd foam/foam-extend-3.2/
#cp $topSourceDir/Third_Party_Modules/OpenFoamFSI/trunk/openFoamGitPatch .
#if [ $? -ne 0 ]; then status=1; fi
#git apply openFoamGitPatch
#if [ $? -ne 0 ]; then status=1; fi
cd $topSourceDir

# Copy the appropriate source files into elmer
cd elmerfem/fem/src/
ln -s $topSourceDir/Third_Party_Modules/ElmerFSI/trunk/native/ ElmerModule
if [ $? -ne 0 ]; then status=1; fi

# Patch the elmer source
patch < ElmerModule/ElmerPatch
if [ $? -ne 0 ]; then status=1; fi

FILES="$1/elmerfem/fem/src/*"
for f in $FILES
do
  sed -i 's/MPI_COMM_WORLD/ElmerModuleComm/g' $f
done
FILES="$1/elmerfem/fem/src/modules/*"
for f in $FILES
do
  sed -i 's/MPI_COMM_WORLD/ElmerModuleComm/g' $f
done

cd $topSourceDir

exit $status
