#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd fluid;
cleanTimeDirectories;
cleanCase;
\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones*
\rm -rf VTK case.foam history
\rm *.vtu
\rm *.vtk
\rm prb*.dat

cd ../solid;
cleanTimeDirectories;
cleanCase;
\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones*
\rm -rf VTK case.foam history

cd ..
./removeSerialLinks fluid solid
