#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd fluid;
runApplication blockMesh
runApplication changeDictionary
runApplication setSet -batch batch.setSet
runApplication setsToZones -noFlipMap
runApplication decomposePar

cd ../solid;
runApplication blockMesh
runApplication changeDictionary
runApplication setSet -batch batch.setSet
runApplication setsToZones -noFlipMap
runApplication decomposePar

cd ..
./makeLinks fluid solid
